gip-inclusion/rdv-insertion

.rubocop.yml, app/controllers/applicants_controller.rb, app/controllers/concerns/authenticated_controller_concern.rb, app/controllers/departments_controller.rb, app/controllers/sessions_controller.rb, app/javascript/react/actions/createApplicant.js, app/javascript/react/components/Applicant.jsx, app/javascript/react/components/ApplicantList.jsx, app/javascript/react/pages/Applicants.jsx, app/models/agent.rb, app/models/department.rb, app/policies/department_policy.rb, app/services/create_applicant.rb, app/services/find_or_create_agent.rb, app/views/applicants/index.html.erb, app/views/departments/index.html.erb, config/routes.rb, db/migrate/20210902084652_add_department_agents.rb, db/schema.rb, spec/controllers/applicants_controller_spec.rb, spec/controllers/departments_controller_spec.rb, spec/controllers/invitations_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/factories/agent.rb, spec/policies/department_policy_spec.rb, spec/services/create_applicant_spec.rb, spec/services/find_or_create_agent_spec.rb
Cette PR contient plusieurs refactors de l'application existante,  les principaux étant: 
- Changement de la relation entre `agent` et `department` en passant de one-to-one à one-to-many pour être plus iso avec ce qu'il se fait sur Rdv-Solidarités
- Changement de certaines routes et actions pour être plus REST en nestant notamment les actions liées aux `applicants` au sein des `departments`.
=> refactor(app): Refactor of routes and model relationships

.env.example, app/controllers/invitations_controller.rb, app/services/invitations/send_sms.rb, config/routes.rb, db/migrate/20210907172021_add_seen_to_invitations.rb, db/schema.rb, spec/controllers/invitations_controller_spec.rb, spec/services/invitations/send_sms_spec.rb
Cette PR vise à permettre l'envoi d'un lien raccourci à l'utilisateur, un problème soulevé dans l'issue #13. Le code ajouté correspond à :
- Créer une nouvelle route GET , qui prend en paramètres le token d'invitation
- Au sein de l'action du controller associée (invitations#redirect), le record d'invitation associé au token est récupéré.
- Ajout d'une colonne seen de type booléen sur la table invitations qui est égale à false par défaut et qui est updatée à true une fois que le record d'invitation est retrouvé au sein de l'action invitations#redirect
- Redirection de l'utilisateur sur le link associé à l'invitation qui redirige vers rdv-solidarités
=> Feat/Raccourcir le lien d'invitation envoyé au bRSA

app/controllers/concerns/filter_rdv_solidarites_webhooks_concern.rb, app/jobs/notify_applicant_job.rb, config/initializers/sidekiq.rb, spec/controllers/rdv_solidarites_webhooks_controller_spec.rb
We decided not to notify applicants for the moment when a RDV is updated.
So I added a filter on the update webhooks to not process them anymore.
=> refactor(yonne): do not notify on rdv update

app/controllers/applicants_controller.rb
We load the applications along with the applicants to avoid querying each invitation afterwards.
=> fix(app): Load invitations along with applicants

app/javascript/react/models/Applicant.js
Sur le fichier de la Drôme une "x" est placée quand un email n'est pas présent, ce qui renvoie une erreur lors de la validation de l'email.
Dans cette PR je n'envoie pas aux API les emails s'ils ne contiennent pas un "@".
=> fix(drome): format email attribute

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
Dans cette PR j'ajoute un context avec l'id et le mail de l'agent aux erreurs sentry, ainsi que la gem `sentry-sidekiq` pour capturer les erreurs se produisant dans nos workers
=> feat(sentry): Add context to sentry events

app/services/send_transactional_sms.rb
Sendinblue renvoie une erreur depuis ce matin lorsqu'on essaie d'envoyer des SMS.
Le message d'erreur dise  "message trop long" alors qu'il n'apparaissait  pas avant. 
Je vais ouvrir un ticket sur le support de SendInBlue, mais en attendant j'ai vu qu'enlever les accents circonflexes  résolvait le problème. 
J'envoie aussi l'erreur à Sentry pour  être alerté quand ça arrive.
=> fix(sms): format sms content

app/services/invitations/send_sms.rb, app/services/send_transactional_sms.rb, spec/services/invitations/send_sms_spec.rb
Je remplaçais les "ô" par des "e" dans la PR précédente 🤦, cette PR répare ça et assure de n'envoyer des sms que en production.
=> fix(sms): format content correctly

.rubocop.yml, db/migrate/20211102161424_change_department_table.rb, db/schema.rb, spec/mailers/invitation_mailer_spec.rb, spec/services/invitations/create_spec.rb
3eme partie de la refacto liée à #75 .
Cette PR vient après #107 .
Dans cette PR j'enlève les liens qui reliait la table `departments` aux tables `agents` et `applicants` et j'ajoute un lien 1:many entre la table `departments` et `organisations`.
=> refactor(app): Create organisations [3/4]

app/javascript/react/pages/ApplicantsUpload.jsx, app/javascript/stylesheets/components/_card.scss, app/javascript/stylesheets/components/_title.scss, app/models/department.rb, app/models/organisation.rb, app/services/invitations/compute_link.rb, app/services/notifications/rdv_created.rb, app/services/notifications/rdv_updated.rb, app/views/applicants/index.html.erb, app/views/organisations/index.html.erb, app/views/uploads/new.html.erb, db/migrate/20211102171611_change_organisations.rb, db/schema.rb, db/seeds.rb, spec/factories/department.rb, spec/factories/organisation.rb, spec/services/invitations/compute_link_spec.rb, spec/services/invitations/send_sms_spec.rb, spec/services/notifications/rdv_cancelled_spec.rb, spec/services/notifications/rdv_created_spec.rb
4eme et dernière  partie de la refacto liée à #75 .
Cette PR vient après #112 .
Dans cette PR j'enlève les attributs de la table `organisations` qui ne se retrouvent qu'au niveau des `departments` (`region`, `number`, `capital`).
Je fais les changements associées pour récupérer ces attributs sur les `departments` et non plus sur les `organisations` dans le code.
L'index des organisations devient semblable à celui de RDVS:
=> refactor(app): Create organisations [4/4]

app/services/notifications/notify_applicant.rb, app/views/applicants/_search_form.html.erb, spec/services/notifications/notify_applicant_spec.rb
Cette PR fait suite au mail de Guillaume Faure.
Lorsqu'un RDV est pris sur RDVS pour un allocataire qui n'a pas de téléphone pour des raisons d'agenda, on ne procède pas à la notification mais on ne considère pas que c'est un échec (cf. https://sentry.io/organizations/betagouv-f7/issues/2730054987).
=> fix(notifications): Do not raise when no phone

app/services/rdv_solidarites_api/base.rb, app/services/rdv_solidarites_api/create_user.rb, app/services/rdv_solidarites_api/retrieve_invitation_token.rb, app/services/rdv_solidarites_api/retrieve_motifs.rb, app/services/rdv_solidarites_api/retrieve_resources.rb, app/services/rdv_solidarites_api/retrieve_user.rb, spec/services/rdv_solidarites_api/create_user_spec.rb, spec/services/rdv_solidarites_api/retrieve_invitation_token_spec.rb, spec/services/rdv_solidarites_api/retrieve_motifs_spec.rb, spec/services/rdv_solidarites_api/retrieve_resources_spec.rb, spec/services/rdv_solidarites_api/retrieve_user_spec.rb
close #109 
Pour permettre un affichage des erreurs envoyées par l'API de RDV-Solidarités, cette PR substitue les `errors` par les `error_messages`
=> Fix/Translate rdv-solidarites errors in french

app/services/invitations/compute_link.rb, app/services/invitations/create.rb, app/services/retrieve_geolocalisation.rb, spec/services/invitations/compute_link_spec.rb, spec/services/invitations/create_spec.rb, spec/services/retrieve_geolocalisation_spec.rb
Dans cette PR j'introduis un service qui récupère les attributs géographiques (`latitude`, `longitude`, `city_code` et `street_ban_id`) liés à l'utilisateur à partir de son adresse en requêtant [l'API Adresse](https://adresse.data.gouv.fr/api-doc/adresse).
Je mets ces attributs (lorsqu'ils sont retrouvés avec succès) dans le lien d'invitation vers RDV-Solidarités envoyé à l'utilisateur.
Je change également les liens d'invitations suite à un changement dans RDV-Solidarités (voir https://github.com/betagouv/rdv-solidarites.fr/pull/1865). Cette PR ne doit donc pas être déployé avant celle concernant RDV-Solidarités.
=> feat(invitations): add geolocalisation attributes to invitations

app/controllers/stats_controller.rb, app/helpers/stats_helper.rb, app/models/applicant.rb, app/views/stats/index.html.erb
Cette PR vise à limiter l'affichage des statistiques pour les départements qui n'utilisent RDV-I que pour envoyer des convocations.
En attendant son intégration à RDV-I, le département des Ardennes est temporairement masqué pour éviter d'afficher des stats vides.
=> fix(stats): hide stats for notify_applicant departments + temp hiding of Ardennes

app/models/concerns/has_phone_number_concern.rb, app/services/invitations/send_sms.rb, app/services/notifications/notify_applicant.rb, app/services/send_transactional_sms.rb, spec/services/invitations/send_sms_spec.rb, spec/services/notifications/notify_applicant_spec.rb, spec/services/notifications/rdv_cancelled_spec.rb, spec/services/notifications/rdv_created_spec.rb, spec/services/send_transactional_sms_spec.rb
Cette PR a pour effet de ne plus formater le numéro de téléphone avant de le stocker en DB, mais seulement au moment d'envoyer un SMS.
La motivation derrière ce changement est qu'avec [la méthode de validation actuelle](https://github.com/betagouv/rdv-insertion/blob/dd8abe10409b044e7cac545fc71d280be7414554/app/models/concerns/has_phone_number_concern.rb#L17), il arrive qu'un numéro de téléphone non parsé soit valide alors que ce même numéro parsé ne l'est pas, ce qui pose problème.
De plus, cela est plus homogène avec ce qui se fait sur RDV-S (`phone_number` <=> `phone_number`).
=> fix(applicant): do not store parsed phone numbers

app/services/invitations/send_sms.rb, app/services/notifications/notify_applicant.rb, app/services/send_transactional_sms.rb, spec/services/invitations/send_sms_spec.rb, spec/services/notifications/notify_applicant_spec.rb, spec/services/notifications/rdv_cancelled_spec.rb, spec/services/notifications/rdv_created_spec.rb, spec/services/send_transactional_sms_spec.rb
Dans cette PR, j'ajoute un argument `sender_name` au call de `SendTransactionalSms` afin de personnaliser l'émetteur en fonction du CD.
Le texte du SMS a également été amendé pour respecter les changements vus avec la Drôme.
=> feat(invitations): change sender name + sms wording

app/controllers/applicants_controller.rb, app/javascript/react/components/Applicant.jsx, app/javascript/react/models/Applicant.js, app/javascript/react/pages/ApplicantsUpload.jsx, app/models/applicant.rb, app/views/applicants/_applicant_form.html.erb, app/views/applicants/show.html.erb, db/migrate/20211214113405_add_allocation_starting_date_to_applicants.rb, db/migrate/20211214113405_add_rights_opening_date_to_applicants.rb, db/schema.rb
Dans cette PR, j'ajoute l'attribut `allocation_starting_date` à la table `applicants`, qui correspond à la date d'ouverture des droits ou à la date d'entrée dans le flux des allocataires. Cette date est récupérée dans le fichier à l'upload, puis utilisée pour calculer le délai d'orientation. Elle a également été ajoutée aux pages show et edit.
Le nom affiché est "Date d'entré flux" (vu avec Claire).
=> feat(applicants): add allocation_starting_date

app/javascript/react/pages/ApplicantsUpload.jsx
La date d'entrée du flux n'était pas formatée au moment de lire le fichier excel et n'était pas affichée ni prise en compte correctement. Ce fix fait appel à la fonction `excelDateToString` au moment de récupérer la date.
=> fix(upload): format rights opening date

app/controllers/static_pages_controller.rb, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/components/_footer.scss, app/javascript/stylesheets/components/_image.scss, app/javascript/stylesheets/components/_navbar.scss, app/javascript/stylesheets/components/_title.scss, app/views/applicants/index.html.erb, app/views/common/_footer.html.erb, app/views/common/_header.html.erb, app/views/layouts/application.html.erb, app/views/static_pages/accessibility.html.erb, app/views/static_pages/legal_notice.html.erb, app/views/static_pages/privacy_policy.html.erb, config/routes.rb, spec/controllers/static_pages_controller_spec.rb
Dans cette PR, redesign du footer pour respecter le design system de l'état + ajout des pages Mentions légales, Politique de confidentialité et Accessibilité.
Légere modification du header (ajout d'un container) pour suivre la logique utilisée par pas mal de suite et se caler sur le footer, mais si ça ne te plait pas on peut enlever cette modif, je ne sais pas trop si c'est mieux ou pas.
=> feat(front): new footer + legal pages

app/models/applicant.rb, db/migrate/20220103132647_add_birth_name_to_applicant.rb, db/schema.rb, spec/services/upsert_applicant_spec.rb
I let the possibility to store the birth name the same way we do for RDV-Solidarités.
It prevents [this issue](https://sentry.io/organizations/betagouv-f7/issues/2902995549/?project=5958991&query=is%3Aunresolved) from happening.
=> feat(applicant): Store birth name

app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb
We are onboarding organisations that handle a lot of rdvs that are not linked to RDVI, then there is no point in notifying Mattermost in those cases it will just be noisy.
=> feat(webhooks): remove mattermost notif when no applicants

app/controllers/concerns/filter_rdv_solidarites_webhooks_concern.rb, app/controllers/rdv_solidarites_webhooks_controller.rb, app/jobs/rdv_solidarites_webhooks/process_organisation_job.rb, app/models/organisation.rb, app/models/rdv.rb, app/services/upsert_record.rb, spec/controllers/rdv_solidarites_webhooks_controller_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_organisation_job_spec.rb
Cette PR permet d'updater les infos d'une orga sur RDV-I lorsque ceux ci changent sur RDV-S en processant les webhooks correspondants (voir https://github.com/betagouv/rdv-solidarites.fr/pull/1963).
=> feat(webhooks): sync organisations

.rubocop.yml, app/controllers/applicants_controller.rb, app/javascript/react/components/Applicant.jsx, app/javascript/react/models/Applicant.js, app/javascript/react/pages/ApplicantsUpload.jsx, app/jobs/soft_delete_applicant_job.rb, app/models/applicant.rb, app/models/department.rb, db/migrate/20220111152434_add_department_to_applicants.rb, db/migrate/20220111162622_rename_custom_id_to_department_internal_id.rb, db/schema.rb, db/seeds.rb, spec/controllers/applicants_controller_spec.rb, spec/factories/applicant.rb, spec/jobs/soft_delete_applicant_job_spec.rb, spec/models/applicant_spec.rb
In this PR I made changes so that: 
* We now compute the `uid` every time there is a new save. This makes sense because we were not updating the uid when updating the affiliation number or the role.
* I renamed the column `custom_id` to `department_internal_id` to be more precise
* I added a uniqueness constraint on the `department_internal_id` in the scope of a department
* I also know link in DB an applicant and a department. This is in line with the work started by the RDVS team (see [this thread](https://mattermost.incubateur.net/betagouv/pl/ydweh657qf8z3mz5y189j6ktsa)) and is also coherent with our usecase
=> refactor(uids): Rework uid and department internal id logic

app/views/applicants/edit.html.erb, app/views/applicants/new.html.erb, db/schema.rb, spec/controllers/applicants_controller_spec.rb
Dans cette PR, j'ajoute des tests pour les changements apportés par la PR #179.
Je supprime également le `page_name` passé au `applicant_form`, qui n'est plus nécessaire.
=> add tests for departments routes

app/controllers/applicants_controller.rb, app/models/configuration.rb, app/models/department.rb, app/models/organisation.rb, app/views/applicants/index.html.erb, app/views/organisations/index.html.erb, db/migrate/20220120203747_change_configuration_organisation_association.rb, db/schema.rb, spec/factories/configuration.rb, spec/factories/organisation.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb, spec/services/save_applicant_spec.rb
Je change la relation entre les orgas et les configuration pour pouvoir associer plusieurs orgas, ce qui permet de ne pas avoir à créer une config quand un département a plusieurs orgas comme le 64.
J'en profite pour régler qq trucs: 
* Faire en sorte de ne pas avoir de doublons sur la page index d'un territoire (en ajoutant `distinct` à la requête)
* Démarquer un peu plus le choix de "toutes les organisations" (l'UI est pas terrible c'est temporaire)
=> feat(db): Link multiple orgs to configuration

app/controllers/invitations_controller.rb, app/services/invitations/compute_link.rb, db/migrate/20220125154225_add_rdv_solidarites_lieu_id_to_invitation.rb, db/schema.rb, spec/services/invitations/compute_link_spec.rb
I add the possibility to pass a `rdv_solidarites_lieu_id` in the invitation. We store it in the invitations table.
If we pass one, we obviously don't pass the geolocalisation attributes.
For now we never send one through the application.
I also took this opportunity to change the type of the columns `rdv_solidarites_organisation_id` and `rdv_solidarites_user_id` from `integer` to `bigint`.
=> feat(invitations): Add lieu id to invitations

app/views/applicants/_applicants_list.html.erb
Micro-changement d'affichage sur la page index, après retex du 64 : j'ajoute le numéro de téléphone à la place du numéro d'allocataire (sur cette page, le téléphone, avec le mail, permet de voir si un allocataire a un moyen d'être invité ou non ; le numéro d'allocataire ne sert pas trop).
Je passe le nom en premier élément de la colonne car c'est un élément plus différenciant que le prénom si on cherche rapidement des yeux quelqu'un dans la liste.
=> feat(front): add phone on index

app/views/applicants/_applicant_form.html.erb, app/views/applicants/show.html.erb, config/locales/models/applicant.fr.yml, spec/models/applicant_spec.rb
Dans cette PR, j'ajoute l'affichage du nom de naissance et surtout, dans le cas où l'agent consulte un applicant au niveau du département, le nom des organisations auxquelles le bénéficiaire est attaché.
Je modifie également l'ordre de l'affichage des attributs, en partie pour être en accord avec `applicant_form` (inversion nom/prénom).
=> feat(front): add organisations name & birth_name to applicant show

Gemfile, Gemfile.lock, README.md, package.json, yarn.lock
J'ai lancé la commande `yarn upgrade` pour mettre à jour nos packages et j'ai updaté la version de `webpacker`.
A noter que maintenant il faut avoir node 16 pour lancer l'app en local.
=> chore(deps): upgrade js dependencies

app/controllers/applicants_controller.rb, app/services/invitations/save_with_link.rb
Essai de régler le problème de lien invalide en reloadant le record `applicant` lié à l'invitation dans le service `SaveWithLink`.
J'en profite pour nullifier les empty string à l'envoi du formulaire de création d'allocataire.
=> fix(invitations): reload applicant in save with link service

app/helpers/applicants_helper.rb, app/javascript/react/models/Applicant.js, app/javascript/react/pages/ApplicantsUpload.jsx, app/models/configuration.rb, db/migrate/20220204162710_change_invitation_format_in_config.rb, db/schema.rb, db/seeds.rb, spec/factories/configuration.rb
Dans cette PR, je change le type de la colonne `invitation_format` dans la table `configurations` en mettant un array/string à la place d'un enum/integer afin de gérer plus facilement les conditions d'affichages (comme suggéré en commentaire de l'issue #198). Je change également le nom de la colonne en `invitation_formats` car il s'agit désormais d'une array (+ `invitation_format` est parfois utilisé pour le `format` de l'invitation, par exemple dans `invitations_controller`, donc cela permet de mieux différencier).
Cette PR devra être mergée avant la PR concernant la "landing page" des invitations courrier et celle concernant l'ajout de la possibilité d'inviter par courrier sur la page upload.
=> feat(configuration): change column type for invitation format in config

app/controllers/applicants_controller.rb, app/models/applicant.rb
Le fix appliqué dans #217 n'est pas bon car il empêche de nullifier un attribut d'un allocataire quand on le modifie.
Du coup je nullify directement les paramètres qu'on est obligé de nullifier (malheureusement on ne peut pas tous les nullifier, car nullifier les dates telle qu'on les passe - avec 3 valeurs - fait raiser la méthode `assign_attributes` d'ActiveRecord).
=> fix(app): update applicants params

.rubocop.yml, app/services/notifications/notify_applicant.rb, spec/services/notifications/notify_applicant_spec.rb
Un petit fix lié au mail de Guillaume Faure: les notifications n'étaient jamais marquées comme envoyées.
=> fix(notification): fix notify applicant service

app/models/concerns/has_phone_number_concern.rb, app/services/invitations/send_sms.rb, spec/services/invitations/send_sms_spec.rb
Dans cette PR, j'empêche l'envoi des invitations SMS si le numéro de téléphone est un téléphone fixe.
=> feat(invitations): forbid sms invitations for landlines numbers

config/initializers/sentry.rb
Je fixe l'envoi de transactions à Sentry utilisé pour le monitoring des performances à 5% pour réduire la consommation du quota de transactions (https://mattermost.incubateur.net/betagouv/pl/qgeyjnhu6383ub3unoc3ain5hw).
=> fix(monitoring): reduce sentry sample rate

app/helpers/pdf_helper.rb
Dans cette PR, je modifie le path donné à wicked_pdf pour réparer un bug au moment de la génération du courrier d'invitation en production.
=> fix(pdf): change images path for pdf in production

app/models/applicant.rb, config/locales/models/applicant.fr.yml, spec/models/applicant_spec.rb
Dans cette PR, je change le callback de `generate_uid` d'un `before_save` en un `before_validation` pour éviter un raise d'ActiveRecord en cas de doublon d'uid.
J'en profite également pour expliciter dans le yml, à destination des agents, ce à quoi correspond l'uid.
=> fix(new applicant): avoid raise when uid already exists

app/services/upsert_record.rb
I nullify blank values from webhooks to prevent these kind of errors: https://sentry.io/organizations/betagouv-f7/issues/2843211881/?project=5958991&query=is%3Aunresolved
=> fix(webhooks): Nullify blank values in upsert record

app/javascript/stylesheets/_variables.scss, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/components/_banner.scss, app/javascript/stylesheets/components/_image.scss, app/views/static_pages/welcome.html.erb
Dans cette PR, j'ajoute un lien très visible (sous forme de bannière) sur la page d'accueil pour les bénéficiaires qui auraient reçu l'invitation par courrier mais n'auraient pas tapé l'url exacte.
=> feat(front): add homepage link for invitations

app/mailers/application_mailer.rb, app/views/layouts/mailer.html.erb
Lié à #96 .
J'enlève le `reply-to` et je mets les liens des mentions légales vers RDV-I plutôt que RDV-S dans les mails envoyés.
L'adresse de `reply-to` sera donc `contact@rdv-insertion.fr` qui redirige vers mon adresse (c'est d'ailleurs mieux que les mails de réponse des bRSA ne soient pas partagés entre tous les destinataires de `data.insertion@beta.gouv.fr`).
Si ça ne marche toujours pas la dernière qu'on pourrait tenter serait d'enlever ou de réduire les images présentes dans le mail.
=> fix(mailer): try to send email outside of promotions

app/controllers/invitations_controller.rb, app/models/applicant.rb, spec/controllers/invitations_controller_spec.rb
Je fais 2 mini changements sur les invitations: 
* Je mets le nom en premier dans le fichier, car + facile à rechercher dans les téléchargements
* J'enlève les `,` et les `.` en fin d'adresse en plus du `-`
=> fix(invitation): Small adds on postal invitations

app/views/layouts/mailer.html.erb, app/views/mailers/invitation_mailer/first_invitation.html.erb
Dans cette PR j'enlève les images du logo de RDV-I et du département comme dernière tentative de déplacer les mails de l'onglet "promotions" de gmail (#96)
=> refactor(mailer): Remove images from invitation email

app/models/applicant.rb, spec/models/applicant_spec.rb
Je fais en sorte qu'il ne soit pas possible de créer un BRSA si l'`uid` ou le `department_interrnal_id` ne sont pas présents pour identifier le bRSA.
=> feat(applicant): Validate uid or department internal id presence

app/controllers/applicants_controller.rb, app/services/find_or_initialize_applicant.rb, spec/services/find_or_initialize_applicant_spec.rb
2 personnes différentes peuvent potentiellement avoir le même ID interne ou le même numéro CAF si elles sont dans 2 départements différents.
Je prends donc en compte l'ID du département dans le `FindOrInitializeApplicant` service.
=> fix(applicant): Consider department in find or initialize service

app/controllers/applicants_controller.rb
Certains départements comme la Manche ont l'ID interne au département dans leur fichier mais pas le couple numéro allocataire / rôle. 
Dans ces cas-là il faut pas qu'on ait une erreur.
=> fix(app): do not require uids on search

app/javascript/react/lib/handleApplicantCreation.js
J'enlève le warning à la création lorsqu'on on a pas de numéro d'allocataire ou de rôle, puisque de toutes façons on est obligés maintenant d'avoir soit le couple numéro allocataire/rôle soit l'ID interne au département, et dans le cas de la manche on utilise que l'ID interne.
=> refactor(jsapp): Remove warning when no role or affiliation number

app/models/concerns/has_phone_number_concern.rb, app/services/invitations/send_sms.rb, spec/services/invitations/send_sms_spec.rb
Dans cette PR, je modifie le `HasPhoneNumberConcern` afin que les sms soient bien envoyés aux utilisateurs ayant un numéro de portable en outre mer.
=> fix(app): format phone numbers correctly for outre mer

config/routes.rb
Dans cette PR, je corrige l'url de la page de fin de téléprocédure afin de coller à ce qui a été déployée par la CNAF.
=> fix(routes): teleprocedure path

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/cors.rb
J'ajoute ça pour éviter les problèmes de CORS lorsque les assets sont délivrés sur les subdomains de `rdv-insertion.fr`.
=> feat(app): Add rack cors to allow all requests from rdv-insertion domains

app/models/letter_configuration.rb, app/models/organisation.rb, app/services/invitations/generate_letter.rb, app/views/invitations/invitation_letter.html.erb, db/migrate/20220328173945_add_direction_names_to_department.rb, db/migrate/20220328173945_create_letter_configurations.rb, db/schema.rb, spec/factories/letter_configuration.rb, spec/services/invitations/generate_letter_spec.rb
Dans cette PR, je permets la configuration de l'en-tête de courrier en fonction de la dénomination des services dans les départements.
J'ai opté pour un array car le "nombre" de noms de services/de lignes est variable en fonction des départements (3 dans les Ardennes, 2 dans la Drôme, par exemple).
=> feat(invitation letter): add letter configuration table and default signature

app/javascript/stylesheets/pdf.scss, app/views/invitations/invitation_letter.html.erb
Dans cette PR, je résous le bug lié à l'absence de `responsible` lors de la génération d'un courrier, et je réduis certaines marges pour éviter que le courrier parte sur 2 pages dans certains cas.
=> fix(invitation letter): fix signature bug and avoid page break

app/jobs/soft_delete_applicant_job.rb
J'utilise `update_columns` au lieu d'un update lors de la soft deletion pour ne pas lancer les callbacks et éviter ce genre d'erreurs.
=> fix(worker): Use update_columns when soft deleting

app/javascript/react/pages/ApplicantsUpload.jsx
Sur la page d'upload, pour la feature d'enrichissement avec données de contacts, le format demandé était csv/txt, mais il était toujours possible de charger un fichier d'un autre format, ce qui ne fonctionnait pas mais ne renvoyait aucune erreur. Cette PR vise à corriger ce problème pour éviter des incompréhensions côté utilisateur (cas de la Manche).
=> fix(upload): add safety check on contacts file upload

scripts/extract_applicants_to_csv.rb
Le csv généré présente des problèmes d'encodage sur les lettres accentuées. Cette PR tente de corriger ce problème.
=> fix(script): change encoding of csv

app/views/applicants/_rdv_context.html.erb
Dans le cas de Yonne on affiche un bloc vide sur la page show, cette PR évite d'affiche le bloc dans ces cas-là.
=> fix(applicants): Do no show invitation block when no invitations

app/services/invitations/compute_link.rb, spec/services/invitations/compute_link_spec.rb
Cette PR est liée et doit être mergée après [cette PR](https://github.com/betagouv/rdv-solidarites.fr/pull/2354) sur RDV-Solidarités.
On envoie maintenant la catégorie du motif dans le lien d'invitation plutôt que des termes à rechercher dans le nom du motif.
=> feat(invitations): Pass motif category parameter

app/controllers/uploads_controller.rb
Dans cette PR, je corrige un bug qui apparaissait sur la page `upload` au moment de la sélection du contexte au niveau du département.
=> fix(upload): set current configuration on upload when multiple contexts 

app/controllers/concerns/filterable_applicants_concern.rb, app/controllers/invitations_controller.rb, app/helpers/applicants_helper.rb, app/javascript/react/actions/inviteApplicant.js, app/javascript/react/components/Applicant.jsx, app/javascript/react/components/InvitationBlock.jsx, app/javascript/react/lib/handleApplicantInvitation.js, app/models/concerns/invitable_concern.rb, app/models/invitation.rb, app/models/letter_configuration.rb, app/models/organisation.rb, app/models/rdv_context.rb, app/services/invitations/send_sms.rb, app/views/applicants/_applicants_list.html.erb, app/views/applicants/_rdv_context.html.erb, app/views/letters/invitation_for_rsa_accompagnement.html.erb, app/views/letters/invitation_for_rsa_orientation.html.erb, app/views/letters/invitation_for_rsa_orientation_on_phone_platform.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_accompagnement.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_orientation.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_orientation_on_phone_platform.html.erb, config/locales/models/invitation.fr.yml, db/migrate/20220412150442_add_days_to_accept_invitations_to_configuations_and_invitations.rb, db/migrate/20220412151557_remove_motif_from_letter_configurations.rb, db/schema.rb, spec/controllers/applicants_controller_spec.rb, spec/factories/invitation.rb, spec/mailers/invitation_mailer_spec.rb, spec/models/rdv_context_spec.rb, spec/services/invitations/send_sms_spec.rb
Cette PR est liée à #275 .
Dans cette PR j'ajoute une colonne `number_of_days_to_accept_invitation` à la table `invitations` ainsi qu'à la table `configurations`:
* Dans le 1er cas ça sert à afficher ce délai dynamiquement dans les SMS, mails et courriers
* Dans le 2eme cas ça sert à avoir un délai d'intervention nécessaire qui dépend du contexte dans lequel on est sur les vues des allocataires (index et show) 
J'en profite également pour supprimer la colonne `motif` de la table `letter_configurations` qui n'est plus utilisée.
=> feat(invitations): Set number of days to accept invitations as parameter

app/javascript/react/components/InvitationBlock.jsx, app/javascript/stylesheets/pages/_applicants.scss, app/views/applicants/_rdv_context.html.erb, config/locales/models/rdv_context.fr.yml
Dans cette PR, je retravaille légèrement les blocs invitations/rdvs/statuts de la page `show` afin de : 
- ne plus rendre l'affichage du bloc rdvs optionnel
- avoir des blocs qui gardent la même largeur d'un bRSA à un autre, pour appréhender plus facilement les infos
- avoir des blocs lisibles en toutes circonstances (par exemple : la case du statut était jusque là un peu étroite ; les retours à la ligne du bouton "voir sur rdv-s" n'étaient pas optimaux)
- avoir un design responsive jusqu'à l'ipad (en-dessous, ça devient difficile, mais ça ne sera sans doute pas consulté sur mobile ; cela permet au moins une bonne consultation quand le navigateur n'est pas en fullscreen)
=> fix(front): more coherent show page

app/javascript/react/actions/getInvitationLetter.js
Permet de régler [cette erreur](https://sentry.incubateur.net/organizations/betagouv/issues/187/?project=16&query=is%3Aunresolved) sur sentry qui fait que les courriers ne peuvent pas être générés.
Je pense qu'on pourrait à l'avenir regrouper les méthodes `handleApplicantInvitation`,  `inviteApplicant` et `getInvitationLetter` au même endroit pour éviter ce genre d'erreur.
=> fix(invitations): Fix postal invitations

Gemfile, Gemfile.lock, app/controllers/api/v1/applicants_controller.rb, app/controllers/concerns/api/v1/params_validation_concern.rb, app/controllers/invitations_controller.rb, app/jobs/create_and_invite_applicant_job.rb, app/jobs/invite_applicant_job.rb, app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/jobs/send_rdv_webhook_job.rb, app/models/applicant.rb, app/models/invitation.rb, app/models/organisation.rb, app/models/rdv_solidarites/rdv.rb, app/models/webhook_endpoint.rb, app/services/migrations/retrieve_and_save_organisation_rdvs.rb, db/migrate/20220425164025_create_webhook_endpoints.rb, db/schema.rb, spec/factories/webhook_endpoint.rb, spec/jobs/create_and_invite_applicant_job_spec.rb, spec/jobs/invite_applicant_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb, spec/jobs/send_rdv_webhook_job_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/applicants_request_spec.rb
Cette PR rajoute le mécanisme de webhook sortant de RDVI (voir  #319), mais également des changements sur l'API pour prendre en compte les changements relatifs aux contextes.
Désolé j'ai pas eu le temps de séparer en 2 PRs, on a besoin des 2 pour la démo avec Marseille demain 😬 . Par contre les 2 commits de cette PR sont bien scopés.
Pour les webhooks j'ajoute une table `webhook_endpoints` comme sur RDV-S, et j'ajoute un job `SendRdvWebhookJob` qui sera appelé à la fin du traitement du webhook reçu depuis RDV-S. De cette façon RDVI jouera vraiment un rôle de "proxy" entre RDV-S et le département en ce qui concerne les webhooks.
=> feat(webhook): Add outgoing webhook mechanism

app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/jobs/send_rdv_solidarites_webhook_job.rb, app/models/rdv_solidarites/rdv.rb, app/models/rdv_solidarites/user.rb, app/services/migrations/retrieve_and_save_organisation_rdvs.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb, spec/jobs/send_rdv_solidarites_webhook_job_spec.rb
Je change le webhook qu'on envoie à la sortie de RDV-Insertion. On reprend exactement le webhook de RDV-S auquel on ne rajoute que le `department_internal_id` et le `title` pour les `users` liés au RDV.
=> refactor(webhooks): Change outgoing webhook payload

app/controllers/applicants_controller.rb, app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, spec/controllers/applicants_controller_spec.rb, spec/factories/applicant.rb
Cette PR comprend 2 mini changements: 
* Je fais en sorte que la méthode `set_applicants_and_rdv_contexts` soit un peu moins lourd dans l'`ApplicantsController`
* Je donne le nom de l'orga au lieu de l'ID dans les notifs mattermost lorsqu'il n'y a pas de catégories
=> refactor(app): Small changes

.buildpacks
Webpack étant déprécié sur Rails 7, il faut ajouter les buildpacks Node.js et Ruby pour continuer à l'utiliser avec Scalingo.
Je le mets en attendant de migrer webpack à terme (voir #365 )
=> chore(ops): Add builpacks to support webpack

app/controllers/applicants_controller.rb, app/helpers/applicants_helper.rb, app/models/applicant.rb, app/views/applicants/_applicants_list.html.erb, app/views/applicants/_search_form.html.erb, app/views/applicants/index.html.erb, spec/controllers/applicants_controller_spec.rb
Cette PR est liée à #360 .
Lorsqu'on est dans l'onglet des "Autres" (anciennement "Non invités"), on récupère maintenant non seulement les allocataires qui n'ont pas du tout de `rdv_contexts` associés mais **aussi** les allocataires qui ont des `rdv_contexts` associés dans des autres contextes que ceux pour lesquels l'organisation en question peut inviter.
C'est notamment important lorsque l'on va avoir #344  et qu'un allocataire passera d'une org à une autre liée à des contextes différents.
=> feat(applicants): Lists all applicants with no rdv contexts

app/javascript/react/pages/ApplicantsUpload.jsx
Dans cette PR, j'ajoute les fichiers `.ods` et `.csv` aux fichiers autorisés pour l'upload des bénéficiaires. Pour éviter que d'autres fichiers soient soumis [(L'attribut `accept` ne valide pas les types de fichiers sélectionnés ; il fournit des indications aux navigateurs pour guider les utilisateurs vers la sélection des bons types de fichiers)](https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/accept), j'ajoute également une validation dans le code, déjà utilisée pour le fichier de contacts
=> feat(upload): add ods and csv support + hard check file on upload

app/jobs/send_rdv_solidarites_webhook_job.rb, spec/jobs/send_rdv_solidarites_webhook_job_spec.rb
Je passe l'expiration dans le header du JWT au lieu du payload.
=> refactor(webhooks): Change JWT headers

app/controllers/static_pages_controller.rb, app/models/stat.rb, app/views/static_pages/welcome.html.erb
On ne loade plus les stats sur la page d'accueil (sinon le chargement de la page est trop long) en attendant #358
=> refactor(app): Hide stats from homepage

app/services/save_applicant.rb
Cette PR fix #390. Elle évite l'update de l'email d'un conjoint sur rdv-s dans tous les cas, pour éviter les doublons de mail.
=> fix(app): Dont update conjoint mail on rdvs

app/models/applicant.rb, app/views/applicants/show.html.erb
Lorsque l'on clique sur le bouton "Retour", on veut que cela nous ramène vers une liste liée au contexte auquel est rattaché l'allocataire.
=> fix(view): Redirect to right context when back to list

app/jobs/notify_applicant_job.rb, app/jobs/rdv_solidarites_webhooks/process_organisation_job.rb, app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/jobs/rdv_solidarites_webhooks/process_user_job.rb, app/models/concerns/has_status_concern.rb, app/services/migrations/retrieve_and_save_organisation_rdvs.rb, app/services/upsert_record.rb, db/migrate/20220530135315_add_webhook_time_stamp.rb, db/schema.rb, spec/jobs/rdv_solidarites_webhooks/process_organisation_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_user_job_spec.rb, spec/services/upsert_record_spec.rb
Dans cette PR je fais en sorte que: 
* L'on prenne en compte l'heure de la réception du webhook qui entraine l'update d'un record en base. On store cet attribut dans les tables `organisations`, `applicants` et `rdvs`. Ainsi on est sûr qu'on updatera pas un record à partir d'un webhook antérieur à celui qui a entrainé le dernier update
* Je lock au moment de l'upsert pour que l'on est pas deux upsert en même qui nous donne les erreurs `ActiveRecord::RecordInvalid` ou `ActiveRecord::RecordNotUnique` (voir sentry)
=> fix(jobs): Maintain fifo when upserting records

app/models/invitation.rb
Je me suis rendu compte qu'on ne récupérait pas le premier record d'`invitation_parameters` **présent** mais seulement le record lié à la première orga. 
Cette PR corrige ça.
=> fix(invitations): Retrieve invitation parameters from invitations

app/models/concerns/invitable_concern.rb
Lié à cette erreur sur sentry: https://sentry.incubateur.net/organizations/betagouv/issues/2333/?query=is%3Aunresolved
Il faut prendre en compte les invitations ou `sent_at` est présent
=> fix(view): Fix error when retrieving last invitation sent at

app/javascript/react/models/Applicant.js
Pour permettre au 93 d'upload ses bRSA sans intervention manuelle sur le numéro CAF à chaque fois, nous autorisions les numéros d'affiliation dont la longueur est égale à 13 caractères (cas du 93, qui rajoute des 0).
=> feat(upload): remove 13 characters limit for NIR

app/models/applicant.rb, app/services/save_applicant.rb, app/services/upsert_rdv_solidarites_user.rb, spec/services/save_applicant_spec.rb, spec/services/upsert_rdv_solidarites_user_spec.rb
On n'envoie pas les attributs vide lorsque l'on met à jour l'utilisateur sur RDV-S. Ça permet de ne pas écraser ces attributs si ceux-ci sont présents dans RDV-S.
Du coup, si on veut nullifier un attribut commun à RDVI et RDVS, il faut le faire depuis RDVS (et le webhook le nullifiera sur RDVI).
=> refactor(applicant): Do not send empty attributes to RDV-S

db/migrate/20220613120827_add_valid_until_to_invitations.rb
Pour la migration en prod, on ne change le nombre de jours avant intervention nécessaire que s'il est inférieur à 3.
=> fix(migration): update number_of_days_before_action_required migration

.eslintrc.json, app/controllers/organisations_controller.rb, app/javascript/components/choose-organisation-modal.js, app/javascript/lib/retrieveRelevantOrganisation.js, app/javascript/react/actions/searchOrganisations.js, app/javascript/react/components/Applicant.jsx, app/javascript/react/models/Applicant.js, app/javascript/react/pages/ApplicantsUpload.jsx, app/models/organisation.rb, app/models/responsible.rb, config/routes.rb, db/migrate/20220629133900_add_slug_to_organisations.rb, db/migrate/20220629134039_remove_responsibles.rb, db/schema.rb, db/seeds.rb, spec/controllers/organisations_controller_spec.rb, spec/factories/responsible.rb
Dans cette PR je fais en sorte que les départements puissent affecter l'allocataire dans une organisation en ajoutant une colonne spécifique dans leur fichier Excel.
Cette colonne peut contenir soit le nom, soit un `slug` (nouvel attribut ajouté aux organisations) pour retrouver l'organisation en question.
Pour l'affectation, le principe est à peu près le même que lors de l'affectation: 
* Si un terme est présent dans la colonne, on appelle un endpoint nouvellement créé `organisations#search`
* Si une seule organisation est retrouvée, on crée l'allocataire dans cette organisation
* Si plusieurs organisations sont retrouvées, on affiche une modale pour que l'agent choisisse la bonne organisation 
* Si aucune organisation n'est trouvée, on affiche une modale pour que l'agent choisisse entre …
=> feat(app): Assign organisation by search term

app/javascript/controllers/invitations_checkbox_form_controller.js, app/models/concerns/has_rdvs_concern.rb, app/views/invitations/_checkbox_form.html.erb
* Je ne permets pas d'inviter depuis la page index quand l'allocataire a déjà rdvs (dans ce cas là il vaut mieux aller voir dans la page show la situation de l'allocataire)
* J'ajoute un tooltip pour dire que cocher les cases génèrent des invitations
=> fix(invitations): disable invite when rdvs present

app/controllers/applicants_controller.rb
Il faut toujours set une configuration sur la page index même quand une catégorie de motif n'est pas passée dans l'URL au risque d'avoir une erreur 500: https://mattermost.incubateur.net/betagouv/pl/aciy4zg7h7nxfjkpancihcw4jo
=> fix(app): Always Set a current configuration on index page

app/models/concerns/has_status_concern.rb
La méthode `last_rdv` du `HasStatusConcern` entrait en conflit avec la méthode `last_rdv` du `has_rdvs_concern`.
Je la renomme donc `last_created_rdv`.
=> fix(rdvs): Rename last rdv method in status concern

app/controllers/invitations_controller.rb, app/models/invitation.rb, app/services/invitations/assign_attributes.rb, app/services/invitations/save_and_send.rb, spec/models/invitation_spec.rb, spec/services/invitations/assign_attributes_spec.rb, spec/services/invitations/save_and_send_spec.rb
Lorsque l'on crée une invitation postal on ne mettait pas de durée d'expiration ce qui crée plusieurs problèmes: 
- Si la personne n'est invité que par courrier, le token n'expire jamais ce qui peut poser problème, surtout maintenant que l'on va procéder aux convocations
- Si un invitation est invitée par mail et/ou sms après ça, le token expire quand même alors que l'expiration n'est pas marquée au niveau de l'invitation
On s'est dit avec Rémi qu'il valait mieux mettre la même expiration sur les courriers. On pourra revoir cette logique si un département le demande explicitement.
=> fix(invitations): Always set an expiration on invitations

app/controllers/stats_controller.rb, app/helpers/stats_helper.rb, app/models/department.rb, db/migrate/20220907144848_add_display_stats_to_departments.rb, db/schema.rb
Dans cette PR, afin de répondre à l'issue #499, j'ajoute une colonne `display_in_stats` au modèle `department` afin de pouvoir choisir, sans intervenir dans le code, d'afficher ou non certains départements sur la page `/stats`.
Par défaut, la valeur de `display_in_stats` est fixée à `true` (c'est donc un opt-out, en quelque sorte).
=> fix(stats): add option to hide departments in stats

app/jobs/invite_applicant_job.rb, config/environments/development.rb, spec/jobs/invite_applicant_job_spec.rb
La logique d'invitation n'a pas été mise à jour au niveau du `InviteApplicantJob`, ce qui a donné lieu à une erreur ce matin: https://sentry.incubateur.net/organizations/betagouv/issues/7238/?project=16&query=is%3Aunresolved
Je règle ça en ajoutant un test pour vérifier que la durée de validité est toujours bien assignée.
=> fix(job): Update new invitation logic for api

app/models/concerns/has_motif_category_concern.rb
Dans cette PR, je fais en sorte que 2 nouvelles catégories de motifs puissent être prises en compte côté RDV-I (issue #542) : 
- un contexte 'signature CER'
- un contexte 'offre accompagnement pro'
Une autre PR est à merger côté RDV-S pour que l'issue soit résolue dans sa totalité.
A priori c'est la seule chose à faire côté RDV-I mais je suis passé un peu vite dessus, je n'ai pas pu tester fonctionnellement.
=> feat(motifs): add new motif categories

app/services/stats/compute_stats.rb
J'évite une N+1 query lorsque l'on calcule les stats (ce qui permet au job qui le lance de consommer moins de CPU)
=> feat(stats): Optimize stat computation

app/models/concerns/has_status_concern.rb, spec/models/rdv_context_spec.rb
Lorsqu'un rdv est en attente il faut toujours que le statut soit en "RDV pris", quelque soit le cas de figure, notamment si des rdvs ont été pris après par inadvertance puis annulé (voir [ici](https://mattermost.incubateur.net/betagouv/pl/rftrh9uz17n4ig5f6584oaua5a)).
J'ai fait donc le correctif en ce sens, et j'ai rajouté/cleané des specs sur la logique de statut pour prendre en compte tous les cas de figure.
=> fix(app): Improve the rdv_context status logic

app/jobs/rdv_solidarites_webhooks/process_motif_job.rb, app/models/motif.rb, spec/jobs/rdv_solidarites_webhooks/process_motif_job_spec.rb
Dans cette PR j'enlève la condition sur la catégorie pour qu'un motif puisse être importé.
En effet, imaginons qu'une catégorie soit mise puis retirée sur un motif. Elle serait alors présente dans notre BDD sans catégorie assignée, on ne peut donc pas forcer la mise d'une catégorie.
De plus si on importe pas tous les motifs, certains RDV ne pourront pas être liés à des motifs en BDD (ceux qui ont été pris avant la notion de catégorie).
Autant donc importer tous les motifs, l'idée étant de toutes façons ici d'avoir du cache de RDV-S et de ne pas y associer trop de logique.
=> feat(db): Import all motifs

app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/models/motif.rb, app/models/rdv.rb, app/models/rdv_solidarites/rdv.rb, app/views/applicants/_rdv_context.html.erb, db/migrate/20220926133354_add_motif_to_rdvs.rb, db/schema.rb, spec/controllers/applicants_controller_spec.rb, spec/factories/motif.rb, spec/factories/rdv.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb
Cette PR vient après #563 .
Dans cette PR je fais la migration pour lier les RDVs aux motifs correspondants en base.
Je fais aussi en sorte d'ajouter ce lien lorsque l'on process les webhooks liés aux rdvs.
J'affiche également le nom du motif dans la vue du demandeur:
=> feat(db): Link rdvs to motifs

app/models/motif.rb, app/services/concerns/invitations/sms_content.rb, app/views/letters/invitation_for_rsa_follow_up.html.erb, app/views/letters/invitation_for_rsa_insertion_offer.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_accompagnement_reminder.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_cer_signature_reminder.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_follow_up.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_follow_up_reminder.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_insertion_offer.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_insertion_offer_reminder.html.erb, app/views/mailers/invitation_mailer/invitation_for_rsa_orientation_on_phone_platform_reminder.html.erb, spec/mailers/previews/invitation_preview.rb, spec/services/invitations/send_sms_spec.rb
Dans cette PR, j'ajoute le motif `rsa_follow_up` pour les rendez-vous de suivi, et je rajoute les textes pour les invitations relatives à ce motif et au motif `insertion_offer`. Je modifie également quelques détails d'autres textes pour garder plus de cohérence sur la rédaction (l'utilisation de RDV/rendez-vous, notamment).
=> feat(invitations) add follow up motif and texts for follow up & insertion offer invitations

app/models/concerns/invitable_concern.rb
Sur la page index les checkbox étaient checkées lorsqu'une invitation existait pour le format en question mais ne vérifiait pas si l'invitation a été envoyée (via la méthode `invited_through?`). 
Ce qui pouvait donner lieu à des incohérences comme ceci: 
Cette PR règle ce problème et ajoute une méthode `sent_invitations` dans le `InvitableConcern`.
=> fix(view): Mark as invited on index page only when invitations are sent

app/services/exports/generate_applicants_csv.rb, spec/services/exports/generate_applicants_csv_spec.rb
Dans cette PR, je corrige les bugs listés dans l'issue #550 : 
- le champ rdv honoré en - de jours n'est pas bon, il vérifie juste si un rdv a été honoré
- le cas où une structure n'est pas passé ne marche pas
- le cas où une catégorie de motif n'est pas passé les infos sont incohérentes
=> fix(exports): allow csv exports when no structure or motif category are passed

app/jobs/send_invitation_reminders_job.rb, spec/jobs/send_invitation_reminders_job_spec.rb
closes issue #561 
Dans cette PR, je fais en sorte que les relances SMS ne soient pas envoyées si le numéro de téléphone du bRSA n'est pas un mobile.
=> fix(invitations): do not send sms reminders if phone is not mobile

app/mailers/invitation_mailer.rb, app/mailers/notification_mailer.rb, app/models/logo.rb
J'avais oublié qu'on ne pouvait pas envoyer de svg pour les mails, du coup j'ai fait un fix pour n'envoyer que du png ou du jpg dans ces cas.
À noter que seuls la Drôme et l'Aude ont des logos à ces formats.
=> fix(mailers): Prevent svg for mails

app/models/notification.rb, app/services/notifications/notify_applicant.rb, spec/services/notifications/notify_applicant_spec.rb
Lié à cette erreur sur Sentry lors de la dernière demo: https://sentry.incubateur.net/organizations/betagouv/issues/10758/?project=16&query=is%3Aunresolved
On veut pouvoir garder une notification en db si le rdv est supprimé sans que ça raise une erreur au moment d'essayer d'accéder à des notifications pour une catégorie.
Du coup je réassigne le `rdv_solidarites_rdv_id` à la notification pour retrouver le rdv dans ces cas-là.
=> refactor(notification): Allow notifications without rdv

app/mailers/invitation_mailer.rb, app/views/mailers/invitation_mailer/invitation_for_rsa_orientation_on_phone_platform_reminder.html.erb, spec/mailers/invitation_mailer_spec.rb
Dans cette PR, j'ajoute les méthodes manquantes pour les rendez-vous de suivi dans le `invitation_mailer`. J'en profite également pour rajouter les tests manquants pour une bonne partie des méthodes de ce mailer, et pour corriger un téléphone non formatté dans une des invitations par mail.
=> fix(mails): add follow up mailer methods + missing tests

app/controllers/invitations_controller.rb, app/jobs/create_and_invite_applicant_job.rb, app/jobs/invalidate_invitation_job.rb, app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/jobs/send_invitation_reminder_job.rb, app/models/invitation.rb, app/services/invitations/assign_attributes.rb, app/services/invitations/compute_link.rb, app/services/invitations/save_and_send.rb, app/services/rdv_solidarites_api/retrieve_invitation.rb, config/locales/models/invitation.fr.yml, db/migrate/20221013134556_rename_token_to_rdv_solidarites_token.rb, db/schema.rb, scripts/create_applicants_and_rdvs.rb, spec/controllers/invitations_controller_spec.rb, spec/factories/invitation.rb, spec/jobs/create_and_invite_applicant_job_spec.rb, spec/jobs/invalidate_invitation_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb, spec/jobs/send_invitation_reminder_job_spec.rb, spec/models/invitation_spec.rb, spec/services/invitations/assign_attributes_spec.rb, spec/services/invitations/compute_link_spec.rb, spec/services/invitations/save_and_send_spec.rb, spec/services/invitations/send_sms_spec.rb
Cette PR est liée à #539 .
Dans cette PR on fait en sorte que:
* On ne supporte + que l'uuid pour retrouver l'invitation et plus le token dans `Invitations#redirect`
* On met une date d'expiration à toutes les invitations en base
* On met à jour `expired?`
* On renomme la colonne `token` en `rdv_solidarites_token`
J'en profite aussi pour vérifier que le numéro est mobile quand on enqueue un job d'invitation depuis par API.
=> feat(invitations): Remove old invitation logic

app/controllers/applicants_controller.rb, app/models/agent.rb, app/models/configuration.rb, app/policies/rdv_context_policy.rb, app/views/applicants/_applicants_list_tabs.html.erb, app/views/applicants/show.html.erb, spec/controllers/applicants_controller_spec.rb
Cette PR corrige le bug décrit dans l'issue #546 : En tant qu'agent, je ne dois voir que les contextes pour lesquels un motif existe sur mon organisation. En plus de corriger ce bug dans la liste des contextes qui apparaissent sur la page show d'un bénéficiaire, elle corrige également un bug "similaire" dans les onglets de la page index.
=> fix(bug): see only the relevant contexts

app/controllers/stats_controller.rb, app/services/stats/compute_stats.rb, spec/services/stats/compute_stats_spec.rb
Dans cette PR, je permets l'affichage complète des stats pour les organisations qui utilisent la nouvelle fonction de convocation des bRSA tout en invitant tout de même les bénéficiaires en première intention. Concrètement, un département comme le Vaucluse ou la Drôme auront toutes leurs stats affichées, mais ce ne sera pas le cas pour l'Yonne.
N.B. pour @aminedhobb : dans `stats_controller`, `@display_all_stats` est set to `false` dès lors qu'une organisation du département n'invite pas.
`@display_all_stats = @department.configurations.none? { |configuration| configuration.invitation_formats.blank? }`
On pourrait peut-être s'interroger sur la possibilité de l'ajouter dès lors qu'une organisation du département invite, pour être moins limitant, je te laisse trancher (ce qui donnerait ça: …
=> feat(stats): display convene applicant organisations in stats

app/services/concerns/invitations/sms_content.rb, app/views/mailers/invitation_mailer/regular_invitation.html.erb, spec/mailers/invitation_mailer_spec.rb, spec/services/invitations/send_sms_spec.rb
J'enlève finalement le `rdv_purpose` du SMS d'invitation pour ne pas trop le rallonger. Il est présent dans le sms de rappel.
=> feat(invitations): Remove rdv purpose from sms

app/jobs/rdv_solidarites_webhooks/process_user_job.rb, app/models/rdv_solidarites/user.rb, app/services/upsert_record.rb, spec/jobs/rdv_solidarites_webhooks/process_user_job_spec.rb
Cette PR est liée à #619 .
J'enlève le fait de compacter automatiquement ce qu'on récupère des webhooks, et je gère le cas particulier des numéros d'allocataires nullifiés.
=> refactor(webhook): Do not compact rdv-s attribute

app/models/motif.rb, app/models/rdv_solidarites/motif.rb, app/services/invitations/validate.rb, db/migrate/20221205153103_add_follow_up_to_motifs.rb, db/schema.rb, spec/services/invitations/validate_spec.rb
Dans cette PR j'ajoute l'attribut `follow_up` aux motifs comme sur RDV-S et je vérifie au moment de l'invitation qu'un motif de suivi est définie pour la catégorie invitée.
=> feat(motifs): Add follow up logic

db/seeds.rb, docs/INSTALL.md
J'ai effectué quelques changements dans le seed suite à des modifs coté rdv-s (les id des organisations ont changés)
L'idée est d'avoir quelquechose de fonctionnel immédiatement après le make install coté rdv-s et rdv-i sans avoir à renvoyer manuellement les webhook ou éditer les motifs coté rdv-s pour qu'ils se créent dans rdv insertion. (idem pour l'agent)
=> Changement dans le seed aprés modifs coté rdv-s

app/services/applicants/save.rb, spec/services/applicants/save_spec.rb
Suite au problème de doublon de la Manche #712  (qui était causé par l'absence de la colonne rôle). Les utilisateurs nous ont remonté un nouveau problème.
Il y a un bug lors du chargement d'un fichier d'allocataire sans colonne rôle.
Dans ce cas le service ne renvoi pas l'email à rdv-solidarites considérant l'absence de rôle comme un rôle conjoint.
Le retour du webhook created de l'usager dans rdv-solidarites efface l'email de l'applicant en DB côté rdv-insertion.
J'ai ajouté la bonne condition et un test.
Pour info, on a plus de 4000 allocataires sans rôles en DB de prod. C'est étonnant que ce bug n'est pas été remonté avant.
=> Fix(import) Bug d'import quand il n'y a pas de colonne role

db/migrate/20230117094244_add_external_to_organisations.rb, db/migrate/20230117094244_add_independent_from_cd_to_organisations.rb, db/schema.rb
close issue #741 
permet la réalisation de #751 
- ajout d'une nouvelle colonne `external` sur la table `organisations`, sous forme de booléen, afin de déterminer si une organisation est externe au département ou non. Par défault, la valeur est fixée à `false`
=> feat(invitations): add variable for external organisations

Gemfile.lock, app/javascript/stylesheets/pdf.scss, app/models/concerns/sendable.rb, app/services/invitations/generate_letter.rb, app/views/letters/_footer.html.erb, app/views/letters/_header.html.erb, app/views/letters/invitation_for_rsa_insertion_offer.html.erb, app/views/letters/invitation_for_rsa_orientation_on_phone_platform.html.erb, app/views/letters/regular_invitation.html.erb, db/migrate/20230117114011_add_display_department_logo_to_messages_configurations.rb, db/schema.rb, spec/services/invitations/generate_letter_spec.rb
close issue #752 
Dans cette PR, je change les règles d'affichage des logos dans le footer des lettres : 
- ajout d'une colonne `display_department_logo` sur la table `messages_configuration` ; valeur par défaut `true`
- le logo du département est affiché dans tous les cas si le logo de l'organisation n'est pas en base
- le logo de l'organisation est affiché dans tous les cas s'il est en base
- simplification du html + ajout de commentaires pour rendre le css plus lisible
=> feat(invitations): change logos display for letters

app/services/stats/compute_stats.rb
Pour répondre au problème soulevé dans l'issue #710, je commence par une toute petite tentative d'amélioration : je remplace `except`  par une requête ActiveRecord, ce qui devrait déjà soulager (un petit peu) les performances.
=> fix(stats): Small fix

app/models/concerns/rdv_context_status.rb, spec/models/rdv_context_spec.rb
Suite au changement sur la façon de mettre à jour le statut dans #774 , je n'ai pas pris en compte les cas où un rdv était créé dans le passé puis honoré.
Cette PR remédie à cela.
=> fix(status): set rdv_seen status when last created participation is seen

app/clients/rdv_solidarites_client.rb, app/controllers/applicants_controller.rb, app/controllers/applicants_organisations_controller.rb, app/jobs/rdv_solidarites_webhooks/process_agent_role_job.rb, app/jobs/rdv_solidarites_webhooks/process_user_profile_job.rb, app/jobs/soft_delete_applicant_job.rb, app/models/applicant.rb, app/policies/organisation_assignation_policy.rb, app/services/applicants/remove_from_organisation.rb, app/services/rdv_solidarites_api/delete_user_profile.rb, app/views/applicants/_add_to_org_button.html.erb, app/views/applicants/show.html.erb, app/views/applicants_organisations/_applicants_organisation.html.erb, app/views/applicants_organisations/create.turbo_stream.erb, app/views/applicants_organisations/destroy.turbo_stream.erb, app/views/applicants_organisations/index.html.erb, config/routes.rb, spec/controllers/applicants_controller_spec.rb, spec/controllers/applicants_organisations_controller_spec.rb, spec/features/agent_can_add_or_remove_applicant_from_organisations_spec.rb, spec/features/agent_can_invite_applicants_from_index_page_spec.rb, spec/services/applicants/remove_from_organisation_spec.rb, spec/services/applicants/remove_referent_spec.rb, spec/support/authentication_spec_helper.rb
Dans cette PR je permets à un agent d'ajouter et de retirer le bénéficiaire des différentes organisations du département. 
Pour ça j'ajoute une action pour pouvoir retirer une organisation au bénéficiaire (lié à cette PR côté RDV-Solidarités: https://github.com/betagouv/rdv-solidarites.fr/pull/3289).
Bien sûr, un agent ne peut retirer un bénéficiaire d'une organisation que s'il appartient à cette organisation. 
Si le bénéficiaire n'appartient qu'à une seule organisation et qu'on le retire, ça a pour effet de supprimer le bénéficiaire (même comportement que sur RDV-Solidarités). On affiche un message de confirmation dans ces cas-là.
J'ai également ajouté des tests d'intégration sur cette partie là.
=> feat(app): Enable agent to add and remove applicants from orgs

app/jobs/rdv_solidarites_webhooks/process_agent_role_job.rb, app/jobs/rdv_solidarites_webhooks/process_organisation_job.rb, spec/jobs/rdv_solidarites_webhooks/process_agent_role_job_spec.rb
Dans cette PR je fais un fix pour que l'orga se synchronise avec RDV-Solidarités lorsqu'on appelle la méthode `WebhookEndpoint#trigger_for_all_resources`.
Je fais également en sorte d'upserter l'agent avant de raiser lorsque l'on process un webhook d'`AgentRole` et que l'agent n'est pas sur RDV-I.
=> fix(webhook): Synchronize when receiving webhooks for all ressources

app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/views/applicants/_applicants_list_header.html.erb
On avait une erreur si un webhook comprenait une catégorie de motif mais que l'organisation en question n'avait pas de configurations associée à cette catégorie : https://sentry.incubateur.net/organizations/betagouv/issues/21493/?project=16
Je corrige également une erreur que l'on avait lorsqu'on effectuait une recherche sur les bénéficaires archivés: https://sentry.incubateur.net/organizations/betagouv/issues/12768/?project=16&referrer=regression-activity-email
=> fix(webhooks): Do not process unhandled category webhook

app/jobs/send_invitation_reminder_job.rb, app/jobs/send_invitation_reminders_job.rb, spec/jobs/send_invitation_reminder_job_spec.rb, spec/jobs/send_invitation_reminders_job_spec.rb
Dans cette PR je change la façon de lancer les rappels, suite aux nombreuses erreurs lors du lancement de ces derniers jours : https://sentry.incubateur.net/organizations/betagouv/issues/20419/?project=16&query=&statsPeriod=14d
En effet dans certains cas l'allocataire a pu avoir reçu une invitation il y a 3 jours sur un contexte mais a eu un rdv sur un autre entre temps, et donc l'expression `applicant.first_invitation_relative_to_last_participation_sent_at` pouvait renvoyer `nil`.
Remarque: On risque d'avoir quelques retours au cas où ces rdvs dans différents contextes ne sont pas voulus, auquel cas on devra en parler aux départements concernés et voir comment on peut éviter ça.
=> fix(cron): Send invitation reminders through rdv contexts

spec/mailers/previews/notification_preview.rb
J'ai oublié de mettre à jour le scope pour récupérer les catégories où la présence n'est pas optionnelle dans la preview des mails de notifications danss  #815
=> fix(preview): Use new scope in notification mailer preview

app/controllers/applicants_controller.rb, app/controllers/invitations_controller.rb, app/controllers/uploads_controller.rb, app/models/configuration.rb, app/models/file_configuration.rb, db/migrate/20230207094221_create_file_configurations.rb, db/schema.rb, spec/factories/configuration.rb, spec/factories/file_configuration.rb
Cette PR vient après #815 .
Dans cette PR j'extrais les colonnes `sheet_name`  et `column_names` de la table `configurations` dans une table séparée `file_configurations`. 
J'en profite pour optimiser certaines queries en preloadant les records nécessaires.
Remarque: 
* la table configuration devra probablement être renommé (`CategoryConfiguration` ?) dans une autre PR
=> refactor(app): Separate file configurations and configurations in separate tables

app/models/concerns/rdv_context_status.rb, app/models/participation.rb
On a plusieurs instances de `rdv_context` qui ne se sont pas mis à jour ces derniers jours. 
Je tente ici de rafraichir le statut à chaque modification de participation, voir déjà si ça change quelque chose.
=> fix(status): Refresh rdv_context status on participations create/update

config/schedule.yml
Temporairement en attendant d'avoir optimisé le service (ou définitivement si on pense que ce n'est pas nécessaire de le faire quotidiennement), je baisse la fréquence du calcul des stats globals à une fois par semaine, le week-end, pour éviter d'encombrer les workers.
=> fix(stats): change global stats computing frequency

app/controllers/invitations_controller.rb, db/migrate/20230213152346_rename_invitation_fallbacks_set_to_applicants_organisation_to_invite_to_applicant_organisations_only.rb, db/schema.rb, spec/controllers/invitations_controller_spec.rb
Dans cette PR je renomme la colonne `invitation_fallbacks_set_to_applicants_organisations` de la table `configurations` en 
`invite_to_applicant_organisations_only` qui est plus parlante.
Je mettrai à jour le wiki une fois la PR mergée.
=> refactor(invitation): Rename configuration attribute 

app/views/applicants/_applicants_table_for_motif_category.html.erb, spec/features/agent_can_invite_applicants_from_index_page_spec.rb
Dans cette PR je fais une proposition de changement d'affichage des invitations sur la page index lorsqu'un "RDV est pris".
Aujourd'hui, on affiche les checkbox d'invitations qui sont décochées et incochables: 
C'est censé vouloir dire qu'il est impossible d'inviter la personne car il y a un RDV en attente, mais qu'il sera possible de le faire dès que le RDV sera passé (et son statut déterminé).
Cependant, vu que cette affichage arrive juste après la période "d'invitation en attente de réponse", on pourrait penser que l'affichage ci-dessus veuille dire que le RDV a été pris sans que la personne ait été invitée. 
Nous avions eu un retour du Var nous faisant part de leur étonnement sur cette interface.
Je propose donc de changer pour juste enlever les checkbox lorsqu'un RDV est pris et est …
=> feat(view): Hide invites when rdv pending on index

db/migrate/20230216152810_add_last_webhook_update_received_at_for_agent_roles.rb, db/schema.rb
Pour résoudre [cette erreur Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/22612/), j'ajoute une colonne `last_webhook_update_received_at` à la table `agent_roles`
=> fix(agent_roles): add last webhook update received at to agent_roles

app/controllers/applicants_controller.rb, app/controllers/application_controller.rb, app/controllers/concerns/applicants/filters.rb, app/controllers/concerns/before_action_override.rb
Cette PR a pour but de regrouper les `before_action` du `ApplicantsController` par action.
En effet, il devenait de plus en plus difficile d'avoir en tête quelle filtre ajouter pour quelle action, sans compter le fait que ces filtres peuvent être appelés dans un ordre différent selon l'action.
Cependant, la méthode `before_action` ne permet pas de scoper les filtres par action. Si on appelle un filtre sur une action et qu'on met une condition (à l'aide des options `only`, `if`, `except`, `unless`), alors ce filtre ne pourra pas être appelé pour une autre action.
Une méthode simple consisterait à appeler une définir un nouveau filtre pour chaque action et appeler passer ce filtre à `before_action`.
Par exemple on peut avoir: 
```ruby 
before_action :prepare_index, only: :index
...
def …
```
=> refactor(controllers): Group before_action filters by action 

app/controllers/concerns/applicants/convocable.rb, app/helpers/applicants_helper.rb, app/models/motif.rb, spec/features/agent_can_convene_applicant_spec.rb
Dans cette PR je filtre les motifs supprimés pour la convocation.
J'ajoute également un paramètre de commit pour afficher directement les créneaux disponibles.
=> fix(convocation): Select active motifs only for convocation

spec/services/stats/compute_rate_of_applicants_with_rdv_seen_in_less_than_thirty_days_spec.rb
Dans cette PR, je fix le test de `ComputeRateOfApplicantsWithRdvSeenInLessThanThirtyDays`, qui pouvait bugger les premiers jours de mars, lorsque le premier jour du mois précédent était distant de moins de 30 jours.
=> fix(tests): fix the ComputeRateOfApplicantsWithRdvSeenInLessThanThirtyDays test

config/initializers/session_store.rb
Lorsque l'application a été créé on ne vérifiait pas si le token de session de RDV-S était valide à chaque requête. 
Par conséquent si on invalidait le token RDV-Solidarités en se connectant à RDVI sur un autre navigateur (ou par API) des sessions RDVI pouvaient rester ouverte sans qu'aucune requête n'aboutisse (puisque les actions ne pouvaient pas se faire sur RDV-S). L'idée était donc de faire des sessions courtes sur RDVI pour éviter ce problème.
Seulement depuis #662 on vérifie que le token est valide à chaque requête, donc on devra automatiquement se logger si le token RDVS devenait invalide. Ainsi j'enlève l'expiration sur la durée de session.
=> feat(app): Do not set expiration for session duration

app/jobs/refresh_out_of_date_rdv_context_statuses_job.rb, config/schedule.yml, spec/jobs/refresh_out_of_date_rdv_context_statuses_job_spec.rb
Cette PR est lié à #85 .
Je fais en sorte qu'on lance une tâche tous les jours à 21h qui met à jours les statuts des `rdv_contexts` qui ne sont pas à jour.
=> feat(app): refresh out of date rdv context statuses

app/controllers/api/v1/applicants_controller.rb, app/jobs/invite_applicant_job.rb, config/routes.rb, spec/jobs/invite_applicant_job_spec.rb, spec/requests/api/v1/applicants_request_spec.rb
Dans cette PR je fais en sorte qu'on ait une route `POST /api/v1/organisations/:rdv_solidarites_organisation_id/users/create_and_invite_many` qui prend des `users` dans le payload, et qui route vers l'action `applicants#create_and_invite_many`. 
L'idée est que l'API soit moins confusante pour les utilisateurs: on garde le terme `users` qui est utilisé dans les webhooks, et on "cache" le terme `applicants` qui est utilisé que dans notre appli. 
J'en profite pour ajouter 2 retry au job `InviteApplicantJob` (pour les cas où SIB est down par exemple)
=> feat(api): Add 'users' route

app/helpers/environments_helper.rb, app/jobs/application_job.rb, app/jobs/refresh_out_of_date_rdv_context_statuses_job.rb, app/jobs/send_invitation_reminders_job.rb, spec/jobs/refresh_out_of_date_rdv_context_statuses_job_spec.rb
Je fais en sorte que les notifications mattermost ne soient envoyées qu'en production lorsque la tâche de mise à jour des statuts se lance.
=> fix(cron): Send mattermost notifications on prod only

app/controllers/organisations_controller.rb, app/models/participation.rb, app/models/stat.rb, app/services/stats/compute_average_time_between_invitation_and_rdv_in_days.rb, app/services/stats/compute_average_time_between_participation_creation_and_rdv_start_in_days.rb, app/services/stats/compute_percentage_of_no_show.rb, app/services/stats/compute_rate_of_applicants_with_rdv_seen_in_less_than_thirty_days.rb, app/services/stats/compute_rate_of_autonomous_applicants.rb, app/services/stats/global_stats/compute.rb, app/services/stats/monthly_stats/compute_for_focused_month.rb, app/services/stats/monthly_stats/upsert_stat.rb, config/schedule.yml, spec/models/stat_spec.rb, spec/services/stats/compute_average_time_between_invitation_and_rdv_in_days_spec.rb, spec/services/stats/compute_average_time_between_participation_creation_and_rdv_start_in_days_spec.rb, spec/services/stats/compute_percentage_of_no_show_spec.rb, spec/services/stats/compute_rate_of_applicants_with_rdv_seen_in_less_than_thirty_days_spec.rb, spec/services/stats/compute_rate_of_autonomous_applicants_spec.rb, spec/services/stats/global_stats/compute_spec.rb, spec/services/stats/monthly_stats/compute_for_focused_month_spec.rb, spec/services/stats/monthly_stats/upsert_stat_spec.rb
closes #836 (inch'allah)
closes #855
📅📊
Pour la PR 855:
- la stat mensuelle sur le `rate_of_applicants_with_rdv_seen_in_less_than_30_days` est calculée avec un mois de décalage par rapport au reste (pour permettre aux bénéficiaires d'acquérir 30 jours "d'ancienneté")
- je calcule les stats mensuelles toutes les semaines : cela permet de calculer en début de mois la stat `rate_of_applicants_with_rdv_seen_in_less_than_30_days` pour m-2 ; pour les autres stats, cela permet d'avoir des stats plus rapidement pour m-1. Pour les "compteurs" de rdvs, invitations, benef, agents, c'est parfait ; pour les autres stats, qui pourraient être imcomplètes à ce moment-là, cela donne une première idée, qui sera updatée régulièrement jusqu'à la fin du mois.
🎉🛁🚧🛺 (ces emojis n'ont aucun sens mais c'est pour …
=> fix(stats): optimize stats + change rythm calculation

app/jobs/rdv_solidarites_webhooks/process_motif_job.rb, app/models/motif.rb, spec/factories/motif.rb, spec/jobs/rdv_solidarites_webhooks/process_motif_job_spec.rb
Après que @qblanc m'ait fait remarquer que certains motifs n'avaient pas stocké de valeur dans la colonne `collectif`, j'ai fait lancé les webhooks pour ces motifs sur RDV-Solidarités. 
Ça m'a fait remarquer que certains motifs sur RDV-I n'étaient plus présents sur RDV-S, parce qu'on ne process pas les "destroyed" event. Cette PR répare ça.
J'en profite pour ajouter une validation sur les motifs pour toujours avoir un booléen dans la colonne `collectif`.
Remarque: Une fois cette PR en prod il faudra supprimer tous les motifs de RDV-I qui ont été supprimés sur RDV-S.
=> feat(webhooks): process destroyed motifs

.env.example, app/clients/mattermost_client.rb, app/jobs/designate_on_watch_developer_job.rb, config/schedule.yml
Dans cette PR je crée un job qui envoie tag chaque semaine le développeur de vigie dans le channel mattermost `startup-data-insertion-bug-RGPD` tous les lundi à 10h.
Pour ça je set le handle du développeur de vigie dans redis.
Remarques: 
* Il est peut-être préférable d'envoyer la notif sur `startup-data-insertion`, vous me direz ce que vous en pensez
* Je ne fais pas de tests puisque ce n'est pas une fonctionnalité directe de l'appli et ce n'est pas critique
* Il faudra ajuster les variables d'environnement et setter manuellement le développeur de garde cette semaine une fois la fonctionnalité déployée
=> feat(ops): Designate on watch developer each week

app/controllers/configurations_controller.rb, app/views/configurations/_configuration_form.html.erb
Cette PR corrige un bug lié à l'ajout de la nouvelle fonction de configuration des organisations : sur la page d'ajout/modification d'une configuration, les fichiers d'imports pouvaient apparaître dupliqués. Cette PR résout ce problème.
=> fix(configuration): avoid duplicate file configurations display

app/controllers/applicants_controller.rb
Dans cette PR, je nullify à la création d'un allocataire le `nir` et le `pole_emploi_id` pour éviter les erreurs `ActiveRecord::RecordNotUnique` lorsque ces champs ne sont pas remplis.
=> fix(applicants): nullify nir and pole emploi id

app/models/concerns/sendable.rb
résout [cette erreur Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/31647/)
Lorsqu'une organisation était configurée sans `MessagesConfiguration`, la génération de lettre entraînait le bug remonté ci-dessus par Sentry. Cette PR corrige ce bug.
=> fix(invitations): hotfix for letters without messages_configurations

app/jobs/rdv_solidarites_webhooks/process_agent_role_job.rb, spec/jobs/rdv_solidarites_webhooks/process_agent_role_job_spec.rb
Dans cette PR je fais en sorte de supprimer les agents lorsqu'ils n'appartiennent plus à aucune org chez nous.
Une fois cette PR déployé je supprimerais manuellement tous les agents en base qui sont déjà supprimés sur RDVS.
=> fix(webhooks): Remove deleted agents

app/models/rdv_solidarites_session/with_shared_secret.rb, spec/models/rdv_solidarites_session/with_shared_secret_spec.rb
Mauvais id dans la validation de la session pour Inclusion Connect.
Tout passait correctement en local parceque j'ai eu un faux positif avec mes ids...
=> BugFix Inclusion Connect

app/models/organisation.rb, spec/models/organisation_spec.rb
https://github.com/betagouv/rdv-insertion/issues/933
J'ai modifié uniquement le modèle `organisation`. J'ai pas touché au module `Phonable` pour qu'il reste générique.
La PR coté RDV-S est merge (https://github.com/betagouv/rdv-solidarites.fr/pull/3421)
=> Ajout d'une validation pour les organisations avec un téléphone à 4 chiffres

app/services/concerns/invitations/sms_content.rb, app/views/letters/invitations/short.html.erb, app/views/letters/invitations/standard.html.erb, app/views/mailers/invitation_mailer/short_invitation.html.erb, app/views/mailers/invitation_mailer/standard_invitation.html.erb, spec/mailers/invitation_mailer_spec.rb, spec/services/invitations/generate_letter_spec.rb, spec/services/invitations/send_sms_spec.rb
closes #938 
Dans cette PR, je change le message standard pour remplacer la notion de `devoir prendre un rendez-vous` par celle d'être `invité à` en prendre un.
=> feat(invitations): change standard orientations messages

app/controllers/organisations_controller.rb, app/views/organisations/_organisation_form.html.erb, app/views/organisations/index.html.erb, config/routes.rb
Dans cette PR, je change la position du bouton "Lier une organisation RDVS" sur la page `index` des `organisations`.
Il était jusqu'alors proposé dans chaque tuile département ; il est désormais positionné en bas de page, en dehors du contexte d'un département. Le but de ce changement est de permettre aux agents d'ajouter une orga dans un département qui existe mais n'apparaît pas dans leur liste d'organisations. Pour leur faciliter la tâche, la modal `new` leur propose un dropdown listant tous les départements existants.
=> feat(configuration): change create organisation button position

db/migrate/20230411153039_add_custom_sentence_to_templates.rb, db/migrate/20230411153056_add_france_travail_orientation_template.rb, db/schema.rb
Dans cette PR, je corrige l'erreur de migration liée [la PR #969](https://github.com/betagouv/rdv-insertion/pull/969), et j'en profite pour séparer en deux le fichier de migration pour une meilleur logique (cf un commentaire de @aminedhobb sur la PR citée plus haut).
=> fix(migrations): fix migrations for france travail motif category

app/jobs/send_convocation_reminders_job.rb, spec/jobs/notify_participations_job_spec.rb, spec/jobs/send_convocation_reminders_job_spec.rb
L'envoi de rappel de convocations ne fonctionnait pas parce que le nom de l'`event` envoyé au `NotifyParticipationsJob` n'était pas le bon (bug remonté dans [cette erreur Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/35421/?project=16&query=is%3Aunresolved)). Cette PR permet de corriger ce souci.
=> fix(participations) : fix notifications reminders

app/controllers/api/v1/applicants_controller.rb, app/controllers/concerns/api/v1/params_validation_concern.rb, spec/requests/api/v1/applicants_request_spec.rb
Ce mail fait suite au mail reçu par le Cantal et est lié à cette erreur sur Sentry: https://sentry.incubateur.net/organizations/betagouv/issues/34431/?project=16&query=is%3Aunresolved
On doit pouvoir pouvoir appeler l'API sans préciser de catégorie de motifs (qui se trouve derrière la clé "invitation") lorsque l'organisation ne gère qu'une seule catégorie de motif. Le fix introduit dans cette PR le permet.
On renvoie également des messages d'erreurs différents lorsque la catégorie n'est pas précisée alors qu'elle doit l'être et lorsque la catégorie est invalide.
=> fix(api): Allow api call without invitation attributes

Gemfile.lock, app/models/concerns/applicant/nir.rb, spec/models/applicant_spec.rb
closes #994 
Dans cette PR, je permets aux agents de renseigner des NIR à 13 chiffres.
Pour garder des NIR cohérents à 15 chiffres en db, j'ajoute après validation, lorsque les NIR sont à 13 chiffres, la clé de sécurité sociale.
Ce dernier point n'est pas forcément indispensable : on pourrait stocker les NIR à 13 chiffres et faire l'ajout plus tard si nécessaire?
N.B. : je fais passer dans cette PR un petit ajout au `Gemfile.lock` consécutif à la montée de version de ruby
=> feat(nir): allow 13 numbers nir

app/controllers/invitations_controller.rb
closes #992 
Dans cette PR, je fix le bug rencontré par le MIE Genevois lorsqu'ils tentaient d'inviter au niveau de "toutes les organisations" des bénéficiaires sans référents, ce qui ne fonctionnait pas à cause des autres organisations de leur département qui réclamaient un référent (voir l'issue pour plus de détail). J'ai fait des tests fonctionnels ça résout bien le problème (sans effet de bord a priori)
=> fix(invitations): Invite without referents in mixed configurations departments

app/controllers/applicants/searches_controller.rb, app/lib/phone_number_formatter.rb, app/lib/phone_number_helper.rb, app/models/applicant.rb, app/models/concerns/phone_number_validation.rb, app/models/concerns/sendable.rb, app/models/rdv_solidarites/user.rb, app/services/applicants/find_or_initialize.rb, app/services/concerns/messengers/send_sms.rb, app/services/invitations/send_sms.rb, app/services/notifications/send_sms.rb, app/services/send_transactional_sms.rb, app/views/letters/notifications/by_phone_participation_created.html.erb, app/views/mailers/notification_mailer/by_phone_participation_created.html.erb, app/views/mailers/notification_mailer/by_phone_participation_reminder.html.erb, app/views/mailers/notification_mailer/by_phone_participation_updated.html.erb, spec/jobs/rdv_solidarites_webhooks/process_user_job_spec.rb, spec/services/invitations/send_sms_spec.rb, spec/services/notifications/send_sms_spec.rb, spec/services/send_transactional_sms_spec.rb
Dans cette PR j'enlève la méthode `applicants#phone_number_formatted` qui n'est plus utilisée depuis #976 , puisqu'on formate toujours les numéros de téléphones avant de sauvegarder en base maintenant.
J'en profite pour refactorer le module `PhoneNumberFormatter` pour que ses méthodes soient accessibles depuis l'extérieur sans inclure le module (en faisant des méthodes de classe), et ainsi je pense améliorer la lisibilité.
=> refactor(app): Remove applicant phone_number_formatted method

app/models/rdv.rb
close https://github.com/betagouv/rdv-insertion/issues/1029
A priori c'est la première fois que l'on reçoit un rdv créé par un prescripteur et sidekiq n'aime pas trop car la valeur prescripteur ne fait pas partie de l'enum du model.
Je ne modifie aucun comportement de l'app, j'ajoute juste la valeur `prescripteur` à l'enum du `created_by` du rdv.
=> bug(jobs) Add `prescripteur` in `created_by` enum

app/views/applicants/_close_rdv_context_button.html.erb
Dans cette PR, je fix la redirection lorsq'un rdv_context est close au niveau de l'organisation. Le param passé dans le formulaire n'était pas le bon.
@aminedhobb je me permets de le déployer direct car c'est un hotfix et il n'y a que deux lignes qui changent.
=> fix(show): fix rdv_context closing redirect

app/controllers/notifications_controller.rb, app/views/applicants/_convocations.html.erb, app/views/applicants/_rdv_context.html.erb
Reverts betagouv/rdv-insertion#981
Le fait de ne plus préciser le format empêche la génération du courrier.
Je revert en attendant de résoudre le problème initial (affichage de l'erreur lorsque la génération est impossible)
=> Revert "fix(notifications): forbid pdf generation if applicant address is invalid"

Gemfile, Gemfile.lock, app/controllers/notifications_controller.rb, app/javascript/react/lib/createInvitationLetter.js, app/services/concerns/messengers/generate_letter.rb, app/views/applicants/_convocations.html.erb, app/views/applicants/_rdv_context.html.erb, app/views/common/_flash.html.erb, spec/controllers/applicants_controller_spec.rb, spec/features/agent_can_generate_convocation_pdf_spec.rb, spec/rails_helper.rb, spec/services/invitations/generate_letter_spec.rb, spec/services/notifications/generate_letter_spec.rb, spec/support/capybara_config.rb, spec/support/download_helper.rb, spec/support/pdf_helper.rb
Suite de #1045 .
Je retente de fixer le bug décrit #950 , la dernière tentative ayant été revert dans #1045.
Pour montrer les erreurs à la génération du courrier de convocation, je set simplement un flash avec l'erreur rencontrée et je recharge la page. 
Au passage, j'enlève l'animation des flashs lorsque ce sont des flashs d'erreurs (je l'avais fait aussi dans #1026 ) car il me semble important de pouvoir lire les messages erreurs et de bien les montrer.
J'en profite également pour ajouter des tests d'intégrations sur cette feature. Pour se faire j'introduis de nouveaux helpers de test qui aident à gérer les download sur les tests d'intégration ainsi que la lecture des pdfs pour tester leur contenu. Pour ce dernier point j'importe la gem `pdf-reader` dans notre environnement de test.
=> fix(notifications): Show postal convocation generation errors

app/controllers/messages_configurations_controller.rb, spec/controllers/messages_configurations_controller_spec.rb
Lorsqu'un record de `MessageConfiguration` était modifié depuis le formulaire, les attributs `sender_city` et `letter_sender_name` étaient save avec des strings vides, ce qui avait des conséquences indésirables pour les courriers. Ce fix corrige ce problème en nullifiant les params lorsqu'ils sont blank.
Side note : ce hotfix rouvre la question de l'issue #922. Je pense que le plus simple/le plus pertinent pour résoudre cette issue serait de passer par des callbacks `before_validation` dans les modèles. Cette logique devrait en effet plutôt être gérée au niveau du modèle que du contrôleur selon moi
=> fix(configurations): avoid blank sender city and letter sender name

app/javascript/react/models/Applicant.js
On ne propose pas dans l'interface de configuration du fichier d'entrée de remplir le champ qui correspond au champ "adresse" mais que les compléments d'adresse. Ce qui faisait que l'adresse n'était pas envoyée à la création des bénéficiaires.
Cette PR répare cela. Il faudra également faire un changement dans l'interface de config pour  proposer la colonne d'adresse principale.
=> fix(jsapp): Send full address even when address column not filled

app/javascript/react/models/Applicant.js
Micro fix pour permettre aux départements d'utiliser la valeur `M`ou `m`pour la civilité masculine ; jusque là, seuls `mr`et `monsieur`étaient acceptés.
=> fix(upload): allow `m` for `monsieur`

app/controllers/applicants_controller.rb, app/views/applicants/index.html.erb, db/migrate/20230509205431_create_archives.rb
Sur la page "archivés", les personnes sont listés via les `@archives` pour pouvoir facilement les lister par ordre de création d'archive. Du coup il faut paginer ces records `@archives` comme ce qu'on fait pour les `@applicants`.
J'en profite pour simplifier une condition dans le template index (qui je me rends compte va probablement disparaitre de toutes façons avec #982 )
=> fix(applicant): Add pagination for archives

app/controllers/applicants_controller.rb, app/models/archive.rb, app/views/applicants/_applicants_archived_table.html.erb
En déployant #1066 je me suis rendu compte que la recherche ne marchait pas pour les personnes archivées et qu'il y avait en fait une solution beaucoup plus simple pour trier les personnes en fonction de la date d'archivage..
=> fix(archive): Sort applicants by archives

app/services/concerns/notifications/sms_content.rb, spec/services/notifications/send_sms_spec.rb
Nous avons certains sms de convocations qui n'arrivent pas à leur destinataire (voir [sentry](https://sentry.incubateur.net/organizations/betagouv/issues/39795/?project=16&query=is%3Aunresolved&referrer=issue-stream)) car les instructions configurées sur le motif dans RDVS sont trop longues pour être mises dans un SMS. En voici un exemple pour des sms qui n'ont pas pu être délivrées: 
Je pense qu'on ne peut pas de toutes façons laisser un champ libre pour les SMS. 
On pourrait faire en sorte de n'insérer l'instruction que si elle est inférieure à un certain nombre de caractère, mais il faudrait un moyen de l'afficher explicitement sur l'appli (quand on pourra configurer les motifs sur RDVI par exemple), sinon on risque d'entrainer de la confusion chez nos utilisateurs qui ne sauront pas …
=> fix(notifications): Remove instruction for rdv from sms

app/controllers/applicants/searches_controller.rb, app/controllers/concerns/applicants/filterable.rb, app/controllers/referent_assignations_controller.rb, app/javascript/react/models/Applicant.js, app/jobs/rdv_solidarites_webhooks/process_referent_assignation_job.rb, app/models/agent.rb, app/models/applicant.rb, app/models/referent_assignation.rb, app/services/applicants/assign_referent.rb, app/services/applicants/remove_referent.rb, app/services/exporters/generate_applicants_csv.rb, app/services/invitations/compute_link.rb, app/services/invitations/validate.rb, app/views/applicants/show.html.erb, app/views/letters/invitations/atelier.html.erb, app/views/letters/invitations/phone_platform.html.erb, app/views/letters/invitations/short.html.erb, app/views/letters/invitations/standard.html.erb, app/views/referent_assignations/create.turbo_stream.erb, app/views/referent_assignations/destroy.turbo_stream.erb, app/views/referent_assignations/index.html.erb, config/locales/models/applicant.fr.yml, db/migrate/20230606084749_rename_agents_applicants_to_referent_assignations.rb, db/schema.rb, spec/controllers/applicants_controller_spec.rb, spec/controllers/referent_assignations_controller_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_referent_assignation_job_spec.rb, spec/services/applicants/assign_referent_spec.rb, spec/services/applicants/remove_referent_spec.rb, spec/services/exporters/generate_applicants_csv_spec.rb
J'ajoute les emails des agents référents dans l'export CSV.
J'en profite pour faire un renommage et parler de `referents` plutôt que d'`agents` lorsque l'on récupère les référents d'une personne.
=> feat(csv): Add referents to csv export

app/helpers/applicants_helper.rb, app/models/rdv_context.rb, spec/features/agent_can_convene_applicant_spec.rb
closes #1061 
Dans cette PR, je permets de convoquer les bénéficiaires plus seulement lorsqu'ils ont une invitation en délai dépassé mais aussi lorsque leur statut est : 
- "RDV annulé à l'initiative de l'allocataire"
- "Absence non excusée au RDV"
- "Plusieurs RDV reportés par l'allocataire".
=> feat(convocations): allow convocation in more cases

app/models/agent_role.rb, app/services/organisations/create.rb, db/migrate/20230613095607_rename_agent_role_level_to_access_level.rb, db/schema.rb, db/seeds.rb, docs/INSTALL.md, spec/factories/agent_role.rb, spec/jobs/rdv_solidarites_webhooks/process_agent_role_job_spec.rb, spec/models/agent_role_spec.rb
Fait suite à un changement coté rdvsp ici : https://github.com/betagouv/rdv-solidarites.fr/pull/3609
L'attribut `level` du model `AgentRole` est renommé en `access_level`.
Cela nous permet de gagner en lisibilité (coté rdvsp particuliérement).
Une fois cette PR merge j'enleverai l'attribut `level` du blueprint coté rdvsp.
=> refactor(app): rename AgentRole attribute level to access_level

app/services/applicants/find_or_initialize.rb
Fix [cette issue Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/48213/?query=is%3Aunresolved&referrer=issue-stream) : quand un bénéficiaire était uploadé sans prénom, le service `FindOrInitialize` était buggé.
=> fix(upload): hotfix for FindOrInitialize

app/models/applicant.rb, db/migrate/20230613163040_add_id_to_referent_assignations.rb, db/schema.rb
On avait un problème lorsqu'un agent était assigné référent au moment de le supprimer à cause de la relation `has_many :referent_assignations, dependent: :destroy`. Comme la table `referent_assignations` n'avait pas de clé primaire on ne sait pas quelles entrées supprimer.
J'ajoute donc une clé primaire à la table `referent_assignations` dans cette PR.
=> fix(referents): Add primary key to refererent assignations

app/lib/nir_helper.rb, app/models/concerns/applicant/nir.rb, spec/models/applicant_spec.rb, spec/support/nir_helper.rb
closes #1124 
Les personnes nées en Corse peuvent avoir un 2A ou un 2B dans leur NIR. Dans ce cas, pour le calcul de la clé de contrôle, le numéro du département 2A (Corse-du-Sud) est remplacé par 19 et celui du 2B (Haute-Corse) par 18 MAIS le nir sauvegardé doit garder 2A ou 2B dedans. Cette PR gère cette particularité.
=> fix(nir): allow corsica nirs

app/models/concerns/motif_category/sortable.rb, app/services/invitations/generate_letter.rb, app/views/letters/invitations/atelier.html.erb, app/views/letters/invitations/phone_platform.html.erb, app/views/letters/invitations/short.html.erb, app/views/letters/invitations/standard.html.erb, app/views/letters/notifications/by_phone_participation_created.html.erb, app/views/letters/notifications/participation_cancelled.html.erb, app/views/letters/notifications/presential_participation_created.html.erb, config/locales/models/motif.fr.yml, db/migrate/20230328075606_add_siae_motif_category.rb, db/migrate/20230625132307_add_motif_categories_and_templates_for_siae.rb, db/schema.rb, spec/mailers/invitation_mailer_spec.rb, spec/services/invitations/generate_letter_spec.rb, spec/services/invitations/send_email_spec.rb, spec/services/invitations/send_sms_spec.rb, spec/support/motif_categories_helper.rb
closes #993
closes #1111 
Dans cette PR, j'ajoute des `MotifCategory` et des `Template` pour les SIAE : `rendez-vous de suivi` et `rendez-vous d'information collective`. J'en profite pour rajouter des tests manquants sur le contexte `spie_interview` ainsi que dans la méthode `Sortable`.
@amaurydubot & @SalmaBennani par rapport à ce que vous aviez mis dans vos issues, les infos relatives au fichier d'entrée ou aux paramètres tels que les délai d'expiration, par exemple, seront à configurer vous même lorsque vous créerez des configurations pour les structures. Vous pourrez le faire dès que cette PR sera mergée.
=> feat(category): add new contexts for siae

app/javascript/react/components/Applicant.jsx, app/javascript/react/components/ApplicantList.jsx, app/javascript/react/pages/ApplicantsUpload.jsx, db/migrate/20230626131432_add_cdb_ids_to_departments_and_applicants.rb, db/schema.rb
closes #1107 
closes #1104 
Dans cette PR, j'ajoute des colonnes pour stocker les ids des déploiements cdb et des carnets, et j'ajoute un emplacement pour le CTA de la création de carnet sur la page upload.
=> feat(cdb): add CTA and columns for carnet de bord

app/services/carnet_de_bord/create_carnet.rb, spec/services/carnet_de_bord/create_carnet_spec.rb
L'attribut renvoyé en cas d'erreur est `message` et non pas `error` comme marqué dans le notion
=> fix(cdb): Change cdb response attribute

app/views/layouts/application.html.erb
=> fix: Change layout title from Rdv insertion to rdv-insertion

app/javascript/stylesheets/pdf.scss
Le logo débordait car en l'absence d'autre logo il prenait par défaut sa largeur originale soit `406 × 99`. Je l'ai limité à 350px de largeur ce qui permet d'éviter le débordement. Voici le résultat une fois fixé avec les 4 différentes possibilités. 
Si cette grande taille de logo n'était pas voulu on pourrait mettre plus petit car lorsque il est seul, le logo de RI est quand même assez grand. 300px semblait déjà suffisant.
Maintenant que sa taille maximale sera limitée on pourrait également mettre des logo @2x pour améliorer la qualité des images.
Ticket: https://github.com/betagouv/rdv-insertion/issues/1163
=> fix(css): avoid overflow of logos on PDFs

app/services/rdv_solidarites_api/invite_user.rb, spec/services/rdv_solidarites_api/invite_user_spec.rb
Petite refacto pour être iso avec les changements à venir dans cette PR : https://github.com/betagouv/rdv-solidarites.fr/pull/3690
On utilise plus le params de l'api rdvs `invite_for` pour gérer l'expiration de l'invitation (gérer directement dans rdvi)
=> refactor(app): remove unused invite_for params

app/javascript/react/components/applicant/ContactInfosExtraLine.jsx, app/javascript/react/lib/updateApplicantContactsData.js
Il y avait un souci sur la manière dont on appelait la fonction `handleApplicantUpdate` depuis le component `ContactsInfoExtraLine` suite à un changement précédent qui faisait que l'update ne fonctionnait pas (voir #1193 ).
Je fais un hotfix ici, et j'introduirai des tests d'intégration après pour qu'on n'ait plus ce genre de régression.
J'en profite pour faire en sorte que le numéro de tel du fichier de contact ne soit plus considéré comme nouveau s'il n'y a que son format qui change. Je ne compare plus que les 8 derniers chiffres.
=> fix(upload): Fix contacts data update

app/javascript/components/matomo-script-tag.js, app/javascript/packs/application.js
Dans cette PR je mets en place le mécanisme pour injecter le script de matomo sur nos pages permettant d'utiliser le tag manager de matomo.
=> feat(analytics): Add Matomo tag manager

app/javascript/components/matomo-script-tag.js
hotfix sur la manière d'appeler la variable d'environnement `MATOMO_CONTAINER_ID`
=> fix(analytics): Call matomo container id correctly

app/models/applicant.rb, app/services/applicants/validate.rb, spec/services/applicants/validate_spec.rb
Nous avons 48 personne en DB qui n'ont pas d'attribut `identifier` parce que la règle de présence d'un de ces attributs a été ajoutée récemment. 
Ces 48 records sont donc considérés comme invalides, et donc il est impossible des les mettre à jour lorsque l'on reçoit un webhook les concernant sur rdvs (voir https://www.rdv-insertion.fr/sidekiq/retries). 
Je propose donc de bouger cette règle de validation dans le service `Applicants::Validate` pour qu'elle ne soit utilisée que lors de la création/modification d'une personne via l'interface de RDV-I, et que ces personnes puissent être mises à jour via les webhooks de rdvs.
=> refactor(validation): Move id presence validation

Gemfile, Gemfile.lock
On avait un problème au niveau des webdrivers qui la bonne version du driver chrome. 
En mettant à jour `selenium-webdriver` et enlevant la gem `webdrivers` ça fonctionne sans avoir à préciser une version spécifique de chromedriver (voir https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1642289629). 
J'ai dû en parallèle mettre à jour `capybara` puisqu'une autre erreur apparaissait suite à cette update (+ d'infos [ici](https://github.com/teamcapybara/capybara/issues/2666)).
=> chore(deps): Upgrade selenium-webdriver and capybara versions

app/helpers/applicants_helper.rb, app/views/applicants/show.html.erb
Cette PR ajoute un lien vers la page de recherche de RDV sur RDV-Solidarités filtrée sur l'utilisateur affiché.
Corrige #1077
=> feat(applicant): add link to rdv page

app/controllers/concerns/applicants/filterable.rb, app/controllers/configurations_controller.rb, app/javascript/controllers/autocomplete_controller.js, app/javascript/controllers/tags_controller.js, app/javascript/react/components/applicant/EditTags.jsx, app/javascript/react/components/applicant/EditableCell.jsx, app/javascript/react/components/applicant/EditableTags.jsx, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/components/_autocomplete.scss, app/views/applicants/_filter_by_tag_button.html.erb, app/views/tags/_tag_form.html.erb, app/views/tags_filterings/new.html.erb, config/locales/models/applicant.fr.yml, config/locales/models/file_configuration.fr.yml, spec/controllers/applicants_controller_spec.rb, spec/features/agent_can_edit_applicant_tags_spec.rb
Cette PR permet l'ajout d'un dropdown de sélection permettant de créer des tags basés sur ceux existant dans le département plutôt que d'en créer de nouveaux. 
Ceci devrait éviter la duplication de tags ayant des nommages quasi similaires. 
https://github.com/betagouv/rdv-insertion/assets/4990201/bee0f6dd-1dd0-4183-b02d-01b28feb702f
Le dropdown d'autocomplete est ré-utilisable, non associé avec les tags, pour cela il suffit d'avoir le HTML suivant : 
```html
<div class="autocomplete-container" data-controller="autocomplete">
<input>
<div class="autocomplete">
<button>pomme</button>
<button>banane</button>
</div>
</div>
```
J'ai également renommé "Catégories d'usagers" en "Tags" ainsi que passé les filtres sur les tags en AND plutôt que OR. 
Corrige #1300
=> feat(tags): Dropdown for selecting existing tags

app/controllers/applicants_controller.rb, app/views/applicants_organisations/_applicants_organisation.html.erb, app/views/tags/_tag.html.erb, spec/controllers/applicants_controller_spec.rb, spec/features/agent_can_add_or_remove_applicant_from_organisations_spec.rb
Cette PR rajoute un confirm sur la suppression d'un tag de l'organisation et corrige un problème empêchant la suppression de l'ensemble des tags d'un utilisateur depuis la page show. 
Corrige #1312
=> fix(tags): prevent unwanted destroys and minor fixes

app/jobs/transfer_email_reply_job.rb, app/mailers/reply_transfer_mailer.rb, app/views/mailers/reply_transfer_mailer/_organisation_email_not_found.html.erb, app/views/mailers/reply_transfer_mailer/forward_invitation_reply_to_organisation.html.erb, app/views/mailers/reply_transfer_mailer/forward_notification_reply_to_organisation.html.erb, spec/jobs/transfer_email_reply_job_spec.rb
Lié à #1281 . 
On envoie une notif mattermost à chaque fois qu'un email d'usager est transféré.
J'en profite pour ajouter un message dans le mail transféré lorsque le mail est transféré à `support@rdv-insertion.fr` parce que l'email de l'organisation  n'est pas présent sur l'appli.
=> feat(mail): notify mail redirection on mattermost

app/jobs/notify_participation_job.rb, app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb, app/models/applicant.rb, db/migrate/20230830142108_add_created_through_to_applicants.rb, db/schema.rb, spec/jobs/notify_participation_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb
Dans cette PR j'ajoute une colonne à la table `applicants` pour différencier les personnes créées depuis rdv-solidarites et celles créées depuis rdv-insertion. 
Comme expliqué [dans cette conversation](https://mattermost.incubateur.net/betagouv/pl/6z6wk8c5xjnm8rm5jy4wyfeige), on décide de ne pas envoyer des messages de convocations aux personnes créées depuis rdv-solidarites qui n'ont pas été invitées.
=> feat(notifications): do not notify applicants not created through rdvi

app/models/concerns/motif_category/sortable.rb, config/locales/models/motif.fr.yml, db/migrate/20230831090625_add_motif_category_for_var.rb, db/schema.rb, db/seeds.rb
@aminedhobb PI il y avait des tests dans les précédentes PR de création de contexte mais comme j'évoquais à Quentin dans `spec/services/invitations/generate_letter_spec.rb` de la ligne 159 à 420 ils devraient pouvoir être enlevés car ils ne font que tester le résultat dans les invitations de record fictifs créés pour le tests (qui ne sont pas liés avec ceux en prod).
=> feat(category): add new context for var

app/jobs/send_periodic_invites_job.rb, db/migrate/20230822125225_add_number_of_days_before_next_invite_to_configurations.rb, db/schema.rb, spec/jobs/send_periodic_invites_job_spec.rb
Cette PR permet d'éviter l'envoi d'invitations périodiques dans le cas où aucune configuration n'a été set. 
Pour cela on enlève la valeur par défaut de la colonne.
=> fix: prevent periodic invites to be sent when the configuration is nil

app/controllers/previews/notifications_controller.rb, spec/features/agent_can_preview_messages_contents_spec.rb
Dans #1267 @Michaelvilleneuve  a ajouté un nouvel attribut à passer pour la génération des courriers de convocations.
Je le rajoute pour pouvoir visualier les previews sans lever de cette erreur dans la Drôme: 
https://sentry.incubateur.net/organizations/betagouv/issues/63392/?project=16&query=is%3Aunresolved&referrer=issue-stream
L'erreur  n'était pas levée dans les tests car on utilise l'attribut `motif_category` que si on est dans la Drôme.
=> fix(previews): Add attribute for letter notifications preview

app/models/concerns/has_logo.rb
closes #1329 
Dans cette PR, je permet au système de récupérer le logo correspondant au `logo_filename` en fonction de la string tapée par l'utilisateur : quelque soit la casse ou la graphie du `logo_filename`, le système ira chercher le logo avec ce nom là, sans transformation. La tentative de jonction entre une organisation et son logo se fait malgré tout **toujours** dans un format parameterize (downcase, underscore pour les espaces) : cela reste la convention de nommage à privilégier pour les logos.
=> fix(logos): allow upcase for logos

app/controllers/concerns/applicants/filterable.rb, spec/controllers/applicants_controller_spec.rb
Cette PR permet d'éviter de crash lorsque certains browser envoient un seul tag à filtrer. 
Par défaut les browsers envoient un tableau contenant un seul élément mais il semblerait que Edge n'envoie pas un tableau mais envoie directement l'élément inline. 
Pour régler ça on enveloppe le param dans un tableau que l'on flatten, de cette façon on obtient toujours un tableau
=> fix: prevent arg error when some browser send a single tag

app/models/stat.rb, app/services/stats/compute_rate_of_autonomous_applicants.rb, app/services/stats/global_stats/compute.rb, app/services/stats/monthly_stats/compute_for_focused_month.rb, scripts/initialize_no_show_rate_for_stats.rb, scripts/recompute_autonomous_stats.rb, spec/models/stat_spec.rb, spec/services/stats/compute_rate_of_autonomous_applicants_spec.rb, spec/services/stats/global_stats/compute_spec.rb, spec/services/stats/monthly_stats/compute_for_focused_month_spec.rb
closes #1352 
Dans cette PR, je change la façon dont nous calculons le pourcentage de rendez-vous pris en autonomie. Notre précédente méthode de calcul était très imparfaite car les `participations` ne portaient pas encore l'information `created_by`, nécessaire pour bien calculer cette stat pour les rendez-vous collectif. Cette PR corrige ce souci.
Il faudra lancer le script `recompute_autonomous_stats` après déploiement pour recalculer cette stat.
N.B. : pas le scope de cette PR mais j'en profite pour commit un script plus propre pour `initialize_no_show_rate_for_stats` (évitant notamment de lancer le gros job de calcul de stats globales) ; je ferai ensuite une PR pour le supprimer, mais ça nous permet de garder une trace d'un script "propre" au cas où on le cherche plus tard.
=> feat(stats): improve autonomous applicants rate computing

app/javascript/react/components/UserBatchActions.jsx
L'ajout d'un top: 40px sur le composant partagé de dropdown a pété cette vue car le composant parent n'était pas en relatif. Le top: 40 était donc relatif à l'écran donc le menu partait en haut de l'écran.
=> fix: dropdown css menu broken

Gemfile.lock
Les jobs n'étaient plus retried lorsqu'une erreur était levée à cause de l'option `retry_for => 0` ajoutée dans les jobs dans la version `7.1.3`. 
La version `7.1.4` que je mets à jour ici contient le fix associé (voir https://github.com/sidekiq/sidekiq/pull/6035).
=> chore(deps): bump sidekiq version

app/controllers/users_controller.rb, app/services/exporters/generate_users_csv.rb
La Manche a un "Application timeout" lorsqu'elle tente de charger un export csv. Il y avait en effet des n+1 au moment de la création du fichier, cette PR résout ce problème. Je bouge également le `preload` dans le controller, ce qui me paraît plus logique que dans le service.
N.B : Je pense qu'il faudrait qu'on se penche sur les ressources chargées non seulement pour la génération du csv mais également lorsque les pages index commencent à avoir de grandes collections de `users`. La Manche a par exemple à date 213 pages de users, ce qui rend le chargement de la page pas très rapide. On pourrait peut-être optimiser ça.
=> fix(exports): remove n+1 queries in csv exports

app/javascript/lib/retrieveContactPhoneNumber.js, app/javascript/react/components/User.jsx, app/javascript/react/components/user/ContactInfosExtraLine.jsx, app/javascript/react/lib/parseContactsData.js, spec/features/agent_can_update_contacts_info_spec.rb
Cette PR empêche la possibilité de mettre à jour des données d'un usager alors que celui-ci n'est pas affecté à la même organisation.  
Elle permet aussi de diminuer la fréquence d'affichage du bouton de mise à jour en ne prenant pas en compte les différences de casse sur l'email
Corrige https://github.com/betagouv/rdv-insertion/issues/1342
Corrige aussi https://github.com/betagouv/rdv-insertion/issues/1204
=> fix(upload): prevent updating before creating

app/views/stats/_stats.html.erb
Plusieurs petites typos sur la page stats `... de usagers` plutôt que `... d'usagers`, consécutives au changement de naming des bénéficiaires en usagers. Cette PR résout ce problème.
=> fix(stats): typos after applicants naming change

app/views/stats/_stats.html.erb
Lorsque certaines valeurs étaient `nil`, les pages stats renvoyaient des 500. Cette PR règle ce problème.
Je choisis de ne pas mettre de default value pour les colonnes de stats car cela permet de mieux différencier celles qui pourraient avoir une valeur nulle de manière légitime des stats non calculées.
=> fix(stats): avoid 500 for stats

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/services/exporters/generate_users_csv.rb, config/environments/development.rb, config/initializers/prosopite.rb
Dans cette PR j'essaie d'éviter les requêtes inutiles lors de l'export csv pour essayer de générer le fichier plus rapidement.
Pour ce faire: 
* J'enlève la gem [`bullet`](https://github.com/flyerhzm/bullet) qui détecte beaucoup de faux positifs et je mets [`proposite`](https://github.com/charkost/prosopite) à la place qui me parait + fiable
* Dans le service de l'export, je fais 2 preload différents en fonction du cas où une catégorie de motif est définie ou non
* J'évite certains preload qui ne sont pas nécessaires dans le cadre d'un export csv dans le `users_controller`
=> feat(perf): Optimize csv export

app/jobs/stats/monthly_stats/upsert_stat_job.rb, spec/jobs/stats/monthly_stats/upsert_stat_job_spec.rb
le job n'avait pas été modifié pour prendre en compte la nouvelle manière d'appeller le service
=> fix(stats): upsert monthly stat job

app/models/stat.rb, app/services/stats/compute_rate_of_users_with_rdv_seen_in_less_than_thirty_days.rb
Les jobs de stats prennent trop de temps à être run ; celui qui regroupe les stats de toute l'app tourne même + de 24h sans parvenir à se terminer. Cette PR vise à améliorer les perfs en :
- enlevant une requête n+1 (le preload des rdvs)
- limitant le `select` dans `ComputeRateOfUsersWithRdvSeenInLessThanThirtyDays` aux seuls utilisateurs susceptibles de passer le test (ie, ceux qui ont au moins un rdv honoré)
- découpant ce `select` en batch
=> feat(stats): better perfs for stats jobs

app/models/concerns/rdv_participation_status.rb, app/models/participation.rb, app/models/rdv.rb, app/services/notifications/notify_participation.rb, app/views/rdv_contexts/_convocations.html.erb, spec/controllers/users_controller_spec.rb, spec/features/agent_can_generate_convocation_pdf_spec.rb, spec/models/participation_spec.rb, spec/models/rdv_spec.rb, spec/services/notifications/notify_participation_spec.rb
Je me suis rendu compte qu'il n'y avait rien dans le code qui empêchait d'envoyer une notification alors que le rdv est déjà passé, je rajoute cette contrainte pour être sûr de ne pas envoyer de notif si on met à jour un vieux rdv
=> feat(notifications): Prevent sending a notification when rdv is in the past

app/controllers/concerns/users/sortable.rb, app/helpers/users_helper.rb, app/views/users/_users_table_for_motif_category.html.erb, spec/controllers/users_controller_spec.rb
Cette PR permet de trier les usagers par date d'invitation depuis les listing de motifs catégories : 
Corrige https://github.com/betagouv/rdv-insertion/issues/1271
=> fix(users): add abillity to order by invitations created_at

app/javascript/react/pages/UsersUpload.jsx
Cette PR rend possible la création de tags par nombre. 
Aujourd'hui uploader un fichier avec un tag en integer lève une erreur JS. Cette PR corrige l'erreur et transforme le tag en string.
=> fix(tags): allow tags as numbers

app/controllers/concerns/users/sortable.rb, app/helpers/users_helper.rb, app/views/users/_users_table_for_motif_category.html.erb, spec/controllers/users_controller_spec.rb
Reverts betagouv/rdv-insertion#1436
J'ai l'impression que le mécanisme inhérent à la PR ne fonctionne pas comme il faudrait ou en tous cas que l'ajout apporté  est trop confusant pour les utilisateurs à l'heure actuelle: 
Je propose qu'on revert cette PR en attendant le retour de @Michaelvilleneuve .
Ce revert fait suite à une discussion ici: https://mattermost.incubateur.net/betagouv/pl/o5f93fs85bgc8yz951oh49htrh
=> Revert "fix(users): add abillity to order by invitations created_at"

app/controllers/concerns/users/sortable.rb, app/controllers/users_controller.rb
J'ai remarqué en faisant certains tests que des doublons apparaissaient lorsqu'on faisait une recherche sur la page index. 
En me plongeant un peu dans le code j'ai remarqué que certaines queries n'étaient pas nécessaires.
J'enlève ici le code qui n'est pas nécessaire, et je fais en sorte de spécifier le `select` seulement à l'endroit où on en a besoin, c'est à dire l'endroit où on fait l'ordering en fonction de ce qu'on a sélectionné.
=> refactor(sorting): Use simpler queries on index page

app/clients/mattermost_client.rb, app/jobs/notify_participation_job.rb, app/jobs/rdv_solidarites_webhooks/process_agent_role_job.rb, app/jobs/rdv_solidarites_webhooks/process_referent_assignation_job.rb, spec/jobs/notify_participation_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_agent_role_job_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_referent_assignation_job_spec.rb
closes #1427 
J'enlève des notifications qui n'apportaient pas d'informations utiles et qui ont surtout été utilisé pour vérifier le bon fonctionnement des features en question. 
J'en profite pour préciser l'organisation de l'agent lorsque celui-ci est supprimé ainsi que de ne plus prendre en compte les notifications venant de l'espace de demo.
=> refactor(mattermost): Send less notifications

app/jobs/stats/global_stats/upsert_stat_job.rb, app/jobs/stats/monthly_stats/upsert_stat_job.rb
Ceci est un fix temporaire pour éviter d'avoir à tuer à la main les jobs de stats qui n'arrivent pas à se résoudre.
J'ai essayé de faire ça plus proprement en mettant en place un système de hard_timeout global pour les jobs, inspiré par ce qu'a fait rdv-s, mais j'ai rencontré diverses erreurs que je n'ai pas réussi/pas eu le temps de surmonter. Intéressé de faire du pair programming sur ce point avec l'un de vous deux en rentrant de vacances. 
Pour documenter, la solution de rdv-s ne fonctionne pas car ils utilisent `ActiveJob` et peuvent donc se servir du callback `around_perform`, ce qu'on ne peut pas faire. J'ai donc suivi deux pistes : 
- ajouter le callback dans un server middleware (en suivant [la doc de Sidekiq](https://github.com/sidekiq/sidekiq/wiki/Middleware) + j'ai trouvé …
=> feat(stats): add timeouts to stats jobs

app/javascript/react/pages/UsersUpload.jsx
closes #1500 
Je corrige ici un bug introduit par [cette PR](https://github.com/betagouv/rdv-insertion/pull/1454). À la suite de cette modif, les agents n'avaient plus la possibilité de sélectionner les usagers en masse lors de l'import de ceux-ci. La checkbox du `th`avait disparu. Je la remet ici - @Michaelvilleneuve on pourrait peut-être rajouter un feature test et/ou refactorer ce que j'ai fait.
=> fix(upload): re-add multiple selection checkbox

app/controllers/concerns/users/sortable.rb, app/services/exporters/generate_users_csv.rb, config/locales/models/rdv.fr.yml, config/locales/models/rdv_context.fr.yml, spec/services/exporters/generate_users_csv_spec.rb
Dans cette PR, je réponds à une demande de la Manche : comme je le craignais, le fait de supprimer le statut du `rdv_context` (avec la disparition des informations "invitation en attente de réponse" et "délai dépassé") les a perturbé. Ils nous ont réclamé qu'on les remette. Plutôt que de les "forcer" à faire des croisements compliqués dans leurs tableaux Excel, je remet le statut du `rdv_context` dans une autre colonne.
N.B. : en testant la modif, j'ai eu [ce bug bizarre qu'on ne comprenait pas](https://sentry.incubateur.net/organizations/betagouv/issues/69684/?project=16&query=is%3Aunresolved&referrer=issue-stream) avec @aminedhobb. Visiblement il provient du `order_users` pour `all_users`. J'ai donc remis plus ou moins la requête de tri que l'on faisait avant de la modifier dans [cette …
=> fix(csv): add rdv_context status in users csv export when motif_category

app/views/invitations/invitation_code.html.erb
closes #1513 
Lorsque nous redirigeons vers rdv-solidarites via l'action `invitations#redirect`, nous stockons le token d'invitation dans la session rdv-solidarités et faisons apparaitre l'url sans ce token d'invitation (qui permettrait, s'il était récupéré, d'accéder à tous les motifs normalement réservés aux invitations). Ce mécanisme se trouve [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/60f8758d0bcb5f91e44bbaa4dec78b59807fb765/app/controllers/concerns/token_invitable.rb#L15) dans la codebase rdvs.
Le problème, c'est que quand nous appelons l'action `invitations#redirect` via le formulaire de la page `/invitation`, les headers de la requête n'étaient pas les mêmes que lorsque nous cliquions sur le lien dans le mail ou le sms. Notamment le header …
=> fix(postal): fix invitation code flow

app/controllers/users_organisations_controller.rb
Lorsque le retrait de l'organisation échouait on était quand même redirigé vers la page index ce qui donnait l'impression que l'action avait réussi
=> fix(navigation): do not redirect when error when removing org

app/views/tag_assignations/_form.html.erb, app/views/users/_users_list_tabs.html.erb
Juste 2 petites améliorations : 
- Pas d'icone pour drag n drop s'il y une seule tab
- Un texte explicatif lorsqu'aucun tag n'existe
=> fix(tags/drag n drop): minor changes

app/controllers/configurations_controller.rb, app/javascript/stylesheets/pdf.scss, app/models/organisation.rb, db/migrate/20231109092923_add_messages_configurations_to_all_organisations.rb, db/schema.rb
closes #1523 
Dans cette PR je fais en sorte qu'une organisation ait toujours un record de `messages_configuration` associé. 
Parce que quand on ne persistait pas on avait choisi d'instancier une nouvelle instance de `messages_configuration` avec les valeurs par défaut sur certaines colonnes qui n'étaient pas reflétées à la génération du courrier, ce qui pouvait porter à confusion.
Je fais aussi en sorte de diminuer la largeur max d'un logo car lorsqu'on affichait le logo rdvi uniquement les courriers s'affichaient sur 2 pages.
=> fix(letters): Always create a messages configuration record

app/clients/rdv_solidarites_client.rb, app/models/rdv_solidarites/rdv.rb, app/services/participations/update.rb, app/services/rdv_solidarites_api/update_participation.rb, spec/features/agent_can_update_a_participation_status_spec.rb, spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb, spec/services/participations/update_spec.rb
Suite à https://github.com/betagouv/rdv-solidarites.fr/pull/3857
Nous sommes les seuls à utiliser l'endpoint participations#update pour l'api donc je le met à jour ici avant de le renommer définitivement coté RDVSP.
=> refactor(app): rename rdvs_users to participations

app/jobs/send_convocation_reminders_job.rb, app/models/concerns/rdv_participation_status.rb, app/services/notifications/notify_participation.rb, spec/jobs/send_convocation_reminders_job_spec.rb, spec/services/notifications/notify_participation_spec.rb
Lorsqu'un rdv de convocation était annulé, le reminder de rdv était malgré tout envoyé. Le problème avait été remonté par @Evajuliab [ici](https://mattermost.incubateur.net/betagouv/pl/b3h75rxzkpribps5jumqukixje). Cette PR résout ce problème. J'aurais peut-être pu me contenter de faire un seul des deux fixs mais je me dis que ça ne coûte pas grand chose de s'assurer qu'on ne le fait pas (dans `NotifyParticipation`, cela check aussi pour les invitations)
=> fix(reminders): don't send convocation reminder if the participation is cancelled

app/services/concerns/invitations/sms_content.rb, app/views/mailers/invitation_mailer/atelier_invitation.html.erb, spec/mailers/invitation_mailer_spec.rb, spec/services/invitations/send_sms_spec.rb
Dans certains cas, les invitations envoyées pour des ateliers concernent un atelier unique ; les bénéficiaires n'ont donc pas le choix du créneau. De plus, les ateliers ont a priori toujours un nombre de place limité (par la taille de la salle), et même si ce n'est pas le cas, la phrase à ce sujet n'est pas gênante.
J'essaye donc de prendre en compte ces éléments avec ce changement, afin de rendre le template d'invitation aux ateliers plus générique.
=> feat(invitations): change atelier invitation mailer message

app/controllers/concerns/users/filterable.rb, app/controllers/concerns/users/sortable.rb, app/controllers/users_controller.rb, db/migrate/20231121133009_fill_null_users_organisations_created_at.rb, db/schema.rb, spec/controllers/users_controller_spec.rb
On avait 2 problèmes dans la page "tous les contacts" sur une organisation: 
* Lorsqu'un usager appartenait à plusieurs organisations au niveau du département, on le sélectionnait 2 fois puisque dans la requête on sélectionnait les `users_organisations.created_at` associés et il pouvait y en avoir plusieurs. 
* Les usagers n'apparaissaient pas forcément dans l'ordre d'affectation au département quand ils appartenaient à plusieurs orgas du département
Je fais en sorte de ne plus avoir de doublons et de les avoir dans le bon ordre en modifiant la requête et en ne prenant en compte que la première date d'affectation à une organisation du département. 
J'ajoute également un fichier de migration pour ne pas avoir de date nulle en création de `users_organisations`, ce qui pouvait créer des …
=> fix(ordering): order users correctly when all users displayed

app/javascript/stylesheets/pdf.scss
Le 44 avait un problème, vu avec @SalmaBennani : le mot "RSA" qui apparaissait dans l'objet de la lettre était visible dans la fenêtre de l'enveloppe envoyée au bénéficiaire. Cette PR corrige ce souci. Pour éviter que les courriers passent sur 2 pages, je récupère en sur la bottom-margin entre les signatures et les logos.
=> fix(letters): move down object line

app/models/rdv_solidarites_session/base.rb, app/services/base_service.rb, app/services/rdv_solidarites_api/base.rb
Il semblerait que nous n'utilisions pas `NotImplementedError` de la bonne façon, ce n'est pas fait pour montrer qu'une classe enfant doit implémenter cette méthode (voir par exemple dans [cette article](https://kirillshevch.medium.com/misusing-of-notimplementederror-in-ruby-531dd866f461)).
=> refactor(app): Replace NotImplementedError with NoMethodError

app/controllers/invitations_controller.rb, app/services/concerns/invitations/sms_content.rb, config/routes.rb, spec/controllers/invitations_controller_spec.rb, spec/services/invitations/send_sms_spec.rb
Cette PR permet de raccourcir l'url affichée dans les SMS pour réduire le coût de ceux-ci. 
Concrétement on passe d'une url comme celle-ci : 
`https://www.rdv-insertion.fr/invitations/redirect?uuid=AAAAAAAA`
à 
`rdv-insertion.fr/r/AAAAAAAA`
Ce qui devrait permettre d'économiser 36 caractères par SMS
fix: https://github.com/betagouv/rdv-insertion/issues/654
=> feat(sms): shorten invitation url link

app/controllers/concerns/authenticated_controller_concern.rb, app/controllers/sessions_controller.rb, app/controllers/static_pages_controller.rb
Nous avions une incohérence dans la page d'accueil lorsqu'un agent était en session mais lorsque ses identifiants de sessions sont invalides, notamment suite à [ce changement récent](https://github.com/betagouv/rdv-insertion/commit/e28f275fb842aad9a5e69976240aa17ac7739235): 
Cette PR règle ce problème.
=> fix(session): Fix incoherence when agent session credentials invalid

app/mailers/reply_transfer_mailer.rb, spec/mailers/reply_transfer_mailer_spec.rb
Traite [cette erreur Sentry].
Lorsqu'un usager répondait à un email depuis une boîte mail autre que celle utilisée pour prendre le rendez-vous, le job de transfert de réponse automatique ne fonctionnait pas. Cette PR résout ce problème, en priorisant l'utilisateur lié au rendez-vous ou à l'invitation ; l'email n'est utilisé pour `set_user` que lorsque cette priorité n'est pas réalisable.
=> fix(mailers): set_user correctly if reply comes from another email

app/jobs/application_job.rb, app/jobs/concerns/job_session_concern.rb, app/jobs/create_and_invite_user_job.rb, app/jobs/invite_user_job.rb, app/jobs/trigger_rdv_solidarites_webhooks_job.rb, spec/jobs/create_and_invite_user_job_spec.rb, spec/jobs/invite_user_job_spec.rb, spec/jobs/trigger_rdv_solidarites_webhooks_job_spec.rb
fix [ce bug Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/78219/?alert_rule_id=9&alert_timestamp=1702886472245&alert_type=email&environment=production&project=16&referrer=alert_email)
Les jobs étant executés en asychrone, le `Current.agent` n'y était pas défini. Je résous ce problème (avec une petite refacto de l'endroit où l'on crée la session pour être plus DRY
=> fix(jobs): set current agent in jobs

app/services/exporters/generate_users_csv.rb, spec/services/exporters/generate_users_csv_spec.rb
Cette PR permet d'afficher le statut de la participation du user au RDV plutôt que le statut du RDV en lui même (qui peut changer en fonction des autres users). 
closes #1528
=> fix(csv): show participation status instead of rdv status

app/jobs/stats/global_stats/upsert_stat_job.rb, app/models/stat.rb, app/services/stats/global_stats/compute.rb, spec/models/stat_spec.rb
Du coup dans cette PR j'ai augmenté le délai de timeout pour éviter qu'il s'arrête à 10 minutes (en local avec un jeu de donnée de production je dépasse ce temps). 
Sinon niveau code l'amélioration magique a consisté à enlever un `where(user_id: user_sample)` qui générait un WHERE IN, ce qui était très couteux VS le left outer joins. J'ai également gardé en mémoire certaines chose comme les id de users archivés. 
Malgré ces améliorations, le temps de traitement du job ne va malgré tout faire qu'augmenter. 
En effet, il reste des choses que l'on calcule avec des gros `.find_each` et qui sont voués à ne plus fonctionner dans les semaines / mois à venir. 
Par exemple, ce code : 
```ruby
@rdv_contexts.find_each do |rdv_context|
cumulated_invitation_delays += …
```
=> fix(stats): allow stats to run by removing in memory handling of conditions

config/routes.rb
Ceci est un fix temporaire du bug empêchant l'assignation d'un référent en production. 
Je n'ai pas encore trouvé la source du problème mais j'imagine que la partie React n'a pas encore été adaptée à la structure des routes. 
J'ouvrirai une autre PR pour corriger ça une fois compris le pourquoi du problème
Fix: https://github.com/betagouv/rdv-insertion/issues/1622
=> fix(routes): re-enable deleted routes

app/controllers/referent_assignations_controller.rb, config/routes.rb
After re-enabling the deleted route, requests are now successful locally, but requests that were already failing in production are now failing because the Agent seems to be missing. 
Error went from "The resource could not be found" to "L'agent n'a pas été trouvé"
I suspect that the Current structure is in some cases not properly updated when using session coming from the React App. 
This may be causing the allowed agents not to resolve properly due to trying to find agent on a nil department.
=> fix(referents): assignations routing using incorrect param

app/controllers/concerns/filter_rdv_solidarites_webhooks_concern.rb, app/controllers/inclusion_connect_controller.rb, app/models/rdv_solidarites_session/with_shared_secret.rb
Il est recommandé d'utiliser `secure_compare` plutôt qu'une simple vérification d'égalité, notamment pour se prémunir des "timing attacks". 
Je l'utilise à chaque fois que l'on fait des vérifications sur des hash cryptographiques.
=> fix(app): Use secure_compare for hash verifications

app/controllers/participations_controller.rb
Cette PR affiche désormais le message d'erreur complet du service plutôt qu'un message d'erreur générique. 
Cela permettra d'éviter les confusions comme celle-ci https://github.com/betagouv/rdv-insertion/issues/1621 où l'erreur était en fait une erreur pouvant être corrigée par l'agent `Erreur RDV-Solidarités: lieu doit être un lieu ouvert de l’organisation, ou un lieu ponctuel.`
Fix #1621
=> fix(status update): clearer error feedback when participation update call fails

spec/features/agent_can_update_a_participation_status_spec.rb
Cette PR vérifie le status de la participation plutôt que du rdv_contexte
=> fix(flaky): participation status update

app/jobs/stats/monthly_stats/upsert_stat_job.rb
C'est moche mais en l'état j'applique désormais juste le même timeout pour les jobs monthly que pour les jobs globaux. 
Cela fixera temporairement le job de stats
=> fix(stats): set a similar timeout between all stats jobs

app/controllers/api/v1/users_controller.rb, app/controllers/configurations_controller.rb, app/controllers/invitations_controller.rb, app/controllers/previews/invitations_controller.rb, app/javascript/controllers/invitations_checkbox_form_controller.js, app/javascript/react/actions/inviteUser.js, app/javascript/react/components/InvitationBlock.jsx, app/javascript/react/lib/createInvitationLetter.js, app/javascript/react/lib/handleUserInvitation.js, app/javascript/react/models/User.js, app/jobs/create_and_invite_user_job.rb, app/models/configuration.rb, app/services/invite_user.rb, app/views/configurations/_configuration_form.html.erb, app/views/configurations/show.html.erb, app/views/invitations/_checkbox_form.html.erb, config/locales/models/configuration.fr.yml, db/migrate/20240104105413_add_phone_number_to_configuration.rb, db/schema.rb, spec/controllers/invitations_controller_spec.rb, spec/factories/configuration.rb, spec/jobs/create_and_invite_user_job_spec.rb, spec/requests/api/v1/users_request_spec.rb, spec/services/invite_user_spec.rb
Cette PR permet d'ajouter un numéro de téléphone par configuration. 
Une fois ajoutée, celle-ci est automatiquement envoyée comme le help_phone_number des invitations. 
Si ce nouveau champ n'est pas rempli, un fallback est automatiquement fait vers le numéro de téléphone de l'organisation.
Fix https://github.com/betagouv/rdv-insertion/issues/1585
=> feat(configurations): add ability to set a custom phone number

app/views/orientations/_orientation.html.erb, app/views/orientations/_orientation_form.html.erb, app/views/users/_user_tabs.html.erb, config/locales/models/orientation.fr.yml, spec/features/agent_can_add_user_orientations_spec.rb
Je fais quelques changements ici suite à #1607 :  
* Je renomme l'onglet "Suivi" en "Rendez-vous"
* Je parle de "Référent unique" et non plus d'"Agent référent"
* Je laisse la possibilité de renseigner une date de fin postérieure à la date du jour
=> feat(parcours): Change new parcours wording

app/views/users/_archiving_button.html.erb, app/views/users/_user_page_header.html.erb, app/views/users/edit.html.erb
Lié à #1631
On avait un problème sur les actions `rdv_contexts#index` et `parcours#show`, vu qu'on n'instanciait pas de variable `@archive` dans ces controllers.
Plutôt que de l'instancier dans ces controllers (où l'archive ne sert qu'à changer les CTA dans la vue) j'utilise plutôt la méthode `@user.archive_for(@department.id)` pour assigner la locale envoyée dans la partial `archiving_button`.
=> fix(archive): Use correct CTA when user archived

spec/features/agent_can_update_a_participation_status_spec.rb
Afin d'éviter de checker la page entière qui contenait la string attendue de toute façon, je check désormais le contenu du bouton d'update qui lui se doit de contenir réellement la string associé au statut mis à jour.
=> fix(flaky): participation update status

app/controllers/concerns/users/filterable.rb, app/services/invitations/assign_link_and_token.rb, app/services/invitations/save_and_send.rb, spec/services/invitations/assign_link_and_token_spec.rb, spec/services/invitations/save_and_send_spec.rb
Dans cette PR j'essaie d'améliorer le temps de réponse de deux requêtes: 
* Celle qui invite un usager. Jusqu'à présent à chaque invitation on lockait l'envoi d'invitations pour l'usager en question. On l'avait fait parce qu'il y avait un risque de race condition lors de l'assignation d'un token rdv-solidarités, où on pouvait se retrouver avec des invitations envoyés avec un token invalidé.  Mais depuis #1214 , l'endpoint appelé sur rdv-solidarités est idempotent et n'a plus d'influence sur la validité de l'invitation. J'enlève donc ce lock.
* Celle qui permet de filtrer les usagers par date d'invitations. J'ai eu un timeout en testant en prod. J'ai remarqué qu'il y avait un N+1 qui se déclenchait lors de ces filtres, je l'enlève ici voir si ça résout le problème
J'en profite pour …
=> feat(ops): Try to improve performance

.gitignore
Depuis que je suis passé sur vscode, j'ai une configuration spécifique qui se trouve dans le dossier `.vscode/`.
J'ajoute ce dossier dans le gitignore pour éviter d'avoir à le supprimer à chaque fois que je veux que la branche soit clean pour déployer
=> feat(config): Add vscode to gitignore

app/controllers/inclusion_connect_controller.rb
Depuis #1617 on a cette erreur sur sentry qui est présente quand le `state` n'est pas présent lors de l'authentification via inclusion connect: https://sentry.incubateur.net/organizations/betagouv/issues/80107/?project=16&query=&referrer=issue-stream&statsPeriod=14d.
@Holist je fais un petit fix ici pour ne plus avoir cette erreur (et que le message affiché à l'usager soit compréhensible), tu me diras si c'est bon.
=> fix(ic): Handle invalid state correctly

app/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job_spec.rb
Dans #1618 j'ai enlevé l'assignation du `rdv_solidarites_agent_role_id` pensant qu'elle n'était plus utilisée.
Or elle est toujours utilisée pour assigner l'id RDVS lorsqu'on crée le record d'`AgentRole` depuis rdv-i [ici](https://github.com/betagouv/rdv-insertion/blob/321fa75f9c5373669e5e55d3e574689c29983661/app/services/organisations/create.rb#L39) lorsqu'on rappatrie une orga rdv-s.
Si on ne le met pas on se retrouve avec ces erreurs: https://sentry.incubateur.net/organizations/betagouv/issues/80310/?project=16&query=is%3Aunresolved&referrer=issue-stream
=> fix(jobs): Assign rdv_solidarites_agent_role_id for agent roles

app/controllers/concerns/users/filterable.rb, app/views/users/_archived_users_table.html.erb
close : https://github.com/betagouv/rdv-insertion/issues/1652
Le changement dans la méthode `invitations_belonging_to_rdv_contexts` fait gagner environ 70% de perfs.
Les changements dans `users_first_invitations` et `users_last_invitations` encore 80%.
Ce qui fait 94% de gain de perf 🚀 
Je ne sais pas si on souhaite vraiment garder les appels aux méthodes `first_sent_invitation` et `last_sent_invitation` du concern `Invitable` dans les méthodes `users_first_invitations` et `users_last_invitations` de `Filterable`
Je ne les utilises plus dans ma proposition. 
Si nécessaire on pourrait imaginer une refacto plus conséquente pour continuer à les utiliser.
On peut aussi décider de ne pas toucher aux methodes `users_first_invitations` et `users_last_invitations` en enlevant simplement le …
=> fix(perfs): improve performances for invitation dates filtering

app/helpers/stats_helper.rb, app/services/stats/compute_average_time_between_invitation_and_rdv_in_days.rb, app/services/stats/monthly_stats/upsert_stat.rb, app/views/stats/_stats.html.erb, spec/services/stats/compute_average_time_between_invitation_and_rdv_in_days_spec.rb, spec/services/stats/monthly_stats/upsert_stat_spec.rb
Cette PR permet de corriger 2 problèmes liées au stats : 
- Le mois en cours était pris en compte et donnait des résultats biaisant la lecture des courbes :
- Les insertion manuelles de participations / rattrapage de données faite après les dates originales par les agents pouvaient fausser la lecture du graphique de délai moyen d'invitation en mettant des valeurs négatives. 
Afin de corriger ça on ne prend désormais plus en compte les valeurs négatives dans le calcul. 
Fix https://github.com/betagouv/rdv-insertion/issues/1644
=> fix(stats): minor issues

app/javascript/react/components/EnrichWithContactFile.jsx, app/javascript/react/models/Users.jsx, app/javascript/react/pages/UsersUpload.jsx, spec/features/agent_can_upload_user_list_spec.rb
Lié à #1517 . 
- Je change le wording sur la page upload pour parler d'usagers et non plus de demandeurs
- Je change le lien cassé vers le nouveau lien mis à disposition dans [ce commentaire](https://github.com/betagouv/rdv-insertion/issues/1517#issuecomment-1898679356)
- J'enlève l'accent en trop dans "Séléction"
=> fix(upload): Change wording and link

app/views/mailers/reply_transfer_mailer/forward_notification_reply_to_organisation.html.erb, spec/mailers/reply_transfer_mailer_spec.rb
fix de [cette erreur Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/82231/?query=is%3Aunresolved+TransferEmailReplyJob&referrer=issue-stream&statsPeriod=14d)
=> fix(mailers): conditional lieu display for transfer email reply job

app/models/agent.rb, spec/controllers/organisations_controller_spec.rb, spec/factories/agent.rb, spec/features/administrate/super_admin_can_manage_departments_spec.rb, spec/features/administrate/super_admin_can_manage_motif_categories_spec.rb, spec/features/administrate/super_admin_can_manage_organisations_spec.rb, spec/features/administrate/super_admin_can_manage_templates_spec.rb, spec/features/administrate/super_admin_can_manage_users_spec.rb, spec/models/agent_spec.rb
Vu qu'on utilise maintenant pleinement la fonctionnalité de super_admin, je réduis la possibilité que qu'un agent soit marqué comme `super_admin` par inadvertance en empêchant l'update d'un agent comme super admin via `agent#update` ou `agent#save`. 
On devra explicitement utiliser `agent#update_column` en console lorsqu'on ajoutera un superadmin.
=> feat(security): ensure super admin cannot be updated

app/services/stats/compute_average_time_between_invitation_and_rdv_in_days.rb, spec/services/stats/compute_average_time_between_invitation_and_rdv_in_days_spec.rb
Depuis la dernière mise à jour des stats il est devenu possible d'avoir des mois dans lesquelles aucune valeur n'est présente dans `ComputeAverageTimeBetweenInvitationAndRdvInDays`, cela engendrait une division de `0.0 / 0.0` qui donnait un NaN, sur lequel appeler un `.round` engendre l'erreur ci-dessous.  
Pour prévenir ce cas on renvoi 0.0 si jamais aucune valeur n'est présente
Corrige https://sentry.incubateur.net/organizations/betagouv/issues/82504/?project=16&query=is%3Aunresolved&referrer=issue-stream
=> fix: stats NaN issue

config/schedule.yml
Petite coquille dans le nom du job rgpd dans le schedule file. Cette PR résout ce problème
=> fix(rgpd): destroy job name in schedule file

app/controllers/concerns/super_admins/redirect_and_render_concern.rb, app/controllers/super_admins/motif_categories_controller.rb, app/controllers/super_admins/organisations_controller.rb, app/controllers/super_admins/users_controller.rb
Lorsqu'une erreur n'était pas liée au modèle, elle n'était pas affichée sur le formulaire superadmin de new ou edit. Je fais en sorte que ce soit le cas.
=> fix(admin): display services errors in super admin

app/helpers/stats_helper.rb, app/models/stat.rb, app/services/stats/global_stats/compute.rb, app/services/stats/monthly_stats/compute_for_focused_month.rb, app/views/stats/_stats.html.erb, db/migrate/20240124101508_add_columns_to_stats.rb, db/schema.rb, spec/services/stats/global_stats/compute_spec.rb, spec/services/stats/monthly_stats/compute_for_focused_month_spec.rb
Dans cette PR j'ajoute la nouvelle statistique demandée par le GIP : le nombre d'utilisateurs mis en relation via l'outil
Cela correspond au nombre d'utilisateurs ayant eu au moins un rendez-vous "honoré" ou "pris"
https://github.com/betagouv/rdv-insertion/issues/1565
=> feat(stats): add # of users with Rdv taken or seen stat

config/puma.rb
Je fais en sorte ici de pouvoir ajuster le nombre de worker puma sur notre appli via la variable d'env `WEB_CONCURRENCY`.
=> feat(ops): Enable number of puma workers configuration

app/controllers/rdv_contexts_controller.rb, app/services/invite_user.rb, app/services/rdv_contexts/save.rb, spec/services/invite_user_spec.rb, spec/services/rdv_contexts/save_spec.rb
En testant en demo je me suis rendu compte que les erreurs prises en compte dans #1699 faisaient référence à des "utilisateurs" et non des usagers . 
Je change ça ici et j'en profite pour renommer le service `RdvContexts::Create` en `RdvContexts::Save`.
=> fix(view): Rewrite error messages on user invitation

app/javascript/react/components/FileHandler.jsx, app/javascript/react/lib/uploadFile.js, app/javascript/react/pages/UsersUpload.jsx, app/javascript/stylesheets/components/_button.scss, spec/features/agent_can_archive_and_unarchive_user_spec.rb, spec/features/agent_can_create_carnet_spec.rb, spec/features/agent_can_edit_uploaded_user_list_spec.rb, spec/features/agent_can_update_contacts_info_spec.rb, spec/features/agent_can_upload_user_list_spec.rb
Lié à #1686 
Je réaligne le CTA "Choisir un fichier" en mettant un bouton identique aux CTA sur le reste de l'appli.
J'en profite pour corriger un bug: lorsque le fichier xls d'entrée n'avaient pas les bonnes colonnes, la modale d'erreur s'affichait mais lorsqu'on la fermait on voyait toujours le texte "Récupération des informations, merci de patienter". Ce n'est plus le cas.
=> fix(view): Align file upload button

app/controllers/tag_assignations_controller.rb, app/controllers/users_controller.rb, app/policies/tag_policy.rb
Ajout d'une policy sur les tags pour n'afficher que ceux des organisations de l'agent connecté. 
Correction aussi d'un problème de distinct, la liste des tags affichés n'étaient pas dé-dupliquée. 
J'ai vérifié en prod il n'y a pas de doublon dans la table Tag c'était bien juste un distinct à ajouter pour la jointure
Fix https://github.com/betagouv/rdv-insertion/issues/1655
Fix https://github.com/betagouv/rdv-insertion/issues/1658
=> fix(tags): add policy restriction

app/controllers/asset_redirections_controller.rb, app/helpers/application_helper.rb, app/lib/asset_helper.rb, app/models/logo.rb, config/puma.rb, config/routes.rb
Suite au retrait de webpacker, nos assets ne sont plus servies via la même route. Ça a pour conséquences que les logos ne sont plus affichés correctement sur les emails envoyés avant le retrait de webpacker.
Je fais en sorte ici de continuer à bien les afficher en redirigeant vers la nouvelle image lorsqu'on requête l'ancienne route.
=> fix(assets): Redirect old logos urls

app/models/participation.rb, app/models/rdv.rb, app/policies/participation_policy.rb, app/policies/rdv_policy.rb, app/services/exporters/generate_users_csv.rb, spec/services/exporters/generate_users_csv_spec.rb
Ce fix permet d'afficher la date réelle d'orientation de l'utilisateur. 
Elle correspond désormais à la date du premier rendez-vous honoré d'une catégorie d'orientation, scopé par les organisations auquel l'agent a accès. 
Pour info j'ai voulu enlever le `delegate` pour garder uniquement le `has_one` mais ce n'est pas possible car `delegate` gère le chaining de delegate différemment et cela causait des erreurs à cause notamment des delegate présents dans `app/models/concerns/templatable.rb` 
fix #1702
=> fix(csv): display actual orientation date in user csv

app/views/users/_users_table_for_motif_category.html.erb
Lié à #1747 . Lorsque l'on convoque au niveau du département, l'organisation qui est prise en compte n'est pas forcément celle de l'usager. Cette PR règle ça en prenant toujours une organisation à laquelle appartient l'usager.
=> fix(convocation): Convene on user organisation

app/controllers/concerns/turbo_stream_concern.rb, app/controllers/users_controller.rb, app/views/common/_flash.html.erb, app/views/layouts/application.html.erb
Lié à #1737 . 
Je fais en sorte que les messages d'erreurs ne s'empilent pas mais qu'ils soient remplacés à chaque requête. Pour ça j'introduis une méthode `turbo_stream_replace_flash_message` analogue à `turbo_stream_prepend_flash_message` dans le `TurboStreamConcern` que j'utilise lorsqu'on renvoie une erreur à la création d'usager.
=> fix(view): Do not repeat error flash message

app/views/users/_users_list_header.html.erb
On ne veut pas afficher la phrase "filter par :" lorsqu'il n'y a pas de tags renseignés ou lorsqu'on ne peut pas filtrer par intervention nécessaire
=> fix(view): conditionally display filter sentence

app/javascript/stylesheets/components/_color.scss, app/services/invitations/save_and_send.rb, spec/features/agent_can_invite_users_from_index_page_spec.rb, spec/services/invitations/save_and_send_spec.rb
closes #1714 
Dans cette PR, je rajoute un lien vers notre guide dans le message d'erreur des créneaux. J'en profite aussi pour améliorer sa lisibilité (en ajoutant des sauts de ligne + en mettant l'info principale du message dès le début du message)
Avant : 
Après :
=> feat(errors): better creneaux error message

app/controllers/referent_assignations_controller.rb, app/controllers/users_organisations_controller.rb, spec/controllers/referent_assignations_controller_spec.rb, spec/controllers/users_organisations_controller_spec.rb
closes #1791 
Dans cette PR, je fais en sorte que la synchro avec rdvs soit vérifiée à la suppression d'un référent ou d'une orga.
N.B. : pas besoin de l'ajouter pour l'ajout d'une orga, c'est déjà le cas dans le service `Save`
=> fix(sync): verify user sync with rdvs when its needed

app/models/orientation.rb, spec/models/orientation_spec.rb
Cette PR permet d'enregistrer la date du jour comme date de début de l'orientation. 
Closes https://github.com/betagouv/rdv-insertion/issues/1733
=> feat(orientation): allow today's date

app/javascript/controllers/parcours_documents_controller.js, app/views/parcours_documents/_document_form.html.erb, spec/features/agent_can_upload_documents_for_users_spec.rb
Dans cette PR j'enlève la combinaison de bouton + champ à remplir pour n'avoir qu'un seul bouton permettant de sélectionner et uploader directement le fichier :
https://github.com/betagouv/rdv-insertion/assets/4990201/4ce2b970-9cff-49dd-bf51-557fa9e6d311
Closes https://github.com/betagouv/rdv-insertion/issues/1713
=> feat(upload): simplified file upload

app/jobs/send_periodic_invite_job.rb, app/jobs/send_periodic_invites_job.rb, spec/jobs/send_periodic_invite_job_spec.rb
Lié à #1785 . 
J'évite les doublons d'envoi d'invitations pour les invitations périodiques.
=> fix(cron): Prevent duplicated periodic invitations

app/javascript/stylesheets/components/_flash.scss
Lié à https://github.com/betagouv/rdv-insertion/issues/1784
Je double le temps d'apparition des messages flash de succès ou d'info avant qu'ils ne disparaissent.
=> fix(view): Change flash fading delay

app/controllers/users/parcours_documents_controller.rb, app/policies/parcours_document_policy.rb, app/views/parcours_documents/_document.html.erb, app/views/parcours_documents/_document_form.html.erb, app/views/parcours_documents/_documents_list.html.erb, config/application.rb, config/routes.rb
J'ai du coup bloqué les routes de bases, rajouté une méthode show dans le controller parcours_document avec une vérification de policy sur le fichier. J'ai également corrigé un soucis de marge pour avoir un rendu cohérent avec ou sans document : 
Fix https://github.com/betagouv/rdv-insertion/issues/1827
=> fix(documents): security issue documents url

app/models/user.rb, app/services/users/sync_with_rdv_solidarites.rb, db/migrate/20240226140143_add_old_rdv_solidarites_user_id_to_users.rb, db/schema.rb
Lorsqu'un usager est soft deleté sur rdvi, on n'enlève pas son `rdv_solidarites_user_id`. Or il se peut que l'usager ne soit pas supprimé côté rdvsp, notamment si l'usager en question appartient à des organisations qui n'ont pas pour verticale `rdv_insertion`. 
Ça crée un problème si on veut recréer l'usager, parce qu'on fera le lien avec l'usager existant sur rdvsp mais on détectera qu'on a déjà un record avec cet id rdv_solidarites en DB (dans la méthode `handle_email_taken_error` du service `User::SyncWithRdvSolidarites`) et ça va empêcher la création de l'usager.
Je mets le `rdv_solidarites_user_id` à `nil` lorsque l'usager est soft deleté et j'ajoute une colonne `old_rdv_solidarites_user_id` pour quand même faire le lien avec le record côté rdvsp. 
Une amélioration possible serait de …
=> feat(app): Handle better deleted users 

app/javascript/controllers/autocomplete_controller.js
On ferme la box d'autocomplete des tags lorsque le form parent est envoyé
Fix https://github.com/betagouv/rdv-insertion/issues/1773
=> fix(tags): self close autocomplete when submitted

app/javascript/stylesheets/components/_title.scss, app/views/users/_users_list_header.html.erb
close https://github.com/betagouv/rdv-insertion/issues/1096
Le retour à la ligne fait 'perdre' un tout petit peu de hauteur à l'interface mais le cas est je pense suffisamment rare pour que cela reste très marginal. Une autre solution serait de réduire la police après un certains breakpoint mais cela ne réglera pas le problème si le nom de l'organisation est encore plus long.
Avant : 
Après :
=> ux(user_index): ajust css for long organisations name in user index and centered it.

app/controllers/users_organisations_controller.rb, app/views/mailers/reply_transfer_mailer/forward_invitation_reply_to_organisation.html.erb, app/views/mailers/reply_transfer_mailer/forward_notification_reply_to_organisation.html.erb, app/views/mailers/reply_transfer_mailer/forward_to_default_mailbox.html.erb, app/views/organisations/user_added_notifications/_form.html.erb, app/views/users/index.html.erb, app/views/users_organisations/_users_organisation.html.erb, spec/controllers/users_organisations_controller_spec.rb, spec/features/agent_can_add_or_remove_user_from_organisations_spec.rb, spec/mailers/reply_transfer_mailer_spec.rb
On enlève cette guard clause de redirection qui n'est plus légitime puisque les rdv_contexts ne sont pas affichés ici.
fix https://github.com/betagouv/rdv-insertion/issues/1768
=> fix(user): prevent redirect when adding user at department level

app/jobs/notify_unavailable_creneau_job.rb, app/models/concerns/user/address.rb, app/services/invitations/verify_organisation_creneaux_availability.rb, app/views/mailers/organisation_mailer/creneau_unavailable.html.erb, spec/services/invitations/verify_organisation_creneaux_availability_spec.rb
close https://github.com/betagouv/rdv-insertion/issues/1779
On utilise les codes postaux des adresses des usagers pour remonter les alertes de créneaux indisponibles plutôt que le code fourni par l'api (code insee) qui ne parle pas aux agents.
=> fix(creneaux_availability): use zip_codes instead of city_codes (insee)

app/controllers/csv_exports_controller.rb, app/controllers/users/parcours_documents_controller.rb, app/views/mailers/csv_export_mailer/notify_csv_export.html.erb, app/views/parcours_documents/_document.html.erb, spec/features/agent_can_download_csv_from_index_page_spec.rb
Afin de sécuriser un peu plus les URLs des documents et exports CSV, je met en place des IDs signés sans expiration pour les exports (déjà restreints via le expired? du model) et avec expiration pour l'index des documents de parcours. 
Pour l'instant je continue à supporter les IDs non signés pour les exports CSV car la feature est en prod et il doit donc se passer au moins 48 heures entre le déploiement de la feature et l'arrêt du support des IDs non signés.
=> feat(upload): signed_ids for documents

app/services/retrieve_inclusion_connect_agent_infos.rb, db/migrate/20240312170449_add_agents_inclusion_connect_open_id_sub.rb, db/schema.rb, spec/controllers/inclusion_connect_controller_spec.rb, spec/services/retrieve_inclusion_connect_agent_infos_spec.rb
close : https://github.com/betagouv/rdv-insertion/issues/1770
Concernant la mise à jour de l'agent dans RDVSP depuis chez nous et l'ouverture d'un endpoint dédié que tu proposes dans le ticket @aminedhobb je pense qu'en terme de délais on sera trop juste. 
La mise à jour des agents FT démarre le 15 mars et se termine le 12 avril. ([planning](https://mattermost.incubateur.net/betagouv/pl/1cqwhktycjb3mcuwxk1imh7boe))
Je propose cette PR qui considère les 2 domaines `pole-emploi.fr` et `francetravail.fr` pour la recherche d'un agent. 
Et je propose que l'on mette à jour manuellement tout les agents restants à la main après le 12 avril dans notre base. Les agents qui se seront connectés sur RDVSP seront déjà à jour chez nous via les webhook car j'ai implémenté l'[update des infos agents à la …
=> feat(inclusion_connect): use sub for identifying inclusion connected agents and handle francetravail domain migration

app/controllers/concerns/agents/sign_in.rb
Je change le nom de la méthode `new_rdv_solidarites_credentials` en `rdv_solidarites_credentials_from_request_headers` qui est plus descriptif et approprié
=> refactor(naming): Sign in naming change

app/javascript/controllers/user_link_controller.js, app/javascript/stylesheets/components/_form.scss, app/javascript/stylesheets/pages/_users.scss, app/views/invitations/_checkbox_form.html.erb, app/views/users/_all_users_table.html.erb, app/views/users/_archived_users_table.html.erb, app/views/users/_users_table_for_motif_category.html.erb
closes #1777 
Dans cette PR, je fais en sorte que toute la ligne d'un usager sur les pages index soit cliquable pour se rendre sur son profil (et plus seulement le bouton "gérer").
Finalement @samanthaauffret je trouve que ce n'est pas gênant pour les actions que toute la ligne soit cliquable, avec le curseur qui change je trouve ça assez intuitif de voir si on est sur le bouton ou non. Pour faciliter le clic pour générer les invitations, j'ai légèrement agrandi la checkbox qu'il faut cliquer pour envoyer une invitation.
=> feat(index): make user line clickable

app/models/agent.rb, spec/factories/agent.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_agent_job_spec.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job_spec.rb, spec/models/agent_spec.rb, spec/services/upsert_record_spec.rb
J'ajoute ici le champ `inclusion_connect_open_id_sub` dans les attributs rdvsp des agents, celui ci sert à l'authentification (clé unique) dans inclusion connect.
Le code est déjà implémenté dans rdvps pour que l'on puisse recevoir le nouveau champ.
J'ai ajouté quelques tests pour être sur que tout est ok.
=> feat(agent_rdvsp_attributes): add inclusion_connect_open_id_sub to rdvsp agents attributes for webhooks

app/jobs/designate_on_watch_developer_job.rb, app/jobs/monitor_webhook_activity_job.rb, app/jobs/send_convocation_reminders_job.rb, app/jobs/send_creneau_availability_alert_job.rb, app/jobs/send_invitation_reminders_job.rb, app/jobs/send_periodic_invites_job.rb, config/initializers/sidekiq.rb, config/schedule.yml
Cette PR permet de ne plus avoir à déclarer de guard clause pour éviter de run le job dans l'environment dans lequel il est lancé. De cette façon, les jobs ne seront carrément pas scheduled du tout. 
Je trouve l'idée intéressante mais j'aime pas mettre du code non testé unitairement dans les initializers. 
Pour ceux qui feront la review : je vous invite à run le code en local idéalement avec plusieurs envs histoire qu'on soit serein sur son fonctionnement. 
Fix https://github.com/betagouv/rdv-insertion/issues/1743
=> feat(jobs): avoid having to declare environment guard clause in jobs

app/views/parcours_documents/_document_date_form.html.erb, spec/features/agent_can_upload_documents_for_users_spec.rb
Je corrige le bug vu en retro qui permet à n'importe quel agent de voir le bouton d'édition de la date d'un document.
=> fix(documents): prevent non owners from editing document date

app/javascript/controllers/parcours_documents_controller.js, app/views/parcours_documents/_document_form.html.erb
Cette PR permet d'éviter d'envoyer des gros documents avec un guard clause front (celle du back reste évidemment présente). 
Cela permettra de bloquer directement les gros fichiers sans même les process sur le réseau 
Fix https://github.com/betagouv/rdv-insertion/issues/1823
=> fix(upload): prevent processing big files

app/models/stat.rb, app/services/stats/compute_average_time_between_invitation_and_rdv_in_days.rb, app/services/stats/global_stats/compute.rb, app/services/stats/monthly_stats/compute_for_focused_month.rb, spec/models/stat_spec.rb, spec/services/stats/compute_average_time_between_invitation_and_rdv_in_days_spec.rb, spec/services/stats/global_stats/compute_spec.rb, spec/services/stats/monthly_stats/compute_for_focused_month_spec.rb
Dans cette PR je change le mode de calcul de la stat `ComputeAverageTimeBetweenInvitationAndRdvInDays` pour le faire en pur SQL. 
La différence est monumentale car on s'évite une N+1 ce qui nous fera au total gagner plusieurs minutes de calcul pour l'ensemble des stats.
Pour info on pourrait faire encore mieux car il est inutile d'itérer sur l'ensemble des mois pour récuperer le résultat, on pourrait tout faire en une seule requête comme effectué ici https://rdv-service-public-metabase.osc-secnum-fr1.scalingo.io/question/74-delai-entre-invitation-et-participation-groupe-par-mois
Si on veut faire ça il faudra revoir l'ensemble des stats pour changer la façon de les calculer. 
Quoi qu'il en soit cela devrait déjà énormément aider !
=> feat(stats): better way to compute average time between invitation and rdv

app/controllers/referent_assignations_controller.rb, app/javascript/react/components/user/CreationCell.jsx, app/javascript/react/components/user/ReferentAssignationCell.jsx, app/javascript/react/components/users/BatchActionsButtons.jsx, app/javascript/react/lib/handleArchiveDelete.js, app/javascript/react/lib/handleReferentAssignation.js, app/javascript/react/models/User.js, app/javascript/stylesheets/components/_dropdown.scss, spec/features/agent_can_invite_users_by_batch_from_index_spec.rb, spec/features/agent_can_upload_user_list_spec.rb
closes #1463 
📋 Dans cette PR, je permet l'assignation en masse de référents depuis la page `upload` ou depuis la page `batch_actions` des non-invités.
Le fonctionnement est similaire à celui des invitations en masse : si l'usager n'est pas créé, on tente de le créer avant de lancer l'action, sinon, si l'usager n'est pas déjà assigné à ce référent, on lance l'assignation. Les erreurs sont gérées de la même manière que les autres batch_actions.
\
\
🎉 Je profite de cette PR pour fix trois petites choses :
- on ne pouvait fermer la dropdown des batchActions uniquement en recliquant sur le bouton ou la dropdown ; désormais n'importe quel click sur la page la referme
- la largeur de la dropdown était un peu étroite, elle est désormais égale à celle du bouton
- l'action en masse de création de …
=> feat(batch_actions): mass assign referents

app/controllers/inclusion_connect_controller.rb, app/services/retrieve_inclusion_connect_agent_infos.rb, spec/controllers/inclusion_connect_controller_spec.rb
Close https://github.com/betagouv/rdv-insertion/issues/1005
C'est l'équivalent de ce qui a été fait pour rdvsp ici https://github.com/betagouv/rdv-service-public/pull/4195
On affiche un message plus compréhensif aux agents.
Je vais ignorer l'erreur dans sentry "Agent doesn't exist in rdv-insertion" sauf gros volume (>50/jour) comme j'ai fait pour RDVSP.
=> fix(inclusion_connect): better message for agent when inclusion connect email doesnt exist in rdvi/rdvsp

app/services/invitations/validate.rb, spec/features/agent_can_invite_users_from_index_page_spec.rb, spec/services/invitations/validate_spec.rb
closes #1889 
Pour éviter que deux invitations envoyées à quelques minutes d'écart avec un rdv pris par l'utilisateur entre les deux bloque le statut d'un `rdv_context` sur `Invitation en attente de réponse`, je bloque l'envoi d'invitation si un rdv avec un statut `unknown` (donc à venir) a été pris le jour même. L'erreur remontée ressemble à la capture ci-dessous ; l'agent pourra ensuite facilement vérifier en consultant la show de l'usager si tout est en ordre.
=> fix(invitations): block invitations when rdv pending taken today

app/controllers/concerns/users/sortable.rb, app/javascript/controllers/index_table_sorting_controller.js, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/components/_icon.scss, app/javascript/stylesheets/components/_table.scss, app/views/users/_all_users_table.html.erb, app/views/users/_archived_users_table.html.erb, app/views/users/_users_table_for_motif_category.html.erb, spec/features/agent_can_sort_users_on_index_page_spec.rb, spec/rails_helper.rb, spec/support/sorting_helper.rb
closes #1836
J'ai privilégié une implémentation avec reload de la page au moment du tri afin que les params soient présents dans l'url du navigateur, ce qui permet de les "mémorizer" lorsque l'on se rend sur une fiche bénéficiaire et que l'on utilise le bouton "retour au suivi", par exemple.
=> feat(index): allow table sorting by name on index

app/services/invitations/validate.rb, spec/services/invitations/validate_spec.rb
Corrige et améliore [cette PR](https://github.com/betagouv/rdv-insertion/pull/1902), à la suite d'une remarque d'@aminedhobb 
Bloquer l'envoi d'invit quand un rdv a été créé le même jour peut poser problème, car le rdv peut avoir été créé un jour précédent, et/ou son statut peut être mis à jour sans être en lien avec le bénéficiaire directement.
Nous avons donc décidé de nous baser plutôt sur la participation, et d'élargir le blocage à toutes les participations `pending` (donc `unknown` + dans le futur).
=> fix(invitations): always block when participation pending in rdv_context

app/helpers/users_helper.rb, app/javascript/stylesheets/components/_index_filters.scss, app/views/creation_dates_filterings/new.html.erb, app/views/invitation_dates_filterings/new.html.erb, app/views/users/_filter_by_creation_dates_button.html.erb, app/views/users/_filter_by_invitations_dates_button.html.erb, app/views/users/_users_list_header.html.erb
Cette PR améliore l'UX de l'état actif des filtres en affichant l'information plus clairement. 
Je me suis permis quelques petits améliorations de wording par rapport à la maquette, notamment sur le filtre par date de création de l'usager, plutôt que juste "Du X au X" j'ai mis "Créée entre le X et le X"
Fix https://github.com/betagouv/rdv-insertion/issues/1853
=> feat(filters): UX improvements

app/javascript/react/models/User.js, spec/features/agent_can_edit_uploaded_user_list_spec.rb
Cette PR corrige un bug qui empêche d'affecter des tags depuis un fichier xls lorsque le tag en base de données contient des majuscules
Fix https://github.com/betagouv/rdv-insertion/issues/1923
=> fix(tags): tags case not working

app/controllers/organisations_controller.rb, spec/features/agent_can_edit_organisation_spec.rb
Le renseignement du code safir ne marchait pas car il n'était pas listé dans les paramètres permis par `OrganisationsController::PERMITTED_PARAMS`.
Je le fais ici et j'en profite pour ajouter un test de feature.
=> fix(organisation): Allow safir code update

app/controllers/users_controller.rb
closes #1925 
la variable `@current_agent_roles` ne scopait pas correctement les agent_roles (c'est l'écriture ternaire de la condition qui rendait le scope défectueux). Cela ne posait cependant pas de problème de sécurité, seulement d'affichage, car l'accès à la page était ensuite authorizée correctement.
Cette PR résout ce problème.
=> fix(index): never display configure organisation when basic agent role

app/views/users/_user_organisations_list.html.erb
Cette PR affiche dans la liste des organisations d'un usager lorsqu'une des organisations provient d'un autre département : 
Fixes https://github.com/betagouv/rdv-insertion/issues/1904
=> feat(users): specify when external orgs

app/javascript/controllers/dropdown_controller.js
Dans cette PR je fix un listener qui n'était pas proprement supprimé car la signature de la méthode qui lui était donné n'était pas identique (() => {} !== () => {})
Pour le fixer je suis obligé de mettre dans une variable la méthode à appeler à laquelle je bind this pour être sur que la signature donné à removeEventListener soit similaire
Fix https://github.com/betagouv/rdv-insertion/issues/1938
=> fix(status): prevent dropdown from showing up unwillingly 

app/controllers/stats_controller.rb, app/views/stats/_stats.html.erb
Fix pour [cette erreur remontée sur sentry](https://sentry.incubateur.net/organizations/betagouv/issues/96434/) suite au déploiement de #1882 .
Au lieu de juste changer le nom de la variable dans le block (ce que j'avais fai ici https://github.com/betagouv/rdv-insertion/commit/c12a5f328034ac95a007a35a5ec50ac0390899e7) j'enlève carrément la variable `@display_all_stats` qui je pense n'est plus pertinente avec notre fonctionnement aujourd'hui (je t'avais déjà posé la question sur son utilisation [ici](https://github.com/betagouv/rdv-insertion/pull/1323/files#r1314697041) @qblanc )
=> fix(stat): Fix organisation stat display

app/views/users/show.html.erb
L'utilisation des turbo frames sur la page `users#show` permet de naviguer d'onglets en onglets sans un full reload de la page pour une navigation plus agréable.
Cependant ça avait l'inconvénient que l'url n'était pas changé entre les pages et que donc on pouvait difficilement partager l'url d'une page "parcours", "rendez-vous" ou bien même "edit".
Je change ce comportement en changeant l'url lorsqu'on change de frame en settant l'attribute `data-turbo-action = "advance"` (le lien de la documentation est [ici](https://github.com/hotwired/turbo-site/blob/main/_source/handbook/04_frames.md#promoting-a-frame-navigation-to-a-page-visit) pour + d'infos).
=> refactor(navigation): Change url when navigating between frames

app/models/application_record.rb, app/models/concerns/user/address.rb, app/models/concerns/user/text_helper.rb, app/models/user.rb, app/services/users/save.rb
Lié à #1832 
Ici je fais en sorte d'empêcher les doublons lorsque: 
* les données d'identifications (numéro CAF, id interne ou nom prénom) sont mal formattés
* lorsqu'on envoie deux mêmes requêtes en même temps (race condition)
Dans le ticket je parle aussi de certains doublons qui ont été récupérés via webhooks. Vu la faible occurence de ces cas et la potentielle complexité de cet ajout je décide de ne pas le prendre en compte ici. 
J'introduis une méthode de classe `squishes` qui peut être utilisée sur tous les modèles `ActiveRecord`, qui permet de normaliser les attributs qu'on lui passe en les "squishant". Cette méthode s'appuie sur la nouvelle méthode `normalizes` de Rails 7. Je l'utilise donc pour squisher le nom, le prénom, l'id interne et le numéro CAF des usagers.
Je fais en …
=> feat(app): avoid duplicates

app/views/orientations/_orientation.html.erb, app/views/orientations/_orientations_list.html.erb, spec/features/agent_can_add_user_orientations_spec.rb
closes #1887 
Dans cette PR, je fais en sorte d'espacer les boutons de modif et de suppresion d'une orientation, + j'ajoute une popin de confirmation avant le destroy.
Vu avec @samanthaauffret : j'en profite également pour transformer en tableau (screen 1) cette petite liste dont la lisibilité n'était pas optimale (screen 2), en particulier dès qu'il y avait plus d'un item (répétition des "header" comme `Structure`, `Référent unique`, `Orientation` ; beaucoup d'infos sur une même ligne)
=> fix(parcours): alert when destroy orientation

app/services/orientations/save.rb, spec/services/orientations/save_spec.rb
Dans cette PR j'assigne automatiquement l'organisation associée à l'orientation à créer si l'usager n'y est pas déjà rattaché.
Fix https://github.com/betagouv/rdv-insertion/issues/1947
=> feat(orientation): automatically add user to the org

app/views/static_pages/welcome.html.erb, config/environments/production.rb, config/initializers/content_security_policy.rb
Je mets en place ici des content security policy headers pour avoir + de protection contre certaines attaques (+ d'infos [ici](https://guides.rubyonrails.org/security.html#content-security-policy-header)) .
J'en profite pour: 
* Hoster la vidéo de la landing sur notre bucket scaleway
* Ajouter `force_ssl` au niveau de l'application (on l'a au niveau de scalingo donc todo bien mais c'est + robuste au niveau de l'appli)
=> feat(security): Add content security policy headers

app/javascript/controllers/array_fields_input_controller.js, app/views/common/_attribute_input.html.erb, app/views/common/array_fields/_add_new_row_button.html.erb, app/views/common/array_fields/_input.html.erb
Suite au retrait de Simple form (#1872), le type d'input spécifique aux array mis en place par @qblanc dans #859 avait disparu.
Je le remets ici en faisant en sorte de ne pas changer l'API pour utiliser ce type d'input  (en spécifiant l'option `as: :array` à l'`attribute_input`).
=> fix(form): set back array input in forms

app/javascript/application.js, config/initializers/content_security_policy.rb
On a encore des erreurs en console à cause des nouvelles content security policy, notamment lorsqu'on envoie des requêtes à matomo et sentry.
Je règle ça ici et j'en profite pour baisser le taux de transactions sentry envoyé via l'app js: on en récupère beaucoup sur sentry et elles sont rarement interprétables ce qui crée du bruit.
=> fix(security): Add matomo and sentry to content security policy

app/javascript/stylesheets/components/_pagination.scss, app/views/kaminari/_paginator.html.erb
close https://github.com/betagouv/rdv-insertion/issues/1998
On a le même espacement entre les éléments, peu importe le nombre de page... Le centrage reste dynamique.
=> ux(pagination): set same margin regarless number of pages

app/services/exporters/generate_users_csv.rb, app/services/exporters/generate_users_participations_csv.rb, spec/factories/agent.rb, spec/services/exporters/generate_users_csv_spec.rb, spec/services/exporters/generate_users_participations_csv_spec.rb
closes #1983 #1981 #1988
Je change la façon dont on gère les exports csv pour: 
* Ne plus mettre le NIR dans ces exports
* Mentionner les organisations auxquelles appartient l'usager qui ne font pas partie du département de l'export
* Ne pas renseigner que les tags que l'agent a le droit de voir
=> fix(csv): Restrict csv exort informations

app/models/rdv_solidarites/rdv.rb, app/models/rdv_solidarites/user.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb
On a eu des erreurs sentry sur des usagers ne pouvant pas être créés au process du webhook de rdv parce que leur numéro de téléphone est invalide: 
* Sentry: https://sentry.incubateur.net/organizations/betagouv/issues/92857/?project=16&query=is%3Aunresolved&referrer=issue-stream
* Sidekiq: https://www.rdv-insertion.fr/sidekiq/retries/1715058417.887419-1eed3aa36c94299da33fa7b9
En creusant il apparaît qu'il s'agit en fait d'usagers qui ont été supprimés et donc le numéro de téléphone était `[valeur anonymisé]` ce qui faisait que le job échouait.
J'ai fait un fix ici pour ne pas prendre en compte les usagers supprimés dans les webhooks de rdvs. 
Ceci dit je me demande @Holist si ce serait pas plutôt côté rdv-s où on voudrait filtrer les usagers supprimés des rdvs ?
=> fix(webhooks): Handle deleted users webhooks

config/initializers/content_security_policy.rb
La carte de déploiement n'était pas visible à cause des content security policy.
=> fix(csp): Modify csp to enable deployment map visualisation

app/views/common/_error_list.html.erb
Avec la suppression de React pour l'invitation block dans #1990, la modal d'erreur laissait apparaître des tags html provenant des messages d'erreur, au lieu de formatter le dit-message (cf capture d'écran). Ce petit fix permet de résoudre ce problème.
\
Avant
\
Après
=> fix(modals): avoid plain html tags in error modals

app/controllers/previews/invitations_controller.rb, app/models/invitation.rb, app/services/concerns/invitations/sms_content.rb, app/services/invitations/generate_letter.rb
dans la PR #1993, j'ai profité de l'introduction de la méthode `rdv_solidarites_public_url` pour supprimer le `RdvSolidaritesMailerHelper`. Le problème c'est que cette méthode renvoie une url sans protocole, ce qui pose souci dans les mails (le lien n'est plus généré correctement). Je transforme donc cette méthode en `short_rdv_solidarites_public_url`, et rajoute une méthode `rdv_solidarites_public_url` qui renvoie la même url avec le protocole.
=> fix(mailers): invitation link in mailers

app/views/users/_users_list_header.html.erb
Une des features de [Turbo 8](https://dev.37signals.com/turbo-8-released/) qu'on a introduit dans #1990 est l'InstantClick, qui permet de pre-loader une page en passant la souris sur un lien afin de rendre cette page plus rapidement.
Malheureusement si cette page trigger des actions (comme nos actions d'export csv qui sont des liens GET et non pas des formulaires envoyés) ça a pour conséquences de générer un csv à chaque fois qu'on passe la souris sur le lien avant de le cliquer.
Je disable donc ce comportement pour les exports csv en rajoutant l'attribut `data-turbo-prefetch="false"`.
=> fix(csv): Prevent pre-fetch for exports

config/webpack/webpack.config.js
L'app js plantait parce que certaines variables d'env (utilisées seulement en prod) n'étaient pas définies
=> fix(jsapp): Add missing env variables

.env.example, app/policies/department_policy.rb, app/policies/organisation_policy.rb, spec/features/agent_can_upload_documents_for_users_spec.rb
Cette PR permet de ne pas afficher le parcours dans les départements qui ne le souhaitent pas.
En l'occurence pour le 44 (il restera à activer la variable d'env).
Fix https://github.com/betagouv/rdv-insertion/issues/2060
=> fix(parcours): prevent showing parcours in some departments

app/models/motif_category.rb, spec/factories/motif_category.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb, spec/jobs/send_invitation_reminders_job_spec.rb, spec/services/motif_categories/create_spec.rb
Cette PR permet d'éviter la création de motif category avec participation obligatoire pour des template de type atelier. 
Fix https://github.com/betagouv/rdv-insertion/issues/2006
=> fix(super_admin): ensure template can be affected to motif_category

app/jobs/send_invitation_reminder_job.rb, app/jobs/send_invitation_reminders_job.rb, app/jobs/send_periodic_invite_job.rb, app/models/concerns/invitable.rb, app/models/follow_up.rb, app/models/invitation.rb, db/migrate/20240523142208_add_trigger_to_invitations.rb, db/schema.rb, spec/jobs/send_invitation_reminder_job_spec.rb, spec/jobs/send_invitation_reminders_job_spec.rb, spec/jobs/send_periodic_invite_job_spec.rb, spec/models/follow_up_spec.rb, spec/services/invitations/save_and_send_spec.rb, spec/services/invitations/send_email_spec.rb, spec/services/invitations/send_sms_spec.rb
close https://github.com/betagouv/rdv-insertion/issues/1997
Pour le rattrapage du stock d'invitations périodiques (300 à la louche) déjà envoyées cela va être compliqué car on a que les user dans les logs mattermost.
On pourrait regarder pour chaque user les invitations envoyées vers 14h00 (heure du job d'envoi des invitations pérodiques).
Je ne sais pas ce que vous en pensez, si ca vaut le coup de s'y pencher ou pas.
=> feat(tech): replace reminder boolean with trigger enum - reminder, manual (default) and periodic values

app/models/motif_category.rb, spec/features/administrate/super_admin_can_manage_motif_categories_spec.rb, spec/services/motif_categories/create_spec.rb
Cette PR permet de vérifier la présence du template de reminder plutôt qu'une validation sur le type de model.
=> fix(template): model validation flaws

app/models/agent.rb
closes #2087 
Les agents ne pouvaient pas être supprimés s'ils avaient une orientation. A la place, on nullifie la relation pour permettre le destroy.
=> fix(model): nullify agent orientations

app/controllers/category_configurations_controller.rb, app/controllers/tags_controller.rb, app/javascript/stylesheets/_text.scss, app/javascript/stylesheets/_variables.scss, app/javascript/stylesheets/components/_card.scss, app/javascript/stylesheets/components/_color.scss, app/views/category_configurations/index.html.erb, app/views/tags/_tag.html.erb, app/views/tags/_tag_form.html.erb, app/views/tags/_tag_remove_from_organisation_confirm.html.erb, app/views/users/_user_tags.html.erb
close https://github.com/betagouv/rdv-insertion/issues/2013 https://github.com/betagouv/rdv-insertion/issues/2014
Merci beaucoup à @Michaelvilleneuve pour l'ajout de la modale d'alerte qui a rendu cette PR beaucoup plus rapide à implémenter.
Voici le résultat, je me suis permis de préciser "dans cette organisation" dans le message : "celui-ci sera retiré de tous les usagers comportant ce tag dans cette organisation." car le tag peux persister dans d'autres organisations. C'est plus clair pour les admins sur de multiples organisations.
=> ux(tags): rework of tag configuration ux and add a disclaimer

app/controllers/concerns/current_structure.rb
Après les changements récents, il y avait un souci sur l'écriture du conditionnel de l'auhtorization sur `current_structure` qui empêchait l'affichage des pages stats par orga ou département quand le visiteur n'était pas loggé. Cette PR résout ce problème.
=> fix(:stats): fix stats when not logged in

app/jobs/stats/global_stats/upsert_stat_job.rb, app/jobs/stats/monthly_stats/upsert_stat_job.rb
On a des erreurs régulières de timeout sur les jobs de stat (voir [ici](https://sentry.incubateur.net/organizations/betagouv/issues/?project=16&query=is%3Aunresolved+upsert&referrer=issue-list&statsPeriod=14d) sur sentry). J'ai l'impression cependant qu'au retry le job s'exécute correctement (parce que moins de jobs et moins de load sur la db en parallèle probablement).
Pour en être certain, je passe les jobs de 1 à 3 retries ici juste  pour rendre + visible si ce n'est pas le cas. Vu les horaires où le CRON se lance ça ne devrait pas avoir d'impact sur les performances de l'appli.
=> fix(stats): Increase stat job retries

app/controllers/concerns/current_structure.rb, app/controllers/stats_controller.rb, app/helpers/stats_helper.rb, app/views/stats/_header.html.erb, app/views/stats/show.html.erb
Lorsque l'on est connecté on ne peut pas afficher les stats d'un département auquel on appartient pas ce qui n'est pas logique, j'essaie de réparer ça ici en enlevant la logique de `current_structure` de la page stat où on en a pas forcément besoin. Ça permet de ne pas avoir ce genre d'incohérence en gardant toujours la logique d'autorisations dans notre concern et donc de l'utiliser que pour un usager connecté. 
On a également [des erreurs 500](https://sentry.incubateur.net/organizations/betagouv/issues/104334/) signalées sur sentry à l'affichage des stats, je n'ai pas réussi à identifier le problème mais cette PR devrait le régler cependant.
**Annexe**: j'en profite pour déplacer une requête qui se trouver dans le helper dans le controller.
=> fix(stats): fix stats display

app/models/follow_up.rb, db/migrate/20240611225639_add_index_to_triggers.rb, db/schema.rb
Le filtre "intervention nécessaire" ne fonctionnait plus correctement et renvoyait des usagers avec invitations dont le délai n'était pas dépassé, probablement suite à la migration de #2056 .
Je tente ici de le réparer, et j'en profite pour mettre un index sur les `trigger` de la table invitation.
=> fix(users): fix action required filter

app/javascript/controllers/new_user_form_controller.js, app/views/users/_user_form.html.erb, app/views/users/new.html.erb, spec/features/agent_can_create_user_through_form_spec.rb
Lors de la création d'un usager au niveau du département, nous sélectionnons désormais l'organisation en fonction de l'adresse entrée par l'usager. 
Si aucune organisation n'est trouvée, on lève une modale pour choisir l'organisation. 
La majorité de ce workflow est récupérée de la page upload où nous avons déjà un comportement similaire. 
Fix https://github.com/betagouv/rdv-insertion/issues/2067
=> feat(user): selecting org based on address

app/javascript/react/components/user/EditableTags.jsx, spec/features/agent_can_edit_uploaded_user_list_spec.rb
Je fix ce flaky en mettant le "hide" de la modal derrière un await de la requête, ce qui permet d'élargir le délai entre le moment où on clique sur enregistrer et le moment où on check la colonne.
Testé en local de la façon suivante : 
```
bundle exec rspec spec/features/agent_can_edit_u***
```
Cette façon de lancer le test permettait de reproduire le flaky (2 fois sur 3 au moins) et passe désormais
=> fix(flaky): upload page flaky

app/controllers/concerns/turbo_stream_concern.rb, app/controllers/invitations_controller.rb, app/javascript/controllers/invitation_button_controller.js, app/javascript/controllers/remote_modal_controller.js, app/services/invitations/validate.rb, app/services/invite_user.rb, spec/controllers/invitations_controller_spec.rb, spec/services/invitations/validate_spec.rb, spec/services/invite_user_spec.rb
Ici je fixe un changement introduit dans #2039 qui faisait que sur la page show, lorsque l'invitation d'un usager échouait, le bouton restait dans son loading state.
J'en profite pour: 
* Lier les invitations au niveau du département aux seules organisations qui gèrent la catégorie dans laquelle on invite (ce n'était pas le cas)
* déplacer la validation des invitations envoyées il y a - de 24h dans le service `Invitations::Validate`
=> fix(invitations): Reset loading button in show page

spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb
Je fais en sorte que l'ordering du tableau de participations_attributes n'importe pas en reordonnant manuellement les argument avant de expect
Fix https://github.com/betagouv/rdv-insertion/issues/2083
=> fix(specs): flaky unit test

app/models/user.rb, spec/models/user_spec.rb
Juste un fix sur la regex de validation de l'email que je rend un peu plus stricte pour ne pas permettre l'enchainement de 2 points dans le domaine pour éviter des erreurs comme celle là https://www.rdv-insertion.fr/sidekiq/retries/1718823809.0168757-a0391319d2c58c38ca6e6d3c
=> fix(validation): email regex

app/models/follow_up.rb, app/views/follow_ups/_follow_up_status_cell.html.erb, app/views/users/_all_users_table.html.erb, app/views/users/_users_table_for_motif_category.html.erb, spec/features/agent_can_see_curent_pending_rdv_date_on_users_index_spec.rb
closes #2074 
Dans notre app, il peut exister un décalage entre le statut d'un `follow_up` et l'état d'un `rdv` : le jour de la tenue du `rdv`, le `follow_up` gardera la statut `rdv_pending` jusqu'à ce que [ce CRON](https://github.com/betagouv/rdv-insertion/blob/staging/app/jobs/refresh_out_of_date_follow_up_statuses_job.rb) tourne - il tourne tous les soirs à 21. Je fais en sorte que la date de ce `RDV à venir` continue à s'afficher à côté du statut sur les listes de l'index dans ce cas là.
N.B. : 
- sur la page upload le problème ne se posait pas car la comparaison du rdv dans le futur se fait sur la date générée par `todaysDateString`, qui correspond au début de la journée. Tous les rdvs du jour même sont donc bien considérés comme étant dans le futur - pas besoin de fix
- Le display …
=> fix(index): fix display current rdv date

.env.example
après les changements apportés par @Holist dans #2000 au fichier `config/initializers/content_security_policy.rb`, je modifie la valeur d'exemple de `INCLUSION_CONNECT_BASE_URL` pour qu'elle corresponde à la valeur de `env.test`
=> fix(config): change inclusion connect base url in env.example

app/views/organisations/user_added_notifications/_no_email.html.erb, app/views/users_organisations/create.turbo_stream.erb
close https://github.com/betagouv/rdv-insertion/issues/2129
Voici le message qu'on affiche désormais quand une organisation n'a pas de mail et qu'un agent y ajoute des usagers. 
Nous n'avions aucun message avant et cela portait à confusion.
=> ux(message): inform agent when organisation has no email when add a user on it

app/javascript/react/components/user/InvitationCell.jsx
Dans cette PR je mets un spinner cohérent avec le bouton initial pour le cas où l'on réinvite un usager. J'ai aussi extract dans une méthode pour éviter la ternaire illisible
Fix https://github.com/betagouv/rdv-insertion/issues/2101
=> fix(upload): spinner when sending invite with one already sent

app/controllers/concerns/users/taggable.rb, app/controllers/users_controller.rb, app/helpers/tags_helper.rb, app/javascript/controllers/tooltip_controller.js, app/views/users/_user_page_header.html.erb, app/views/users/_user_tags.html.erb, app/views/users_tags/_user_tag_badge.html.erb
closes #2128 
Dans cette PR, je fais en sorte d'afficher la date de rattachement du tag à un usager lorsque l'on survole ce tag à la souris. J'en profite pour faire une petite refacto du composant.
=> feat(show): add creation date to user_tag

app/controllers/previews/invitations_controller.rb, app/mailers/invitation_mailer.rb, app/models/invitation.rb, app/services/concerns/invitations/sms_content.rb, app/services/invitations/generate_letter.rb, app/views/letters/invitations/phone_platform.html.erb, app/views/letters/invitations/standard.html.erb, app/views/mailers/invitation_mailer/phone_platform_invitation.erb, app/views/mailers/invitation_mailer/standard_invitation.html.erb, spec/factories/motif_category.rb, spec/services/invitations/generate_letter_spec.rb, spec/services/invitations/send_sms_spec.rb, spec/support/motif_categories_helper.rb
closes #2126 
Dans cette PR, je fais en sorte de ne pas afficher le délai de prise de rdv quand il n'y a pas de reminder envoyé.
Question subsidiaire :  il n'y a pas de lien entre `display_mandatory_warning` (template) et `optional_rdv_subscription` (motif_category), est-ce que c'est logique ?
=> feat(invitations): don't display delay when optional rdv subscription

app/helpers/stats_helper.rb, app/services/stats/monthly_stats/compute_for_focused_month.rb, app/services/stats/monthly_stats/upsert_stat.rb, app/views/stats/_stats.html.erb, spec/services/stats/monthly_stats/compute_for_focused_month_spec.rb, spec/services/stats/monthly_stats/upsert_stat_spec.rb
closes #2119 
Pour éviter qu'il y ait un décrochage systématique sur le dernier mois affiché pour la stat du "Taux d'usagers orientés via l'outil par mois", on décale le calcul de la stat d'un mois pour pouvoir observer des cohortes + cohérentes, qui ont eu le temps nécessaire pour avoir leur rdv (ce qui peut parfois prendre + d'un mois)
=> fix users oriented stat

app/views/category_configurations/_category_configurations_list.html.erb
closes #2109 
Le lien de suppression d'une category configuration ne marchait parce que l'élément était un `button_to` et pas un `link_to` et donc le code js modale de confirmation n'arrivait pas à récupérer le lien de l'élément. 
Les data attributes étaient également pas déclarés correctement.
=> fix(configuration): Fix delete category configuration button

app/views/super_admins/organisations/new.html.erb
Closes #1462 
J'ajoute un warning au moment de lier l'organisation à celle rdvsp pour faire attention aux cas où l'organisation rdvsp est ancienne:
=> feat(super_admin): Add warning message when adding ancient org

app/controllers/concerns/agent_roles/csv_export_authorizations_controller.rb, app/models/agent_role.rb, spec/models/agent_role_spec.rb
Lorsqu'un agent n'est passe du niveau admin à un niveau basique, il était toujours autorisé à exporter les csv.
Je change ce comportement pour qu'il ne soit plus autorisé à exporter les csv s'il redevient un agent basique au sein de l'organisation.
J'en profite pour ajouter un flash message au moment de l'update des autorisations (ça ne coûte rien et c'est perturbant je trouve de ne rien voir).
=> fix(agent_roles): Unauthorize export when access level changes

app/models/concerns/deliverable.rb, app/services/inbound_webhooks/brevo/assign_delivery_status_and_date_base.rb, app/services/inbound_webhooks/brevo/assign_mail_delivery_status_and_date.rb, app/services/inbound_webhooks/brevo/assign_sms_delivery_status_and_date.rb, db/migrate/20240705140428_rename_delivered_at_to_last_brevo_webhook_received_at.rb, db/schema.rb, spec/requests/brevo_mail_webhooks_spec.rb, spec/requests/brevo_sms_webhooks_spec.rb, spec/services/inbound_webhooks/brevo/assign_mail_delivery_status_and_date_spec.rb, spec/services/inbound_webhooks/brevo/assign_sms_delivery_status_and_date_spec.rb
Le bug est le suivant :
En enlevant `soft_bounce` des status d'erreur finaux hier (pour lui permettre de passer en `delivered` en cas de retry positif) je me suis retrouvé avec le problème d'ordre des webhook de Brevo (l'invitation passe en `soft_bounce` puis en `sent` parcequ'on reçoit les webhook dans le désordre).
J'ai un peu revu et amélioré le code en plus de fix le problème.
Désormais toutes les invitations avec un status en erreur peuvent changer de status passer en `delivered` (uniquement) si on reçoit un webhook dans ce sens (à priori ça n'arrivera jamais pour les `hard_bounce` mais c'est géré)
La constante `FINAL_DELIVERY_STATUS` rendait les choses un peu trop floues, je l'ai enlevé.
=> fix(brevo_webhooks): update failed status with delivered events only

app/services/inbound_webhooks/brevo/assign_mail_delivery_status_and_date.rb, spec/services/inbound_webhooks/brevo/assign_mail_delivery_status_and_date_spec.rb
Pour éviter d'avoir des faux positif : https://sentry.incubateur.net/organizations/betagouv/issues/110095/?environment=staging&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=1
=> fix(brevo): compare email without case when sending warning to sentry

app/blueprints/agent_blueprint.rb, app/blueprints/application_blueprint.rb, app/blueprints/archive_blueprint.rb, app/blueprints/department_blueprint.rb, app/blueprints/follow_up_blueprint.rb, app/blueprints/invitation_blueprint.rb, app/blueprints/lieu_blueprint.rb, app/blueprints/motif_blueprint.rb, app/blueprints/motif_category_blueprint.rb, app/blueprints/organisation_blueprint.rb, app/blueprints/participation_blueprint.rb, app/blueprints/rdv_blueprint.rb, app/blueprints/tag_blueprint.rb, app/blueprints/user_blueprint.rb, spec/models/user_spec.rb, spec/swagger_helper.rb, swagger/v1/api.json
closes #2142 
J'ajoute les participations aux webhooks pour pouvoir s'adapter aux rdvs collectifs. Le commit qui correspond à ce développement: https://github.com/gip-inclusion/rdv-insertion/commit/57b36b8094116c25a36d406c728298b8542a53d9
J'en ai profité pour mettre les associations qui étaient scopées à l'agent dans une méthode dans une nouvelle classe `ApplicationBlueprint`
=> feat(api): add participations to webhook payload

app/javascript/react/models/User.js
Ce simple fix permet d'éviter une erreur 404 lors de l'édition d'un des attributs du user si celui-ci est détécté dans rdvi mais ne fait pas parti de la currentOrganisation. 
Grace à celui-ci on modifie uniquement la donnée localement et celle-ci sera réellement changée en base de données uniquement si l'usager est ajouté à l'organisation en cours.
Dans le cas reproduit pas claire, elle aura donc un message d'erreur "email invalide" lors de l'ajout à l'orga, l'édition du champ permettra sans erreur 404 de modifier localement la donnée, puis donc de la modifier en base à travers une nouvelle tentative d'ajout à l'orga. 
Fix https://github.com/gip-inclusion/rdv-insertion/issues/1953
=> fix(upload): ensure user belongs to current org when updating it

spec/swagger_helper.rb, swagger/v1/api.json
La liste des statuts possibles n'avait pas été mise à jour dans la doc de l'API suite à #2182 . 
Je le fais ici
=> Update invitation api doc delivery statuses

config/initializers/sidekiq.rb, config/middlewares/sidekiq/capture_current_agent.rb
Cette PR permet de conserver le Current.agent même lors d'un retry Sidekiq. Pour cela, je fais en sorte de set et récuperer le Current.agent avant de déclencher les middleware de Sidekiq Retry. 
Lors du lancement du job je fais en sorte de ne pas mettre le job['current_agent_id'] à nil s'il avait déjà une précédente valeur
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2218
=> fix(sidekiq): keep agent context upon retries

app/policies/organisation_policy.rb, app/views/users/_user_organisations_list.html.erb
Cette PR permet de ne pas afficher le bouton de suppression d'orga si le current agent n'appartient pas à celle-ci 
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2215
=> fix(user): prevent displaying remove org button

app/models/participation.rb
Cette PR permet d'éviter un crash quand on cherche à appeler motif_category sur un follow_up nil.
Ceci n'explique pas la raison de cette incohérence mais corrige le problème
=> fix(participation): prevent crash when calling delegated property

app/models/address/parser.rb, spec/models/address/parser_spec.rb
Lorsqu'on a une adresse où le code postal est suivi d'une `,`, la méthode `parsed_city` du parser retourne une chaine de caractère qui commence par cette virgule, ce qui cause un problème au moment de l'appel à l'API adresse.
=> fix(address): Fix parser adress parsed_city method

app/clients/api_adresse_client.rb, app/models/address/parser.rb
L'endpoint de l'API adresse n'accepte pas les queries qui ne commence pas par un caractère alpha numérique. 
Je filtre donc les caractères non alpha numériques avant d'appeler l'API.
=> fix(api): Call adresse API properly

app/clients/api_adresse_client.rb, app/models/geo_json/feature.rb, app/services/retrieve_address_geocoding_params.rb
Je fais un dernier fix sur le traitement des appels à l'API adresse pour:
* Ne pas l'appeler avec des chaines de caractères vides ou commencant par des caractères alphanumériques
* Ne pas faire le check sur le code postal si dans la réponse de l'API on a pas de code postal
=> fix(geocoding): Fix adresse api calls

app/models/concerns/user/address.rb, app/services/exporters/generate_users_csv.rb, app/services/exporters/generate_users_participations_csv.rb, app/services/retrieve_address_geocoding_params.rb, config/locales/models/user.fr.yml, spec/services/exporters/generate_users_csv_spec.rb, spec/services/exporters/generate_users_participations_csv_spec.rb
closes #1197 
J'utilise les geocodages nouvellement stockés en base de données pour ajouter un champ `CP` et `Ville` aux exports csv. 
N.B: J'en profite pour ajouter ce commit qui n'est pas directement lié à cette feature mais qui permet d'éviter d'appeler l'api adresse lorsque ce n'est pas possible https://github.com/gip-inclusion/rdv-insertion/commit/a81ecc15eabb8d71f88794f241717938ddf4bc9d
=> feat(csv): use geocoded post code and city for exports

app/models/webhook_endpoint.rb, db/migrate/20240723171205_add_organisation_reference_to_webhook_endpoints.rb, db/schema.rb
Aujourd'hui un `webhook_endpoint` peut être liés à plusieurs organisations via une relation many:many.
L'idée est de changer ce comportement est d'avoir une relation 1:many pour pouvoir lier un `webhook_endpoint` à une seule organisation. 
Il y a plusieurs avantages à cela: 
* On peut lier un `webhook_receipt` à une organisation spécifique
* On peut récupérer l'organisation pour laquelle on envoie le webhook et ajuster les données à envoyer en fonction de cela
Cette PR est la première d'un set de 2 PRs visant à faire cette migration.
=> feat(db): Add organisation id to webhook endpoints

app/models/organisation.rb, app/models/webhook_endpoint.rb, db/migrate/20240723232305_drop_webhook_endpoint_organisations_join_table.rb, db/schema.rb
Vient après #2230 .
Ici on enlève la table de jointure entre les `webhook_endpoints` et les `organisations`.
=> feat(db): drop webhook endpoint organisations join table

app/dashboards/user_dashboard.rb, app/javascript/react/models/User.js, app/models/concerns/user/creation_origin.rb, app/services/users/upsert.rb, app/views/users/_user_form.html.erb, config/locales/models/user.fr.yml, spec/features/agent_can_create_user_through_form_spec.rb, spec/models/user_spec.rb
Cette PR fait suite à #2192  et répond à 2 problèmes: 
* Elle empêche les attributs d'origine de pouvoir être modifiés une fois que l'usager est persisté. En effet, vu qu'on fait des upsert d'usagers sur l'application, il est possible que ces attributs soient assignés à un usager persisté. Je fais en sorte ue ce soit impossible dans (https://github.com/gip-inclusion/rdv-insertion/commit/010775bc285310f3094db1aa2b5a3f0cefa9235d)
* J'affiche cette info dans le super admin dans https://github.com/gip-inclusion/rdv-insertion/commit/8f97ef02b6f24dca5dd4b3ef50f6bfda6f5ced8c
=> fix(user): Improve user creation origin mechanism

app/controllers/previews/invitations_controller.rb
closes #2209 
La phrase "dans les 3 jours" continuait de s'afficher dans les previews même après #2153 .
C'est parce que dans les previews il faut passer explicitement les variable d'instance instanciées dans le mailer, et on ne l'avait pas fait pour le nouvel attribut `optional_rdv_subscription`.
=> feat(preview): Add optional rdv subscription to previews

app/models/organisation.rb
Cette validation permet de s'assurer que https://sentry.incubateur.net/organizations/betagouv/issues/113518/?environment=prod&environment=production&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0 ne puisse plus se produire
=> fix(organisation): validate organisation type presence

app/views/category_configurations/show.html.erb, spec/features/agent_can_edit_external_notifications_spec.rb
Cette PR améliore l'ui de la show des notifications tierces
Fix: https://github.com/gip-inclusion/rdv-insertion/issues/2237
=> feat(notifications_tierces): improved ui for 3rd party notifs

Gemfile, Gemfile.lock, app/jobs/stats/global_stats/upsert_stat_job.rb, app/jobs/stats/global_stats/upsert_stats_job.rb, app/jobs/stats/monthly_stats/compute_and_save_single_stat_job.rb, app/jobs/stats/monthly_stats/upsert_stat_job.rb, app/jobs/stats/monthly_stats/upsert_stats_job.rb, config/sidekiq.yml
Cette PR permet de garantir qu'un maximum de 2 jobs de stats peuvent tourner en parallèle. Ceci dans le but de réduire et étaler le load des stats sur la DB
=> fix(sidekiq): make sure a maximum of 2 stats jobs run in parallel

app/models/notification.rb, app/models/participation.rb
Closes #2222 
Jusqu'à présent on ne supprimait pas les notifications liés à un rdv lorsque ce rdv est supprimé.
Cela est dû il me semble à l'implémentation initiale où une notification était envoyée lorsque le rdv était supprimé (ce n'est plus le cas aujourd'hui comme ce ne l'est pas sur rdvsp).
Il n'y a pas grand intérêt à garder cette donnée si elle ne peut pas être liée à une participation (et donc à un usager), je décide donc de supprimer les notifications sans participations et ainsi éviter les erreurs comme [celle-ci](https://sentry.incubateur.net/organizations/betagouv/issues/112149/?environment=production&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=6)
=> refactor(notifications): Destroy notifications with participations

db/migrate/20240628171109_archive_users_by_organisation_rather_than_by_department.rb
En regardant les extra datas ajoutés dans #2296 il semblerait que [l'on itère à un moment donné sur des archives nouvellement créés](https://sentry.incubateur.net/organizations/betagouv/issues/118225/?project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0).
J'essaie de résoudre le problème ici en preloadant les ids des archives en BDD.
=> fix(migration): Fix archive migration new attempt

.env.example, app/clients/mattermost_client.rb, app/services/concerns/messengers/send_sms.rb, app/services/concerns/notifications/sender_phone_number_validation.rb, app/services/notifications/send_email.rb, app/services/notifications/send_sms.rb, spec/services/notifications/send_email_spec.rb, spec/services/notifications/send_sms_spec.rb
Cette PR permet de bloquer l'envoi de SMS et de mails de notifications lorsqu'un numéro de téléphone n'est pas renseigné et nous en informe sur Mattermost
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2260
=> fix(notifications): prevent sending notifs when empty sender phone number

app/javascript/react/components/user/TableRow.jsx, app/views/layouts/_application_base.html.erb, app/views/users/_page_title.html.erb
closes #2282 et #2283 
- On ne met pas le nom de l'usager en titre de page (pour qu'il ne soit pas remonté sur Matomo)
- On ajoute l'attribute `data-matomo-mask` pour être sûr de n'envoyer aucune données personnelles lors des recordings
=> fix(tracking): Anonymize data for tracking

app/jobs/stats/monthly_stats/compute_and_save_single_stat_job.rb, app/models/stat.rb, spec/jobs/stats/monthly_stats/compute_and_save_single_stat_job_spec.rb, spec/models/stat_spec.rb
Suite au déploiement du split du calcul en plusieurs jobs ce sont désormais dans n'importe quel ordre que les stats sont mises à jour. Cette PR permet donc de reclasser la hash d'un stat au moment de la sauvegarde et de supprimer les valeurs de départ du hash si elles sont égales à zéro
=> fix(stats): prevent showing empty start numbers

config/environments/development.rb, db/migrate/20240905161813_remove_logo_filename_from_organisations.rb, db/schema.rb
Lié à #2235 .
On enlève la colonne `logo_filename` qui n'est plus utilisée.
=> fix(db): remove unused column

app/helpers/organisations_badges_helper.rb, app/javascript/controllers/tooltip_controller.js
Close : https://github.com/gip-inclusion/rdv-insertion/issues/2269
Avant | Après
:- | -:
Pour info, j'ai préféré ne pas limiter arbitrairement le nombre de caractères concernant la raison de l'archivage.
Le tooltip gère automatiquement le retour à la ligne si le texte est trop long. @samanthaauffret 
Ex :
=> bug(ux): fix archiving tooltip not displaying archiving_reason with spaces

app/javascript/application.js, config/webpack/webpack.config.js, package.json, yarn.lock
J'enlève le sentry côté client qui remontait les erreurs liées au code JS (composants react ou stimulus controller notamment) car je trouve que ça crée beaucoup de bruit sur Sentry et que les erreurs remontées sont trop imprécises pour amener à des actions concrètes et à du bugfix.
=> feat(deps): Remove Sentry JS

Gemfile, Gemfile.lock, app/controllers/organisations_controller.rb, app/dashboards/organisation_dashboard.rb, config/initializers/safe_migration.rb
L'application a été down quelques minutes ce matin suite au déploiement de commit https://github.com/gip-inclusion/rdv-insertion/commit/904d7117454c31bdb1046b0e8c8e478782b6a3e3. 
Pour une raison que l'on ignore, la migration pourtant simple était bloquée pendant plusieurs minutes. @Michaelvilleneuve a évoqué la piste de la sur-utilisation de notre RAM Postgres.
Dans tous les cas cela a eu pour conséquence de locker notre table `organisations` pendant plusieurs minutes. Et comme cette table est utilisée dans presque toutes les pages, ça a fait que les requêtes se sont  empilées et toute dans l'attente de la release de la table, ce qui a fait que plus aucune connection à la base était disponible.
Pour prévenir que cela se reproduise de nouveau, j'ai ajouté un `lock_timeout` via la gem …
=> feat(migrations): Add safer migrations mechanism

app/jobs/inbound_webhooks/rdv_solidarites/process_motif_job.rb, app/models/rdv_solidarites/motif.rb
Lié  à #2318 
En attendant de prendre en compte les motifs par "visio" sur RDVI (voir #2318 ), j'ignore pour le moment les motifs de ce type qui ne sont pas catégorisés (et qui donc ne sont pas pertinents pour rdv-i)
=> fix(motifs): Do not process visio motif for now

app/blueprints/invitation_blueprint.rb, app/controllers/api/v1/users_controller.rb, docs/api/description.md, spec/swagger_helper.rb, swagger/v1/api.json
Lié à #2297 .
* J'ajoute le champ `expires_at` au blueprint des invitations. Ainsi le webhook envoyé (pour l'interco avec les emplois) contiendra cette information
* Je prends en compte le `short_name` pour préciser la catégorie de motif au moment de l'invitation
=> feat(api): Add new api usages

app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/models/archive.rb, swagger/v1/api.json
Cette PR contient plusieurs petits fixes: 
* https://github.com/gip-inclusion/rdv-insertion/commit/4790f8df0f2a6affabddb3e3c3ca6fd5f204cf8b: La doc swagger n'était pas totalement à jour suite aux changements dans le fichier `description.md` dans #2327 
* https://github.com/gip-inclusion/rdv-insertion/commit/08632364fa9dca48f718e688815dd2162c8eabcb : de la logique spécifique à la migration des archives avait été introduite, je l'enlève ici
* https://github.com/gip-inclusion/rdv-insertion/commit/8dc12ff6f39c7e9d6e75288d5afc896833275379: Lorsque l'on traite un webhook de rdv on ne vérifie le motif que si la catégorie est gérée (vient en complément de #2322)
=> fix(app): Few small fixes

Gemfile, Gemfile.lock, config/anonymizer.yml, spec/anonymizer_spec.rb
Cette PR vient dans le cadre de l’extraction d’une gem d’anonymisation et d’un repo à part d’ETL : https://github.com/betagouv/rdv-service-public/pull/4362
Le fichier de configuration des règles d’anonymisation de RDVI est maintenant commité dans le repository RDVI plutôt que RDVSP. Cela devrait faciliter les itérations. Ce fichier sera téléchargé par [l’ETL](https://github.com/betagouv/rdv-service-public-etl) depuis la branche staging de ce repo github.
Le format de ce fichier a aussi bien changé : 
- Passage de ruby à yaml
- Il n’y a maintenant qu’une seule clé top level `tables` 
- Les tables tronquées ne sont plus à part mais ont une règle truncated: true
J’ai rajouté une dépendance en dev et test sur la gem `anonymizer`. 
Ça permet de rajouter une spec qui lance …
=> Ajout config/anonymizer.yml

config/webpack/webpack.config.js, spec/support/assets_build.rb
closes #2172 .
En faisant des tests de mon côté, j'ai l'impression qu'après avoir enlevé tous les assets précompilés sur ma machine via la commande `rails assets:clobber` (merci @adipasquale 🙇‍♂️ !), les changements dans le code des assets sont maintenant 
reflétés dans les tests d'intégration.
Maintenant lorsque : 
* j'effectue un changement sur du code amené à être précompilé (dans le dossier `app/javascript/`)
* et que mon app tourne en local (et que donc le changement est pris en compte via la compilation de webpack)
= > Le test reflète bien le changement effectué.
En plus de ça, j'ajoute dans cette PR un script qui vérifie qu'un build a toujours eu lieu après un changement au niveau du code des assets. Si ce n'est pas le cas et que l'on a lancé au moins un test de feature, on lance …
=> fix(tests): Ensure assets are precompiled when launching tests

app/javascript/react/actions/assignReferent.js
Bug remonté par Eva toute à l'heure.
La fonctionnalité d'ajout de référent depuis la page upload est cassée.
Cela est sans doute lié à cette PR de changement des routes : https://github.com/betagouv/rdv-insertion/issues/2247
Je fix ce problème ici.
=> bug(upload): assign_referent route changed but not in js file

app/javascript/react/components/user/InvitationCells.jsx
Cette PR rend visible via un tooltip le motif d'archivage pour les archives créées au niveau de l'organisation dans laquelle on est en train d'importer des usagers. 
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2315
=> feat(archives): add archive reason

app/controllers/tags_controller.rb, app/models/tag_organisation.rb, spec/features/agent_can_edit_organisation_tags_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2306
Rien de franchement compliqué ici.
Cela dit j'ai pris un peu de temps pour me décider sur quel message d'erreur afficher et comprendre comment fonctionne les erreurs et dans quel cas on affiche quel type d'erreur. (modal standard, modal custom, liste dans le formulaire, message flash)
Initialement je suis parti sur la liste des erreurs directement dans le formulaire en utilisant un `turbo_stream_replace_error_list_with` modifié mais je trouve que ca marche mieux avec la modale.
J'en ai profité pour ajouter un test pour aller avec (et un test sur la suppression de tag qui n'existait pas)
Le message d'erreur est basique :
=> fix(tag): fix unicity constraint for `TagOrganisation` and add modal error message

lib/tasks/users/transfer_referent.rake, lib/users/transfer_referent.rb, spec/lib/users/transfer_referent_spec.rb
Dans cette PR j'ajoute une tâche permettant de transférer sereinement des usagers d'un référent à un autre. 
J'ai fait le choix de faire ça de notre côté en appelant l'API de RDV-s pour s'éviter la gymnastique mentale de devoir penser à passer les IDs en RDVs, pour garder la main sur cette tâche et la faire évoluer comme on le souhaite. 
Cette task sera à utiliser dans le scope de cette issue : 
https://github.com/gip-inclusion/rdv-insertion/issues/2346
=> feat(user): add transfer referent task

config/initializers/sentry.rb, spec/jobs/concerns/locked_jobs_spec.rb
Cette PR fait suite à #2340 et je modifie deux choses par rapport au commit initial: 
* Je change la spec du concern `locked_jobs` qui était flaky parce que le lock pouvait persister entre les 2 tests que comprend le fichier `locked_jobs_spec.rb`. Je fais en sorte d'englober chaque thread dans un bloc que l'on passe à  `ActiveRecord::Base.connection_pool.with_connection` pour être sûr que le thread release sa connection (et donc le lock) après son exécution. Ce changement se trouve ici: https://github.com/gip-inclusion/rdv-insertion/pull/2365/commits/7aca12a68b925f0cdec7872ed84b5adb0e7032ff
* Suite à ce commentaire https://github.com/gip-inclusion/rdv-insertion/pull/2340#discussion_r1782262124 je remets l'exception sur sentry le temps de voir si on a bien des jobs qui raise en tentant …
=> fix(locking): Fix flaky test + Remove sentry excluded exception

Gemfile, Gemfile.lock, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb, spec/jobs/refresh_out_of_date_follow_up_statuses_job_spec.rb, spec/rails_helper.rb
Tout est dans le titre.
Subtilités : 
On doit utiliser cette version spécifique de la gem "database_cleaner-active_record", "~> 2.2" à cause d'une incompatibilité avec rails 7.1. J'ai mis le lien dans le gemfile.
J'ai du revoir des tests qui utilisaient des id spécifiés pour la création des records (à éviter) sinon on avait des erreurs postgres.
=> feat(tech): add database cleaner gem to prevent flakyness

app/dashboards/motif_category_dashboard.rb, app/models/follow_up.rb, app/models/motif_category.rb, config/anonymizer.yml, config/locales/administrate.fr.yml, config/locales/models/motif_category.fr.yml, db/migrate/20241001131337_add_motif_category_type_to_motif_category.rb, db/migrate/20241001133756_remove_leads_to_orienation_from_motif_category.rb, db/schema.rb, db/seeds.rb, spec/factories/motif_category.rb, spec/features/administrate/super_admin_can_manage_motif_categories_spec.rb, spec/models/stat_spec.rb, spec/services/exporters/generate_users_csv_spec.rb, spec/support/motif_categories_helper.rb
Close https://github.com/gip-inclusion/rdv-insertion/issues/2291
Dans le super admin vous pouvez spécifier le type de catégorie de motif quand vous en créez une.
J'affiche également la colonne dans l'index pour pouvoir les trier si besoin.
L'option leads_to_orientation a été remplacé par la valeur `rsa_orientation` pour le nouvel attribut.
Avant | Après
:- | -:
Avant | Après
:- | -:
On ajoute un champ pour les `MotficCategory` pour pouvoir spécifier le type de motif. (`motif_category_type`)
Je n'ai pas utilisé le nom de colonne `type` car le mot type fait parti des mots réservés.
J'ai remplacé le fonctionnement existant de l'attribut `leads_to_orientation` par le nouveau champ et la valeur `rsa_orientation` dans le scope existant.
Je compte modifier manuellement les type de catégories de …
=> feat(motif_category): add motif_category_type

app/clients/rdv_solidarites_client.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/models/agent.rb, app/models/concerns/agent/rdv_solidarites_client.rb, app/models/rdv_solidarites/user.rb, app/services/invitations/verify_organisation_creneaux_availability.rb, app/services/rdv_solidarites_api/retrieve_user.rb, lib/organisations/destroy_multiple.rb, lib/users/transfer_referent.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb, spec/services/rdv_solidarites_api/retrieve_user_spec.rb
⚠️ Cette PR est liée et doit être mergée après la PR associée sur rdv-sp : https://github.com/betagouv/rdv-service-public/pull/4674
closes #2244 
Dans certains cas, lorsqu'un usager créé depuis rdvsp a un rdv placé sur une organisation présente dans rdv-insertion, pour une catégorie de motif gérée par l'organisation dans rdv-insertion, nous importons le rdv ainsi que l'usager sur rdv-insertion.
Cependant, lorsque l'on crée l'usager sur rdv-i, on le lie uniquement à l'organisation du rdv en question. 
Or cet usager peut potentiellement déjà appartenir à plusieurs organisations déjà présentes sur rdv-i. Ainsi il en résulte un problème de synchronisation: 
* on n'affiche pas toutes ses orgas sur rdvi
* on laisse la possibilité de l'ajouter sur ces orgas depuis rdv-i ce qui engendrera des …
=> feat(webhooks): Retrieve user organisations when creating it from rdvsp

lib/tasks/users/transfer_referent.rake, lib/users/transfer_referent.rb
Cette PR rajoute un rescue sur des erreurs possiblement imprévues. Typiquement j'ai reçu une 500 pour un des usagers ce qui a bloqué l'execution du script. 
De cette façon il tournera jusqu'au bout et affichera les ids problématiques afin de pouvoir les débugger à la main
=> script(referent): fix potentially blocking errors

app/jobs/inbound_webhooks/rdv_solidarites/process_referent_assignation_job.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_user_profile_job.rb, config/initializers/sentry.rb
Je fais deux choses dans cette PR permettant d'éviter des erreurs dans les jobs traitant les webhooks et ainsi réduire le volume d'erreurs dans Sentry: 
On reçoit très régulièrement sur Sentry des erreurs de ce type pour les jobs 
`InboundWebhooks::RdvSolidarites::ProcessUserProfileJob` et `InboundWebhooks::RdvSolidarites::ProcessReferentAssignationJob`:   https://sentry.incubateur.net/organizations/betagouv/issues/123725/?environment=production&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
En investiguant j'ai remarqué que cela se produisait lorsque le référent ou l'organisation étaient assignés depuis l'interface de rdv-insertion: Comme ces assignations sont faites au sein de transaction sur rdv-i …
=> feat(jobs): filter rdvs webhooks sentry errors

app/jobs/alert_motif_category_has_changed_job.rb, spec/jobs/alert_motif_category_has_changed_job_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2353
=> ux(mattermost_notif): better motif category has changed alert on mattermost

app/controllers/users/orientations_controller.rb
Cette PR permet de n'afficher que les organisation issues du type "delegataire_rsa conseil_departemental france_travail" dans la liste des structures référentes
fix https://github.com/gip-inclusion/rdv-insertion/issues/2367
=> fix(orientation): only display relevant orgs in orientation structure select

app/views/website/static_pages/welcome.html.erb
close https://github.com/gip-inclusion/rdv-insertion/issues/2376
close https://github.com/gip-inclusion/rdv-insertion/issues/2354
On change les CTA en dessous du titre et en bas de la page (démo)
On cible le RSA dans la phrase d'accroche
On rajoute 'en masse' pour l'envoi des mail et SMS
https://github.com/user-attachments/assets/51e402fb-dcec-4efc-ac63-322845e4f157
=> ui(landing): change cta disposition and some wording

.buildpacks, Procfile
close https://github.com/gip-inclusion/rdv-insertion/issues/2304
Pour activer jemalloc dans scalingo il faut ajouter la variable d'environnement `JEMALLOC_ENABLED` à `true`.
C'est ce que j'ai fait sur staging, il faudra le faire sur les autres environnements quand on déploiera.
On pourrait aussi le faire au niveau du/des container dans le procfile : 
ex : `web: jemalloc.sh bundle exec puma -C config/puma.rb`
La doc scalingo se trouve [ici](https://doc.scalingo.com/platform/deployment/buildpacks/jemalloc).
Pour s'assurer que jemalloc fonctionne bien et avoir accès à plein de stats on peut lancer la commande suivante en bash sur les vm scalingo : 
```MALLOC_CONF=stats_print:true ruby -e \"exit\"```
Ci dessous, pour comparaison ultérieure les graphs mémoire de nos conteneurs scalingo entre …
=> tech(perf): improve memory usage with jemalloc

app/jobs/send_creneau_availability_alert_job.rb, spec/jobs/send_creneau_availability_alert_job_spec.rb
cette PR fait en sorte de ne pas envoyer la notif de créneaux indispo a des orgs n'ayant pas d'agents, pour éviter ceci dans sidekiq :
=> fix(notif): prevent sending notifs to empty orgs

app/views/website/teleprocedure_landings/show.html.erb, spec/controllers/website/teleprocedure_landings_controller_spec.rb
Cette PR corrige un problème avec l'usage de l'API lookup_context qui empêche de détecter la présence des partials depuis qu'on les a mis dans un dossier website
fix https://mattermost.incubateur.net/betagouv/pl/t1ra81gfhpysfdpffifoa5t13o
=> fix(teleprocedure): partial finding

app/controllers/concerns/current_structure.rb, app/helpers/application_helper.rb
Cette PR permet de ne pas afficher le bandeau de navigation par orga lorsque l'on a pas choisi d'organisation
Devrait au passage fixer https://github.com/gip-inclusion/rdv-insertion/issues/2391
=> fix(redirect): prevent navigation redirection

app/jobs/remove_organisation_user_for_expired_archive_job.rb, app/jobs/remove_organisation_users_for_expired_archives_job.rb, config/schedule.yml, spec/jobs/remove_organisation_user_for_expired_archive_job_spec.rb, spec/jobs/remove_organisation_users_for_expired_archives_job_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2290
On log une erreur si l'organisation de l'archive ne contient pas d'agent (nécessaire pour la connexion à rdvsp).
En lien avec cette PR il y a cette issue qu'on pourra traiter (dans une autre pr) : https://github.com/gip-inclusion/rdv-insertion/issues/2422
=> rgpd(archives): remover users from organisations after 2 years of archiving

app/javascript/controllers/index_filters_controller.js, app/javascript/stylesheets/components/_index_filters.scss, app/views/users/_users_list_header.html.erb
close https://github.com/gip-inclusion/rdv-insertion/issues/2373
On ajoute le bouton "Voir moins de filtres" quand la liste des tags est déroulée
Avant | Après
:- | -:
"Voir plus de filtres" ne change pas.
=> ux(filters): add collapse button for filters in index

app/javascript/stylesheets/components/_index_filters.scss
=> fix(ux): better display for less tag filter

app/helpers/impersonation_helper.rb, app/javascript/components/confirm-modal.js, app/views/category_configurations/index.html.erb, app/views/common/_rdvs_impersonation_warning.html.erb, app/views/convocations/new.html.erb, app/views/follow_ups/_follow_up.html.erb, app/views/users/_find_rdv_button.html.erb, app/views/users/_users_list_header.html.erb
Cette PR ajoute une modale de confirmation lors d'un clic sur un lien rdvs et que l'on est connecté "en tant que". 
Je tire parti de la logique associée aux modales de confirmation existantes en ajoutant la possibilité de demander une confirmation sur un lien externe à l'application. 
Pour info j'ai décidé de ne pas mettre l'illustration dans la modale car elle demandait du code spécifique, je trouve pas que ce soit une bonne utilisation de notre temps que d'en consacrer au design de cette modale 100% spécifique aux super admin, donc à nous en interne
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2254
=> feat(impersonate): add impersonation warning

.husky/pre-commit
En travaillant sur https://github.com/gip-inclusion/rdv-insertion/pull/2426, je me suis souvent retrouvé à travailler uniquement sur des fichiers ruby/html, et à avoir le hook de précommit pour linter le js qui tourne alors qu'aucun fichier n'a été modifié.
Ça ajoute un peu de friction entre le commit et le push, d'où la proposition de cette pr de ne faire tourner le linter que si les fichiers ont été modifiés.
=> tech(lint) Avoid unnecessary eslint runs in precommit hooks

app/services/users/validate.rb
closes #2402 
Lorsqu'on essayait de créer un usager avec un faux numéro de téléphone, `@user.phone_number` était présent alors que `@user.phone_number_formatted` était `nil`.
Du coup dans le service `Users::Validate`, la méthode `validate_phone_number_and_first_name_uniqueness` était appelé dans ce cas, or elle fait une recherche dans la bdd via le `phone_number_formatted`. Du coup on cherchait des usagers qui avait le même prénom que l'usager qu'on était en train de créer et dont le numéro de téléphone est `nil`. On en trouvait donc beaucoup, ce qui faisait échouer le serivce `Users::Validate`.
On appelle `validate_phone_number_and_first_name_uniqueness` que si le numéro de téléphone formatté (celui qui sera sauvé en db) est présent.
=> fix(users): Validation de l'usager sur le phone_number_formatted

app/controllers/users/orientations_controller.rb, app/controllers/users_organisations_controller.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job.rb, app/jobs/send_creneau_availability_alert_job.rb, app/models/agent_role.rb, app/models/concerns/organisation/archivable.rb, app/models/organisation.rb, config/anonymizer.yml, db/migrate/20241031161416_add_deleted_at_to_organisations.rb, db/schema.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job_spec.rb, spec/models/agent_role_spec.rb, spec/models/organisation_spec.rb
closes #2393 
Je mets en place ici une logique d'archivage des orgas pour les orgas qui ne sont plus utilisées.
Pour se faire j'ajoute une colonne `archived_at` aux `organisations` et que je set d'emblée pour toutes les organisations qui n'ont pas d'agents.
Je mets également en place une règle de validation simple: **Une organisation ne peut être archivée que si elle a été vidée de ses agents**
En effet sinon cela nous amènerait à gérer dans l'appli les orgas archivées auxquelles les agents appartient, ce qui compliquerait grandement les choses: il faudrait ne pas les afficher pour l'agent, les filtrer au moment de l'invitation etc. 
Or une organisation archivée n'a pas vocation à être utilisée par un agent.
=> Du coup la plupart des cas sont déjà réglés par la logique d'appartenance de …
=> feat(organisations): Mark organisation as archived

lib/mailer_previews/invitation_preview.rb, lib/mailer_previews/notification_preview.rb
Dans le code permettant de générer dynamiquement des méthodes permettant de visualiser des previews, les messages pointaient tous vers le même template.
C'était parce que les block appelés par `define_method` ne sont appelés qu'une fois qu'on appelle la méthode en question et pas au moment d'itérer sur les `motif_categories`.
Ainsi ils faisaient tous référence à la même catégorie de motif, la dernière de la boucle.
Je fix ça en passant la catégorie de motif par valeur au sein du block passé à `define_method` et non plus par référence à l'extérieur du block.
=> fix(preview): Fix mailer preview generation

app/jobs/application_job.rb, app/jobs/concerns/locked_and_ordered_jobs.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_referent_assignation_job.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_user_profile_job.rb, app/jobs/invite_user_job.rb, app/jobs/notify_participation_to_user_job.rb
Certains webhooks de rdvs prennent du temps à être processés lorsque ce sont des webhooks de rdvs collectifs notamment.
Comme les jobs sont "lockés" pour un même rdv, si on reçoit beaucoup de webhooks pour le même rdvs on va avoir beaucoup dde jobs qui vont raise une erreur `WithAdvisoryLock::FailedToAcquireLock` et s'empiler dans le retry set.
J'applique donc le mécanisme d'ordering des jobs pour ne pas exécuter le job si on a déjà traité un webhook postérieur.
J'en profite pour préfixer ces clés redis par "lock" pour éviter la confusion parce que je me suis rendu compte qu'il y avait beaucoup de clé redis qui commencent par le nom du job (probablement par sidekiq / active job)
=> fix(jobs): Order rdv jobs

app/controllers/concerns/turbo_stream_concern.rb, app/controllers/invitations_controller.rb, app/views/common/_custom_errors_modal.html.erb
Le titre de la modale des erreurs customs était en dur et donc pas vraiment custom... 😄
=> ux(fix): make custom errors modal title dynamic

app/policies/archive_policy.rb, app/policies/category_configuration_policy.rb, app/policies/department_policy.rb, app/policies/messages_configuration_policy.rb, app/policies/organisation_policy.rb, spec/controllers/invitations_controller_spec.rb, spec/features/agent_can_change_navigation_level_spec.rb
On a un bug qui est apparu suite à la refacto de la méthode `current_agent_department_organisations` dans #2404 .
En effet, `policy_scope(current_department.organisations)` retourne toutes les organisations de l'agent et pas celle du département seulement 😬 .
Ça a pour conséquence que toutes les organisations de tous les départements sont retournées dans la liste: 
Heureusement il n'y a que nous (les super admins) qui sommes sur plusieurs territoires donc le bug n'a à priori pas eu d'impact.
Je répare la manière dont est construit le scope erroné dans l'`OrganisationPolicy` ainsi que dans les autres policies en faisant appel à la variable `scope` pour prendre en compte la requête passée en argument de la méthode `policy_scope`.
=> fix(policy): Fix scope in policies

app/controllers/carnet_de_bord/carnets_controller.rb
Nous avons eu une erreur parce qu'un message flash contenait un array: https://sentry.incubateur.net/organizations/betagouv/issues/131663/?referrer=webhooks_plugin
Je répare ça ici :).
=> fix(flash): Fix flash message error

app/controllers/super_admins/webhook_endpoints_controller.rb, app/dashboards/webhook_endpoint_dashboard.rb, app/views/super_admins/webhook_endpoints/_collection_item_actions.html.erb, config/locales/models/webhook_endpoint.fr.yml, config/routes.rb
Cette PR ajoute une interface permettant de visualiser la liste des webhooks et de dupliquer un webhook existant en l'ajoutant à une organisation donnée :
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2412
=> feat(superadmin): add ability to duplicate webhook

app/clients/rdv_solidarites_client.rb, app/controllers/application_controller.rb, app/controllers/invitations_controller.rb, app/controllers/users/rdvs_controller.rb, app/controllers/users/referent_assignations_controller.rb, app/controllers/users_organisations_controller.rb, app/jobs/import_user_associations_from_rdv_solidarites_job.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/models/rdv_solidarites/referent_assignation.rb, app/models/user.rb, app/services/rdv_solidarites_api/retrieve_user_referent_assignations.rb, app/services/users/import_associations_from_rdv_solidarites.rb, app/services/users/push_to_rdv_solidarites.rb, app/services/users/save.rb, spec/controllers/users_controller_spec.rb, spec/controllers/users_organisations_controller_spec.rb, spec/features/administrate/super_admin_can_manage_users_spec.rb, spec/features/agent_can_create_user_through_form_spec.rb, spec/features/agent_can_update_contacts_info_spec.rb, spec/features/agent_can_update_user_through_form_spec.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb, spec/lib/users/transfer_organisation_spec.rb, spec/models/user_spec.rb, spec/services/rdv_solidarites_api/retrieve_user_referent_assignations_spec.rb, spec/services/users/import_associations_from_rdv_solidarites_spec.rb, spec/services/users/push_to_rdv_solidarites_spec.rb, spec/services/users/save_spec.rb, spec/support/stub_helper.rb
closes #2396 
On avait en sorte dans #2369 de récupérer les organisations des usagers qui ont été créés sur RDV-SP puis importé sur rdv-i parce qu'ils avaient un rdv sur une orga gérée sur rdv-i sur une catégorie gérée sur leur orga.
On s'est rendu compte qu'il y avait un autre cas où on importait des usagers déjé créés sur RDV-SP, c'est lorsque le mail est déjà pris dans RDV-SP (et que la personne n'est pas déjà sur rdv-i). Du coup il fallait importer les organisations de ces usagers lorsqu'on les crée sur rdv-i.
En plus des organisations, il se peut que ces usagers aient déjà des référents assignés sur RDV-SP avant leur importation sur RDV-I. Il faut importer les référents de l'usager également.
Je discute de l'implémentation choisie ici en analysant commit par commit. 
Je renomme le …
=> feat(sync): Import user associations from rdvsp on creation

db/migrate/20241120140423_add_indexes_on_orientations.rb, db/schema.rb
Cette PR ajoute un index sur les champs starts_at et ends_at de la table orientations. 
Comme on peut [le voir dans skylight](https://www.skylight.io/app/applications/lsTKL2LytCi4/recent/6h/endpoints/UsersController%23index?responseType=html) 
Les percentiles les plus lents de cette requête HTTP sont causés par le `SELECT` sur la table orientations. 
Mis à part quelques filtrages sur les users la complexité de cette requête est causé par l'absence d'index sur les champs `starts_at` et `ends_at` sur lequels on applique les opérateurs `<=` et `>=` 
J'ai ajouté un index basique avec le type par défaut Btree étant donné que ce type d'index s'applique parfaitement à ces types d'opérateurs (cf : https://www.postgresql.org/docs/14/indexes-types.html)
> B-trees can handle equality and range …
=> perf(orientations): add missing index

app/jobs/import_user_associations_from_rdv_solidarites_job.rb
Répare cette erreur sur sentry: https://sentry.incubateur.net/organizations/betagouv/issues/133840/?project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
Il me semblait que les appels à l'API RDV-SP lancées par le service `Users::ImportAssociationsFromRdvSolidarites` n'appelaient pas de policies côté RDV-SP puisque ce sont des endpoints scopés rdv-insertion. 
Mais [l'endpoint](https://github.com/betagouv/rdv-service-public/blob/cd51b9487ca6c65e8fbfeb9d6bc8b396e813e1dc/app/controllers/api/rdvinsertion/users_controller.rb#L12) récupérant le `user` (et ses organisations) check que l'agent qui appelle a des organisations en commun avec l'usager.
En attendant de peut-être revoir ces policies côté rdv-sp au moment où on fera une séparation + nette entre les …
=> fix(sync): Choose agent from user org when importing associations

app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/models/department.rb, app/views/users/_users_list_header.html.erb
Cette PR enlève la requête un peu lourde permettant d'afficher ou non le filtre par type d'orientation. 
Désormais le filtre sera toujours visible même si la structure n'utilise pas les orientations. 
On peut faire un compromis entre les deux en faisant par exemple 
```ruby
current_structure.orientations.any?
```
ce qui serait moins lourd mais permettrait au moins de ne pas afficher pour les départements et orgas qui n'utilisent pas du tout les orientations
[Solution proposée ci-dessus mise en place suite à discussion sur Mattermost]
=> perf(index): remove condition to display orientation filter

app/jobs/send_invitation_reminders_job.rb, app/jobs/send_periodic_invites_job.rb, spec/jobs/send_periodic_invites_job_spec.rb
closes #2444 
On a remarqué qu'il y avait certaines invitations périodiques qui sont lancée alors que l'usager a reçu une invitation pas longtemps avant. 
C'est parce que quand la périodicité est choisie sur un jour dans le mois (`day_of_the_month_periodic_invites`), on ne vérifiait pas que l'usager n'avait pas reçu d'invitations pas longtemps auparavant. 
Il y avait aussi rien d'explicite dans le code qui s'assurait qu'on envoyait pas des reminder sur des invitations périodiques. 
Dans les faits c'est rare parce qu'on envoie pas de reminder sur les invitations qui n'expirent jamais (ce qui devrait être le cas pour toutes les invitations périodiques), mais ce n'est pas le cas tout le temps (+ de détails à ce sujet dans lla dernière partie de la description). 
* J'ajoute une condition pour …
=> feat(invitations): Do not send periodic invites in some cases

app/views/users/_user_icon.html.erb, app/views/users/_user_page_header.html.erb
En product backlog Samantha et Amaury ont fait la remarque qu'il valait mieux ne pas avoir d'icônes du tout à côté du nom de l'usager.
=> feat(user): Remove user icon

app/clients/mattermost_client.rb, app/services/concerns/notifications/sender_phone_number_validation.rb, spec/services/notifications/send_email_spec.rb
On a ces remontées dans sentry
https://sentry.incubateur.net/organizations/betagouv/issues/125507/events/645906f537274c8fa847ad3ed7072183/?project=16&referrer=previous-event&statsPeriod=24h&stream_index=7
Le fail du job et les remontée sont voulus (suite au travail fait ici https://github.com/gip-inclusion/rdv-insertion/pull/2274)
On doit avoir des remontée d'info dans Mattermost pour que le support puisse contacter les organisations en question afin qu'ils renseignent un numéro de téléphone pour que les usagers puisse recevoir correctement les sms mais cette remontée Mattermost ne fonctionnait pas car n'était jamais appelé. C'est fix ici.
=> fix(mm): Mattermost alert for convocation send without org/lieu phone_number fixed

config/locales/views/kaminari-fr.yml
Suite au retour de Samantha sur les icones de la pagination, cette PR applique les icônes du DSFR (cf https://github.com/gip-inclusion/rdv-insertion/issues/2414#issuecomment-2514682329)
=> fix(icons): apply correct kaminari icons

spec/features/agent_can_edit_category_configuration_spec.rb, spec/features/agent_can_edit_organisation_spec.rb
Cette PR ajoute des tests e2e à la feature d'édition de category configuration
fix https://github.com/gip-inclusion/rdv-insertion/issues/921
=> spec(category_configuration): ensure category configuration edition works

app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb
closes #2516 .
Il arrive que certains usagers soient supprimés, puis qu'on les recrée si on process un webhook de rdv associé après la suppression de ces usagers.
Comme il n'y a rien qui nous garantisse qu'un webhook de rdv ne soit pas processé après le webhook de suppression de l'usager, je fais en sorte de vérifié que les usagers qu'on importe n'ont pas déjà été supprimé auparavant (grâce à la colonne `old_rdv_solidarites_user_id`)
=> fix(webhooks): Do not import already deleted users

config/application.rb
Je suis tombé sur ce bout de code ajouté dans #1776 et censé disparaitre après la migration.
Du coup je me suis permis de l'enlever.
=> fix(app): remove temporary code

app/views/users/_search_form.html.erb
Cette PR permet de ne pas rechercher dans les motifs mais de réinitialiser le motif lorsque l'on recherche 
fix https://github.com/gip-inclusion/rdv-insertion/issues/2501
=> feat(users): do not search in motif

app/models/user.rb, spec/factories/tag_users.rb, spec/features/agent_can_edit_uploaded_user_list_spec.rb, spec/models/user_spec.rb
Cette PR permet d'éviter de lever la contrainte d'unicité lorsque l'on reçoit dans les nested attributes des éléments déjà présent en base de données. 
De plus cette PR permet de dédupliquer les éléments reçus si jamais le array d'attributes contient des tag_id dupliqués. 
En effet 2 cas se détachent qui pourraient amener à ces erreurs https://sentry.incubateur.net/organizations/betagouv/issues/141816/?project=16&referrer=webhooks_plugin
Le premier consiste à updater un user qui possède déjà le tag 1 en lui donnant `tag_users_attributes: [{ tag_id: 1 }]`
Le second consiste à créer (ou updater) un user en lui donnant dès sa création `tag_users_attributes: [{ tag_id: 1 }, { tag_id: 1 }]`
Cette PR fixe donc ces 2 cas ou la combinaison des deux
=> fix(tag): prevent crashing when receiving dupes

.env.test, .github/workflows/ci.yml, app/controllers/users/orientations_controller.rb, app/views/users/orientations/create.turbo_stream.erb, app/views/users/orientations/user_added_notifications/_form.html.erb, spec/features/agent_can_add_user_orientations_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2450
On met en place une pop-in d’envoi d’email depuis l’onglet “parcours” lorsqu'on ajoute un parcours dans une autre organisation. Cette modale s'affiche si l'usager ne fait pas déjà parti de l'organisation concernée par le parcours.
Plutôt que de surcharger le contrôleur j'ai préféré mettre le code dans le fichier turbo stream [app/views/users/orientations/create.turbo_stream.erb](https://github.com/gip-inclusion/rdv-insertion/pull/2512/files#diff-12931bfc917b60d1329f05b6e4eda9445ebc70d5df114f84dc75057b278b2277).
On utilise un form spécifique d'envoi d'email car le contenu change et en désactive la possibilité de mettre une PJ.
=> feat(orientation): add organisation email notification modal on orientation create

app/services/concerns/notifications/sender_phone_number_validation.rb, spec/services/notifications/send_email_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2546
En plus de ce qui était demandé dans l'issue je me suis permis de laisser entre parenthèses les ids du rdv et de l'usager. Ca donne :
"Un rendez-vous de convocation (54321) a été placé pour cet usager (12345) mais la convocation n'a pas été envoyée car l'organisation _NOM de l'orga_ n'a pas de numéro de téléphone."
=> wording(alert): change mm alert wording in case of convoc rdv without phone

app/controllers/concerns/users/filterable.rb, app/helpers/users_helper.rb, app/javascript/stylesheets/_variables.scss, app/javascript/stylesheets/pages/_users.scss, app/views/users/_active_filters_recap.html.erb, app/views/users/_filter_by_creation_dates_button.html.erb, app/views/users/_filter_by_invitation_or_convocation_dates_button.html.erb, app/views/users/_filter_by_orientation_type_button.html.erb, app/views/users/_search_form.html.erb, app/views/users/_users_list_header.html.erb, app/views/users/index.html.erb, spec/controllers/users_controller_spec.rb
Cette PR ajoute un visuel sur la recherche en cours avec la possibilité de réinitilialiser les filtres individuellement et également de modifier à partir de la recherche en cours. 
On retrouve aussi un petit badge montrant les filtres actifs au niveau des filtres en eux même
fix https://github.com/gip-inclusion/rdv-insertion/issues/2504
=> feat(search): add active search view

.github/workflows/ci.yml
Le passage en 24.04 des os des CI Github (https://github.com/actions/runner-images/issues/10636) n'a pas du tout plu à wkhtmltopdf (qui n'est plus maintenu). On fix ici la version ubuntu de la ci en attendant de se débarasser de wkhtmltopdf.
=> tech(ci): fix ubuntu version in ci to 22.04 to keep  wkhtmltopdf compatible

app/controllers/brevo/ip_whitelist_concern.rb, app/controllers/brevo/mail_webhooks_controller.rb, app/controllers/brevo/sms_webhooks_controller.rb, app/services/inbound_webhooks/brevo/assign_delivery_status_and_date_base.rb, app/services/inbound_webhooks/brevo/assign_mail_delivery_status_and_date.rb, app/services/inbound_webhooks/brevo/assign_sms_delivery_status_and_date.rb, spec/controllers/brevo/ip_whitelist_shared.rb, spec/controllers/brevo/mail_webhooks_controller_spec.rb, spec/controllers/brevo/sms_webhooks_controller_spec.rb, spec/rails_helper.rb, spec/requests/brevo_mail_webhooks_spec.rb, spec/requests/brevo_sms_webhooks_spec.rb, spec/services/inbound_webhooks/brevo/assign_mail_delivery_status_and_date_spec.rb, spec/services/inbound_webhooks/brevo/assign_sms_delivery_status_and_date_spec.rb, spec/support/brevo_ip_helper.rb
Cette PR ajoute un whitelisting sur les IPs données par Brevo pour s'assurer que les calls sont légitimes. 
Je rajoute aussi la possibilité de désactiver temporairement le whitelisting à l'aide d'une variable d'environnement au cas où Brevo décide soudainement d'envoyer ses calls depuis une autre IP. 
Je lève également une alerte Sentry si cela arrive où si quelqu'un nous appelle cet endpoint d'une façon où d'une autre. 
fix https://github.com/gip-inclusion/rdv-insertion/issues/2415
=> feat(brevo): make sure webhooks come from brevo

db/schema.rb
Répare cette erreur sur Sentry: https://sentry.incubateur.net/organizations/betagouv/issues/142388/?project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=9
j'avais fait en sorte dans #2434 de spécifier dans le model `parcours_document` que l'appartenance à un agent était optionnel dans le cas où celui-ci était supprimé, mais je n'avais pas fait la migration associée que je fais ici.
=> fix(migration): Remove null constraint on agent_id for parcours_documents

app/views/users/_search_form.html.erb
Cette PR permet de formatter correctement les params tag_ids. 
En effet ce param étant un array il était envoyé dans les params du form de recherche comme une value string classique. 
Pour info, il est impossible de simplement le passer dans l'url du form plutôt que comme un input dans le body du form à cause du fonctionnement intrinsèque des form HTML : https://stackoverflow.com/questions/1116019/when-submitting-a-get-form-the-query-string-is-removed-from-the-action-url
Le form HTML en méthode GET ne fait pas qu'overrider les params donnés en query, il les enlève completement, ce qui implique donc de reconstruire entièrement les params. 
Le bug a été rendu visible par cette PR : https://github.com/gip-inclusion/rdv-insertion/commit/2ce1157127f826a94118d34b197e12c426a580e6
```ruby …
```
=> fix(users): prevent sending tag_ids as string

app/javascript/controllers/crisp_controller.js, app/views/common/_crisp.html.erb
Cette PR règle 2 problèmes : 
- Un problème d'incompatibilité entre Turbo et Crisp ([voir l'issue ici](https://github.com/crisp-im/crisp-sdk-web/issues/39))
- Ne pas appeler la méthode logout quand ce n'est pas nécessaire (quand l'agent n'est pas encore connecté)
=> crisp(bug): fixing incompatibility with turbo and logoff only when needed

Gemfile.lock, app/controllers/csv_exports_controller.rb, app/views/mailers/csv_export_mailer/notify_csv_export.html.erb
Je faisais quelques checks pré bug bounty et je me suis rendu compte que: 
- on faisait toujours une vérif sur l'`id` en plus du `signed_id` pour l'export csv. Ça n'a pas de conséquences puisqu'on check l'autorisation sur l'export après mais j'enlève la vérif sur l'`id` qui n'est plus supportée
- on ne nettoyait pas les params que l'on ajoute dans le contenu d'export de csv. Là encore ça n'a pas de conséquences puisque la personne à l'origine de l'envoi de ce mail est la personne le recevant, mais je nettoie au cas où
=> fix(csv): sanitize csv export params

app/jobs/notify_unavailable_creneau_job.rb, app/services/invitations/aggregate_invitation_without_creneaux_by_category.rb, spec/jobs/notify_unavailable_creneau_job_spec.rb, spec/services/invitations/aggregate_invitation_without_creneaux_by_category_spec.rb
Dans cette PR je fais en sorte d'exclure les invitations qui n'expirent pas des messages d'alerte envoyés aux organisations.
J'ai également ajouté un renommage de la classe `VerifyOrganisationCreneauxAvailability` qui réellement ne vérifiait pas mais aggregait. 
Ça me semble beaucoup plus lisible de cette façon
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2551
=> fix(creneaux_unavailable): avoid taking expireable invites into account

spec/features/agent_can_upload_user_list_spec.rb
Suite à #2654 , le test faisait qu'on ajouter du contenu à la cellule plutôt que de changer le contenu de la cellule.
=> fix(spec): Fix failing test after cell edit

app/controllers/application_controller.rb, app/controllers/concerns/current_structure.rb, app/controllers/concerns/modal_agreements_concern.rb, app/controllers/website/static_pages_controller.rb, config/routes.rb
Nous avions un bug qui faisait qu'un agent connecté avait une erreur de redirections infinie dès lors qu'il essayait d'accédait à une page d'une structure à laquelle il n'était pas autorisé.
Cela se produisait comme suit: 
- l'agent essaie d'accéder à une page d'une structure non autorisé
- l'agent est redirigé vers le `root_url` (`StaticPagesController#welcome`)
- l'agent est alors redirigé vers l'index des organisations 
- la méthode `current_organisation` était appelée via le before_action `:set_should_display_accept_dpa` dans le `ModalAgreementConcern`. [Cette ligne](https://github.com/gip-inclusion/rdv-insertion/commit/29ebb20d1c42e4ce613bb7fb5f7bcb0e804089aa) n'a pas besoin d'être appelée puisqu'on fait un check sur la présence du `params[:organisation_id]` juste après
- La méthode …
=> fix(app): Infinite redirects bug

app/helpers/users_filters_helper.rb, app/helpers/users_helper.rb, app/views/users/_active_filters_recap.html.erb, app/views/users/_filter_by_creation_dates_button.html.erb, app/views/users/_filter_by_invitation_or_convocation_dates_button.html.erb, app/views/users/active_filters_recap/_convocation_date.html.erb, app/views/users/active_filters_recap/_creation_date.html.erb, app/views/users/active_filters_recap/_first_invitation_date.html.erb, app/views/users/active_filters_recap/_last_invitation_date.html.erb, app/views/users/active_filters_recap/_tag_ids.html.erb, spec/controllers/users_controller_spec.rb, spec/features/agent_can_visualize_active_filters_on_index_page_spec.rb
Cette PR améliore le visuel des filtres actifs en gérant mieux les filtres par dates. 
J'ai adapté le test associé, bon je suis pas hyper satisfait de ce test mais il fait le job
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2588
=> fix(users): improve active filters visuals

app/helpers/application_helper.rb, app/helpers/super_admin_header_helper.rb, app/helpers/tooltip_helper.rb, app/javascript/controllers/super_admin_header_controller.js, app/views/common/_header_super_admin_bar.html.erb, app/views/common/_header_super_admin_bar_impersonated.html.erb, package.json, yarn.lock
Closes #2491 .
J'en avais marre de voir l'animation sur le bandeau super admin à chaque fois que je naviguais sur l'appli du coup j'ai décidé de faire un fix 😂 . 
Pour se faire j'utilise les cookies plutôt que le local storage pour afficher/cacher le bandeau. Ainsi le bandeau est rendu ou caché par le html renvoyé par le serveur.
J'ajoute la libraire "js-cookie" pour manipuler les cookies de manière plus sûr et plus sereine. 
J'aurais éventuellement pu ajouter des routes côté serveur pour faire ça côté serveur plutôt que côté client mais: 
- on ne bénéficierait plus de l'animation
- ça complexifierait possiblement le code
J'en profite pour faire un peu de ménage dans `ApplicationHelper` pour extraire des helpers séparés.
=> fix(super_admin): Super admin header improvement

app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/models/concerns/user/creation_origin.rb, app/models/user.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb, spec/models/user_spec.rb
Depuis #2642 , il n'y a qu'un seul moyen d'importer un usager déjà créé sur rdv-sp, c'est qu'il soit créé via les webhooks de rdvsp.
Du coup j'enlève l'accessor `import_associations_from_rdv_solidarites_on_create` qui servait à flagger les usagers dont on devait importer les associations, puisque ces usagers sont maintenant les usagers créé par les webhooks rdv-sp.
=> fix(user): Remove unnecessary logic when importing user

app/models/agent.rb, app/models/dpa_agreement.rb, config/anonymizer.yml, db/migrate/20250227134523_add_dpa_identity_to_dpa_agreement.rb, db/schema.rb, spec/models/agent_spec.rb, spec/models/dpa_agreement_spec.rb
Cette PR permet de stocker l'identité de la personne qui valide le DPA. 
En complément je ferai tourner le code suivant sur la prod une fois déployé : 
```ruby
DpaAgreement.all.find_each do |dpa_agreement|
dpa_agreement.touch
end
```
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2645
=> feat(dpa): store agent identity

app/models/category_configuration.rb, spec/factories/creneau_availability.rb, spec/models/category_configuration_spec.rb
Cette PR permet de garantir qu'une CategoryConfiguration puisse être supprimée en précisant que les creneaux associés doivent être également supprimés. 
Fix https://mattermost.incubateur.net/betagouv/pl/nk3ndsifmjf9xkfsmf5s8pka1w
=> fix(creneaux): ensure category configuration remains destroyable

.github/workflows/ci.yml
Il semble qu'il y ait eu un changement dans la dernière version du driver de chrome qui fait que la version actuelle de selenium utilisée par capybara raise des erreurs (voir issue liée [ici](https://github.com/teamcapybara/capybara/issues/2800)).
Je m'inspire d'[un des commentaires](https://github.com/teamcapybara/capybara/issues/2800#issuecomment-2731100953) pour spécifier dans la CI que l'on utilise l'ancienne version de chrome pour pouvoir régler l'issue, le temps qu'un patch au niveau de la gem soit released.
=> fix(ci): Specify chrome version

app/models/application_record.rb, app/models/concerns/sanitizeable.rb, spec/features/agent_can_add_or_remove_user_from_organisations_spec.rb, spec/features/agent_can_assign_referents_spec.rb, spec/models/archive_spec.rb, spec/models/csv_export_spec.rb, spec/models/messages_configuration_spec.rb
Cette PR rajoute un hook global pour strip le contenu html de tout attribut string stocké en DB, évitant ainsi tout risque d'injection de code malveillant.
=> fix(xss): prevent any kind of xss injections

app/services/france_travail_api/create_participation.rb, app/services/france_travail_api/delete_participation.rb, app/services/france_travail_api/retrieve_access_token.rb, app/services/france_travail_api/retrieve_user_token.rb, app/services/france_travail_api/update_participation.rb, spec/services/france_travail_api/create_participation_spec.rb
On a des erreurs de compatibilité d'encodage des réponses FT depuis quelques jours (le 12 mars). Ils ont du changer leur encodage.
Cette PR force la conversion en UTF-8 pour ne pas que l'on ai de soucis à l'avenir.
https://sentry.incubateur.net/organizations/betagouv/issues/156159/?environment=demo&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0
=> bug(ft): fix encoding changes in ft apis causing jobs to fail

Gemfile.lock
J'ai un souci en local pour faire tourner l'appli à cause d'un conflit de version entre stringio en local et sur l'appli.
J'en profite pour directement mettre à jour la gem.
=> chore(deps): Update stringio

app/models/concerns/sanitizeable.rb, spec/models/archive_spec.rb
Sentry se fait flood car la sanitization enlève des éléments légitimes (sauts de ligne inutiles de window `\r`, whitespaces). 
Étant donné qu'il n'existe pas de moyens de rendre `ActionView::Base.full_sanitizer.sanitize` permissif sur ces éléments (on peut uniquement spécifier des tags autorisés, cf https://github.com/flavorjones/loofah/blob/main/lib/loofah/html5/safelist.rb, Loofah est la lib sous jacente), nous devons faire une pré-sanitization de la valeur à comparer pour s'assurer que la string une fois sanitized est réellement suspecte et mérite donc d'être envoyée sur Sentry. 
Sachant que la valeur originale peut-être un array ou une hash, je dois déplacer cette pré-sanitization au moment ou on itère réellement sur la string à changer pour y faire la comparaison à ce moment. 
La …
=> fix(xss): ensure we notify Sentry only when needed

app/models/user.rb, spec/models/user_spec.rb
Il y a eu des [changements récents](https://github.com/betagouv/rdv-service-public/pull/4945) coté rdvsp sur leur regexp de validation des emails.
Je copie le code de la regexp qu'ils utilisent pour qu'on ai le même comportement des 2 coté.
=> Fix(bug): use same validation email regexp as rdvsp

app/controllers/application_controller.rb, app/controllers/content_security_policy_controller.rb, app/controllers/super_admins/application_controller.rb, app/controllers/super_admins/blocked_invitations_counters_controller.rb, app/controllers/super_admins/blocked_users_controller.rb, app/controllers/website/stats_controller.rb, app/dashboards/user_dashboard.rb, app/javascript/controllers/csp_test_controller.js, app/javascript/controllers/super_admins/webhook_endpoints_controller.js, app/javascript/super_admin.js, app/views/content_security_policy/test.html.erb, app/views/layouts/_head.html.erb, app/views/layouts/super_admins/application.html.erb, app/views/sessions/new.html.erb, app/views/super_admins/webhook_endpoints/_collection_item_actions.html.erb, config/initializers/content_security_policy.rb, config/routes.rb, spec/features/administrate/super_admin_can_manage_users_spec.rb, spec/features/anyone_can_test_app_csp_spec.rb
Closes #2728 
Les CSP actuellement en place dans l'application sont beaucoup trop permissifs et ne protégent pas vraiment de contenus dangereux. 
Cela vient principalement du fait qu'il n'y a jamais eu d de consacrer du temps à ce sujet. 
* Les CSP ont été mis en place [il y a un an](https://github.com/gip-inclusion/rdv-insertion/pull/1968) et ne naissait pas d'une réflexion produit ou d'une décision technique mûrement réfléchie. Ils ont été activée rapidement au détour d'une issue.
* La mise en place des CSP a causé des problèmes d'affichages de certaines pages en prod (notamment les pages stats), et du coup [un hotfix](https://github.com/gip-inclusion/rdv-insertion/pull/1976) trop permissif a été appliqué. En effet, en ajoutant l'option `unsafe_inline` on devient trop vulnérable aux …
=> fix(app): Make CSP more secure

app/jobs/creneaux/store_number_of_creneaux_available_job.rb, app/services/creneaux/store_number_of_creneaux_available.rb, app/services/rdv_solidarites_api/retrieve_creneau_availability.rb, config/sidekiq.yml
Cette PR déplace le calcul des créneaux dispo dans une queue creneaux, empêche la parallélisation sur ce job et rajoute une limitation à 200 pour permettre d'accélerer le calcul et d'éviter les timeout. 
À merger après le déploiement de https://github.com/betagouv/rdv-service-public/pull/5194
=> fix(creneaux): limit creneaux relevant count to 200

app/jobs/inbound_webhooks/rdv_solidarites/process_user_job.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_user_job_spec.rb
Suite à la mise en place des `notification_email` on avait gardé le fonctionnement qui empêchait un email d'être nullifié dans rdvi si l'email est nullifié coté rdvsp (c'était pour éviter de perdre les emails des conjoints).
J'ai rattrapé tout les emails en prod (j'ai mis à jour les `notification_email` de rdvsp avec nos emails quand les usagers n'avaient pas d'email dans rdvsp mais qu'ils en avaient un chez nous) on peut donc enlever ce mécanisme qui est inutile et pourrait poser des problèmes de cohérence dans le cas ou l'email est update à nil coté rdvsp.
=> tech(clean/bug): clean old conjoint behavior

app/controllers/user_list_uploads/invitation_attempts_controller.rb, app/views/user_list_uploads/invitation_attempts/select_rows.html.erb, spec/features/agent_can_upload_user_list_spec.rb
Je change le name et l'id de l'input pour checker le format email qui était `email` pour éviter les interférences avec des extensions chrome qui target tous les `input[name="email"]`
=> fix(upload): Change checkbox name and id

app/services/user_list_upload/save_user.rb, spec/services/user_list_upload/save_user_spec.rb
https://sentry.incubateur.net/organizations/betagouv/issues/165632/?project=16&referrer=webhooks_plugin
Suite à https://github.com/gip-inclusion/rdv-insertion/pull/2754 un bug a été introduit dans les cas ou aucune catégorie de motif n'est sélectionnée `@follow_up` n'existe pas et on obtient une erreur `NoMethodError`
=> NewUpload(bug): fix undefined method closed? for nil (NoMethodError)

app/javascript/controllers/user_list_upload_controller.js, app/javascript/stylesheets/_variables.scss, app/javascript/stylesheets/components/_banner.scss, app/javascript/stylesheets/components/_color.scss, app/views/user_list_uploads/category_selections/_announcement_banner.html.erb, app/views/user_list_uploads/user_list_uploads/new.html.erb, app/views/users/_users_list_header.html.erb, app/views/users/uploads/_announcement_banner.html.erb
Cette PR ajoute un warning à l'ajout d'un fichier lorsqu'il contient plus de 500 lignes.
J'ajoute aussi un badge précédemment oublié au clic sur le bouton Ajouter un fichier
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2733
=> feat(upload): add warning when too many lines sent

app/models/concerns/user_list_upload/user_row/matching_user.rb, spec/models/concerns/user_list_upload/user_row/matching_user_spec.rb
Lorsqu'on récupère un matching user sur le nouvel upload, on avait pas d'ordre de priorité sur les critères de matching.
Je répare ça ici pour que les matchings  se fassent dans cet ordre: 
- sur le NIR
- sur l'id interne
- sur l'email + prénom
- sur le téléphone + prénom
- sur le num d'allocataire/rôle
=> fix(upload): Set matching user priority criterias

app/models/concerns/participation/france_travail_webhooks.rb, app/models/organisation.rb, spec/jobs/outgoing_webhooks/france_travail/create_participation_job_spec.rb, spec/jobs/outgoing_webhooks/france_travail/delete_participation_job_spec.rb, spec/jobs/outgoing_webhooks/france_travail/update_participation_job_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2746
Cette PR :
- Enlève la condition des code safir pour le déclenchement des webhooks FT.
- Les organisations doivent être de type `conseil_departemental` ou `delegataire_rsa` pour que les webhooks se déclenchent.
J'ai amélioré les tests et j'ai résolu un bug éventuel (dans le cas d'une suppression de participation ou l'organisation est éligible aux webhooks FT mais que la participation n'a pas de `france_travail_id`)
=> FT(api): remove safir_code condition for FT webhooks

config/initializers/content_security_policy.rb
Nous avons encore eu des reports  de violation de csp sur la page `/deployment_map` : https://sentry.incubateur.net/organizations/betagouv/issues/165520/?environment=production&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0&utc=true
Je tente de les résoudre ici en autorisant les uri commencant par `public.flourish.studio`  sur les images et les scripts
=> fix(csp): Add flourish csp

app/models/concerns/user_list_upload/user_row/matching_user.rb, db/migrate/20250415134038_add_missing_indices_on_users.rb, db/schema.rb, spec/models/concerns/user_list_upload/user_row/matching_user_spec.rb
Skylight pointe un gros souci de performance sur l'endpoint `user_rows#update` (voir image).
Ce qui prend le plus de temps est la requête sur les users qui est trigger au moment de retrouver un `matching_user` à l'update d'un `user_row`.  
Je fais un fix ici qui: 
- Ajoute des index aux users là où il n'y en a pas pour améliorer la performance de ces requêtes
- Rajoute une condition pour ne pas faire cette requête lorsque c'est inutile
=> fix(upload): Improve user_rows#update performance

app/helpers/user_list_upload/user_list_upload_helper.rb, app/models/user_list_upload/collection.rb, app/models/user_list_upload/user_row.rb, app/services/user_list_upload/save_user.rb, spec/services/user_list_upload/save_user_spec.rb
Suite à #2754 , on a changé la façon dont on créait le suivi dans le service `UserListUpload::SaveUser` en utilisant `FollowUp.find_or_create_by!`. Seulement cette ligne était appelée avant la sauvegarde de l'usager (au sein du service `Users::Save`).  Cela avait pour conséquence de sauvegarder le record `user` lorsque celui-ci n'était pas persisté avant l'appel au service en charge de sauvegarder ce record.
Du coup pour changer cela:
- Je réutilise la méthode `user#assign_motif_category` qui permet de build un `follow_up` qui va être persisté en même temps l'usager
J'en profite pour: 
- enlever les méthodes `reopen_follow_up_if_closed` et `unarchive_user_if_archived` de la transaction car cela ne devrait empêcher la sauvegarde l'usager.
- renommer les méthodes lié au `follow_up` du …
=> fix(upload): Refactor follow up assignement in upload

app/javascript/controllers/user_list_upload_controller.js, app/views/user_list_uploads/_search_form.html.erb, app/views/user_list_uploads/category_selections/new.html.erb, app/views/user_list_uploads/invitation_attempts/_all_invitations_sent_status.html.erb, app/views/user_list_uploads/invitation_attempts/_user_row_after_invitation.html.erb, app/views/user_list_uploads/invitation_attempts/_user_row_before_invitation.html.erb, app/views/user_list_uploads/invitation_attempts/_user_rows_after_invitation.html.erb, app/views/user_list_uploads/invitation_attempts/_user_rows_before_invitation.html.erb, app/views/user_list_uploads/invitation_attempts/index.html.erb, app/views/user_list_uploads/invitation_attempts/select_rows.html.erb, app/views/user_list_uploads/user_list_uploads/_enrich_with_cnaf_button.html.erb, app/views/user_list_uploads/user_list_uploads/_user_row.html.erb, app/views/user_list_uploads/user_list_uploads/_user_row_details.html.erb, app/views/user_list_uploads/user_list_uploads/_user_rows.html.erb, app/views/user_list_uploads/user_list_uploads/new.html.erb, app/views/user_list_uploads/user_list_uploads/show.html.erb, app/views/user_list_uploads/user_save_attempts/_all_saves_attempted_status.html.erb, app/views/user_list_uploads/user_save_attempts/_user_row.html.erb, app/views/user_list_uploads/user_save_attempts/_user_rows.html.erb, app/views/user_list_uploads/user_save_attempts/index.html.erb, app/views/users/_all_users_table.html.erb
https://github.com/gip-inclusion/rdv-insertion/issues/2710
Je propose dans cette PR la mise en place des ids sur le parcours du nouvel upload.
Matomo est actuellement assez peu utilisé et pas vraiment paramétré pour un tracking précis des éléments.
Avant d'ajouter plus d'id dans l'application, je pense qu'il est préférable d'itérer sur ce sujet en fonction des premiers retours de la configuration Matomo. Les ids mis en place sur le nouvel upload dans cette PR vont nous permettre de nous faire la main sur ce sujet.
=> NewUpload(matomo): add ids on elements for matomo tracking

.env.test, app/models/concerns/participation/france_travail_webhooks.rb
Les tests étant concluants pour le Loiret, on active pour tout le monde en enlevant la condition qui permettait de filtrer sur les numéros des départements. FT est prévenu, à merge en prod le mardi 22 avril.
=> FT(api): remove department restrictive condition for france travail webhooks

app/jobs/destroy_old_ressources_job.rb, app/models/concerns/participation/france_travail_webhooks.rb, app/models/concerns/rgpd_destroyable.rb, app/models/user.rb, spec/models/participation_spec.rb
Je fais un fix suite à cette erreur remontée sur sentry: https://sentry.incubateur.net/organizations/betagouv/issues/169065/?environment=production&project=16&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=5&utc=true
Il se peut, dans de très rares cas (17 rdvs au total dans notre BDD) qu'il n'y ait pas d'organisation associé à un rdv. C'est certainement que l'organisation été supprimée sans supprimer les rdvs au préalable, or comme nous avions un `dependent: :nullify` sur l'association organisation -> rdvs, ces rdvs se retrouvent sans `organisation_id`. 
Pour régler le souci:
- Je fais en sorte de conditionner l'envoi de webhooks FT à la présence d'une orga associée pour ne plus lever cette erreur
- Je fais en sorte que ça ne se reproduise plus en changeant …
=> fix(webhooks): Ignore FT webhooks for rgpd destroys

app/models/user_list_upload.rb, spec/models/user_list_upload_spec.rb
Comme pour les tags, je fais en sorte que les référents assignables via l'upload soient scopés aux organisations liées à l'upload.
=> feat(upload): Restrict referent assignations to upload organisations

app/jobs/outgoing_webhooks/france_travail/base_job.rb, app/models/concerns/participation/france_travail_payload.rb, app/services/france_travail_api/retrieve_user_token.rb, spec/jobs/outgoing_webhooks/france_travail/update_participation_job_spec.rb, spec/services/france_travail_api/retrieve_user_token_spec.rb
Suite à l'ouverture de l'envoi de tous les rdvs vers France Travail, nous sommes tombés sur certains cas d'erreurs que l'on voudrait anticiper et mieux gérer.
Nous avons certains cas où les rdvs n'ont pas d'agents associés, et donc `agents.first.email` raise une erreur dans le module `Participation::FranceTravailWebhooks`: https://www.rdv-insertion.fr/sidekiq/retries/1745510715.5825472-db32e50afa2bc339f95672dc . 
[Je fais en sorte d'utiliser un safe operator ](https://github.com/gip-inclusion/rdv-insertion/commit/89207f043259ec7dfba83134da5f91f8f9fab0dc) et de quand même envoyer le rdv puisque sur la documentation, j'ai l'impression  que l'interlocuteur n'est pas `required`. Qu'en penses-tu @Holist ?
Dans certains cas l'API recherche usager renvoie un code "S003" signifiant que plusieurs …
=> fix(ft): handle ft error codes

app/views/mailers/notification_mailer/by_phone_participation_created.html.erb, app/views/mailers/notification_mailer/by_phone_participation_reminder.html.erb, app/views/mailers/notification_mailer/by_phone_participation_updated.html.erb, app/views/mailers/notification_mailer/presential_participation_created.html.erb, app/views/mailers/notification_mailer/presential_participation_reminder.html.erb, app/views/mailers/notification_mailer/presential_participation_updated.html.erb
close https://github.com/gip-inclusion/rdv-insertion/issues/2796
Pour reprendre l'exemple de l'issue ca donne ca. J'ai repris la valeur de la pté `instruction_for_rdv` du motif de l'issue de production. On voit qu'il y a eu un retour à la ligne au milieu d'une phrase ! Il faudra être attentif au paramètrage avec le nouveau fonctionnement @amaurydubot .
Avec les bons retours à la ligne ca donnera ca :
=> ui(mails): use html_escape on instruction_for_rdv for notifications

app/services/concerns/notifications/sms_content.rb, app/views/letters/notifications/by_phone_participation_created.html.erb, app/views/mailers/notification_mailer/by_phone_participation_created.html.erb, app/views/mailers/notification_mailer/by_phone_participation_reminder.html.erb, app/views/mailers/notification_mailer/by_phone_participation_updated.html.erb, spec/mailers/notification_mailer_spec.rb, spec/services/notifications/generate_letter_spec.rb, spec/services/notifications/send_sms_spec.rb
Closes #2788 
J'ai remplacé le terme "travailleur social" par "conseiller d'insertion" sur tous les messages de convocation à des rdvs téléphoniques.
@amaurydubot on pourra éventuellement rendre ce terme configuration si on commence à avoir des cas d'usages avec moins de liens directs avec l'écosystème de l'insertion.
=> feat(convocations): Change by phone convocation text

app/clients/api_adresse_client.rb, spec/services/retrieve_address_geocoding_params_spec.rb
Closes #2799 
Je change l'url de search de l'API adresse pour utiliser la nouvelle adresse liée à l'IGN.
=> feat(geocoding): Update Api Adresse Url

app/controllers/super_admins/users_controller.rb, app/models/user.rb, spec/services/users/remove_from_organisation_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2757
J'en ai profité pour enlever les usagers supprimés du scope du `super_admin`.
=> Rgpd(user): anonymize `Users` `last_name` and `first_name` when soft_deleted

app/models/concerns/participation/france_travail_webhooks.rb, app/models/organisation.rb
Comme je le disais dans #2810 on a quelques rdvs qui n'ont pas d'organisation lorsque l'organisation a été supprimée sans les rdvs. 
Je fais en sorte que ce ne soit pas possible en levant une exception lorsque l'on essaie de supprimer une organisation qui a des rdvs associés. 
J'en profite pour faire de même avec les lieux et les motifs.
Aussi, ayant supprimé les 17 rdvs en db qui étaient dans cet état, je fais en sorte d'enlever le safe operator ici:  https://github.com/gip-inclusion/rdv-insertion/pull/2821/commits/43fa2b248220d8c9caeb5523e58e301d8a5f8292
=> feat(org): Raise when deleting an org with rdvs

app/models/webhook_endpoint.rb
Suite à une demande du 78 je change les règles de validation des webhook endpoints pour pouvoir en configurer plusieurs (différentes) par organisations.
Cette évolution me semble logique et va dans le sens de l'architecture proposée par rdv-sp.
=> feat(webhooks): Allow mutliple webhooks per organisation

app/helpers/user_list_upload/invitation_attempts_helper.rb, app/helpers/user_list_upload/user_list_upload_helper.rb, app/views/user_list_uploads/invitation_attempts/_user_row_before_invitation.html.erb
closes #2793 .
Seules les lignes sélectionnées ont un fond bleuté, les lignes non sélectionnées sur fond blanc. La couleur change lorsqu'une ligne est sélectionnée ou déselectionnée (sauf si l'usager est  archivé).
J'en ai profité pour faire pareil sur la page d'invitation:
=> feat(upload): remove bg color when row is not selected

app/helpers/application_helper.rb, app/views/user_list_uploads/user_list_uploads/show.html.erb
closes #2786
Je change le wording à l'upload d'une liste d'usages pour toujours avoir un compteur des états des dossiers:
=> feat(upload): update wording on upload show

app/views/notification_center/_list.html.erb
Cette PR corrige une erreur 500 au chargement du centre de notifs lorsqu'un agent est connecté "en tant que"
=> fix(notifs): fix link when impersionating other agent

app/controllers/concerns/crisp_concern.rb
Je suis tombé sur cette condition concernant   la variable `@should_display_crisp_chatbot` en relisant du code et j'ai remarqué qu'elle pouvait être simplifiée.
J'en profite  pour renommer la méthode qui set la variable.
=> refactor(crisp): simplify crisp concern

config/schedule.yml
Cette PR fait en sorte d'activer les reminders sur l'environnement de démo conformément à ce que l'on s'est dit ici : 
https://mattermost.incubateur.net/betagouv/pl/8ykxmzw97t8giq6njd4qwtbsia
=> fix(demo): make reminders work on demo env

app/controllers/concerns/crisp_concern.rb, spec/features/crisp_chatbox_visibility_spec.rb
suite à https://github.com/gip-inclusion/rdv-insertion/pull/2843
Cela a introduit un bug qui affiche la fenêtre Crisp pour tout le monde.
J'ai ajouté un test de non regression.
C'est potentiellement une bonne idée pour les prospects et les usagers bloqués mais ca fera l'objet d'un travail dédié.
=> fix(crisp): fix crisp refacto for displaying for logged_in agents only

app/jobs/concerns/locked_jobs.rb, app/jobs/deduplicate_rdv_solidarites_webhooks_from_retry_set_job.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/models/rdv_solidarites_webhook_job_wrapper.rb, spec/jobs/deduplicate_rdv_solidarites_webhooks_from_retry_set_job_spec.rb
closes #2844 
Lorsqu'on fait un changement sur un rdv collectif - par exemple si on change son statut - on reçoit autant de webhooks qu'il y a de participants pour ce rdv. Or pour certains rdvs, comme par exemple pour certaines ALI du 93, il peut y avoir une centaine de participants aux rdvs. 
Le traitement de ces webhooks via la classe `InboundWebhooks::RdvSolidarites::ProcessRdvJob` va en plus être assez long puisqu'on va chercher à retrouver chaque participation aux rdvs: https://github.com/gip-inclusion/rdv-insertion/blob/115c8176052d217cc2ba976e2f3dbaed8903a3df/app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb#L155
Du coup, comme ces jobs sont [lockés](https://github.com/gip-inclusion/rdv-insertion/blob/staging/app/jobs/concerns/locked_jobs.rb) pour qu'il ne puisse y avoir …
=> feat(ops): Deduplicate rdv solidarites webhooks

app/controllers/brevo/ip_whitelist_concern.rb
Répare [cette erreur](https://sentry.incubateur.net/organizations/betagouv/issues/180561/?project=16&referrer=webhooks_plugin) en changeant la nature des arguments passés à la méthodes `capture_message` de Sentry sur ce concern.
=> fix(brevo): Fix the way to call Sentry.capture_message

.env.example, app/views/user_list_uploads/invitation_attempts/index.html.erb, app/views/user_list_uploads/user_save_attempts/index.html.erb
Cette PR enlève les références à la popup Tally se trouvant à la fin du parcours d'upload. 
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2888
=> fix(tally): remove tally popup

app/controllers/users/parcours_controller.rb, app/helpers/users_helper.rb, app/policies/department_policy.rb, app/views/users/_user_tabs.html.erb, spec/features/agent_can_upload_documents_for_users_spec.rb
Cette PR fait en sorte de pouvoir faire varier les droits d'accès à l'onglet parcours en y accédant depuis la page d'un département et ce en fonction de l'usager pour lequel on souhaite afficher le parcours.
Plus concrètement, pour afficher l'onglet parcours, il faut réunir les conditions suivantes :  
- Que le parcours soit activé sur le département
- Qu'au moins une orga associée à l'usager soit : 
- de type valide (france_travail, cd, délégataire, etc)
- et que l'agent y ait accès
Avant il fallait seulement que : l'agent fasse partie d'une organisation pour laquelle le parcours était autorisé, et que le département ait le parcours activé
Désormais, il faut que : l'agent fasse partie d'une des organisations de l'usager dans laquelle le parcours est autorisé, et que le département ait le …
=> fix(policy): ensure correct parcours access

app/controllers/concerns/notification_center_concern.rb, app/controllers/notification_center_controller.rb, app/jobs/creneaux/store_all_number_of_creneaux_available_job.rb, spec/features/agent_can_read_notifications_spec.rb
Cette PR fait en sorte de limiter l'accès au centre de notifications aux seules organisations qui traite de motifs categories valides et dont les configurations sont sans référents
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2875
=> feat(notifs): make sure notifications_center isn't shown for categories with referents

config/schedule.yml
Cette PR déplace l'horaire de traitement des stats mensuelles en début de weekend plutôt que le dimanche à 22h. 
Ce changement a été fait car nous avons remarqué que les stats lancée à 22h le dimanche soir se terminent désormais vers 11h le lundi matin (soit un temps de traitement de 13h et un overlap sur des horaires d'activité). 
En déplaçant ce job au Vendredi soir on se donne une marge plus que suffisante qui laissera encore plusieurs années de traitement avant d'overlap à nouveau sur les heures de semaines (la durée de traitement est malheureusement encore fonction du volume de données).
Pour information l'impact sur la DB est assez majeur, d'où la nécessité de déplacer ce job en dehors des heures de traffic :
=> fix(stats): change monthly stat schedule

app/jobs/send_periodic_invites_job.rb, spec/jobs/send_periodic_invites_job_spec.rb
Maintenant que les jobs fail quand l'invitation périodique ne s'envoie pas on a plus de retours d'erreurs.
Ce fix corrige [cette erreur](https://sentry.incubateur.net/organizations/betagouv/issues/183834/?environment=production&project=16&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=2) sur sentry qui empêche l'envoi d'invitations que la personne a déjà un rdv à venir.
Je ne prends donc pas les suivis qui ont pour statut `rdv_pending` pour les suivis sur lesquels on itère. J'en profite pour enlever les suivis clôturés aussi.
=> fix(invitations): Filter follow ups by status for periodic invites

app/javascript/stylesheets/pdf.scss, db/seeds.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2941
Avant | Après
:- | -:
-------------------------------------------
J'en ai profité pour régler un bug dans les seeds, je peux faire une PR séparée pour ce sujet si besoin.
On créait de nouveaux `MessagesConfiguration` pour les orgas des seeds alors qu'ils existent déjà (dans le model `Organisation` grace à `before_create { build_messages_configuration }`)
Cela générait un comportement aléatoire lors de la génération de PDF d'invitations, les valeurs comme `display_department_logo` peuvent varier de manière imprévisible puisqu'il existe plusieurs `MessagesConfiguration`
On pourrait également ajouter une validation pour empêcher que cela ne se produise à l'avenir (des organisation avec plusieurs `MessagesConfiguration`. J'ai …
=> ui(letters): resize rdvsp logo on letters if its the only logo

app/blueprints/participation_blueprint.rb, app/helpers/participations_helper.rb, app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb, app/models/participation.rb, app/models/rdv_solidarites/participation.rb, app/services/stats/compute_rate_of_autonomous_users.rb, config/anonymizer.yml, db/migrate/20250701140708_add_columns_to_participations.rb, db/schema.rb, docs/api/description.md, spec/factories/participation.rb, spec/factories/rdv.rb, spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb, spec/mailers/organisation_mailer_spec.rb, spec/models/concerns/participation/france_travail_payload_spec.rb, spec/models/rdv_spec.rb, spec/services/exporters/generate_users_participations_csv_spec.rb, spec/services/stats/compute_rate_of_autonomous_users_spec.rb, spec/services/upsert_record_spec.rb
Cette PR permet d'afficher l'information de l'agent créateur de la participation (nom + prénom + email) dans la tooltip de date de création de rdv : 
Comme évoqué ensemble, l'idée est de se rapprocher de la solution proposée par Rdv-solidarités. 
En revanche, étant donné que nous ne souhaitons pas pour le moment stocker la donnée de `Prescripteur` -- seulement des `User` et `Agent` simples -- nous ne mettons pas en place le même polymorphisme que Rdvs. 
Du coup le changement est le suivant, nous passons du simple `enum :created_by` à 3 champs : 
- `created_by_type` -> Correspondance parfaite de rdvs (Agent, Prescripteur, User)
- `rdv_solidarites_created_by_id` -> Comme évoqué, nous stockons directement les ids rdvs, pour être explicite on préfixe ce champ
- `created_by_agent_prescripteur` …
=> feat(participation): display agent creator info in tooltip

Gemfile.lock
J'ai constamment cette erreur en local quand j'ouvre une console ou je lance un serveur. Il faut mettre à jour le `gemfile.lock` pour s'en débarasser. 
`'Bundler::Runtime#check_for_activated_spec!': You have already activated stringio 3.1.7, but your Gemfile requires stringio 3.1.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)`
=> tech(gem): update stringio to 3.1.7

app/jobs/migrate_participations_created_by_job.rb, config/anonymizer.yml, db/migrate/20250701140708_add_columns_to_participations.rb, db/schema.rb, lib/tasks/participations/migrate_created_by.rake
Cette PR permet d'extraire la gestion de la migration de la table participations dans un job dédié. 
De cette façon le job pourra s'executer tranquillement sans bloquer la table participations dans une transaction. 
Cela implique aussi de procéder à la suppression de la colonne created_by et rdv_solidarites_agent_prescripteur_id dans une future PR. 
Durant la mise en production de [ceci ](https://github.com/gip-inclusion/rdv-insertion/commit/d1bc46c1daa41182572e4b8a9d849694a479657d) nous avons tenté d'effectuer le remplissage des nouvelles colonnes created_by_type, created_by_agent_prescripteur et rdv_solidarites_created_by_id de manière synchrone durant l'execution de `rails db:migrate`. 
Le problème est que les migrations rails sont executées (et tant mieux) à l'intérieur d'une …
=> feat(participations): running created_by migration in a job

db/migrate/20250717214918_allow_null_for_created_by_in_participations.rb, db/schema.rb
La migration des données de participations prend finalement beaucoup plus de temps que prévu (8h environ). 
Le problème est qu'en attendant certains jobs échoue car la colonne created_by est toujours présente mais n'est pas remplie. 
https://www.rdv-insertion.fr/sidekiq/retries/1752789179.6757653-89ca434cfb4dcd001d958f6a
https://sentry.incubateur.net/organizations/betagouv/issues/188314/?project=16&referrer=webhooks_plugin
On a déjà eu une vingtaine d'occurrences du problèmes en 2 heures. 
Dans la mesure où sa seule utilité est désormais de permettre de remplir les nouvelles colonnes, on peut se permettre d'enlever la contrainte sur le null en attendant que l'on ai fini de migrer les données.
=> fix(participations): allow nil for created_by

app/controllers/concerns/notification_center_concern.rb
Je fix ce flaky qui me cass.. qui m'empêche de déployer depuis tout à l'heure.
En gros on est sensé prendre les CreneauxAvailability créés depuis minuit sauf que ceci `.where(created_at: Time.zone.today...)` ne prenait pas en compte l'ensemble. 
Donc c'est pas vraiment un flaky mais c'était un test dépendant de l'heure à laquelle il tourne
=> fix(flaky): e2e notification center

db/migrate/20250722122431_remove_created_by_and_rdv_solidarites_prescripteur_id_from_participations.rb, db/schema.rb
J'ai remarqué que la migration écrite dans #2981 n'a jamais été lancée et que le schéma n'avait pas été modifié.
Je la relance ici avec le schéma modifié, et je la place après la migration qui consistait à changer la non-null constraint sur  la colonne `created_by` (que l'on enlève ici) et qui était placée après ce fichier de migration.
=> fix(db): Redo unlaunched migration

app/jobs/inbound_webhooks/rdv_solidarites/process_user_job.rb
On a eu des erreurs où on essayait de recréer un usager qui venait d'être supprimé: https://sentry.incubateur.net/organizations/betagouv/issues/185014/?environment=production&project=16&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=3
Voici ce qu'il se passait: 
* L'usager était enlevé de son organisation sur rdv-i et rdv-sp via le CRON qui enlève les usagers archivés depuis + de 2 ans: https://github.com/gip-inclusion/rdv-insertion/blob/d633d8892556efced90666f7c82e6837541f3039/app/jobs/remove_organisation_user_for_expired_archive_job.rb#L20
* L'usager était dans cette organisation seulement, du coup il est soft deleted sur rdv-sp
* L'usager est donc supprimé sur rdv-i (via webhook de suppression de rdv-sp)
* Dans le même moment, on …
=> fix(webhooks): Order ProcessUserJob

app/controllers/inbound_emails_controller.rb, app/jobs/monitor_inbound_emails_activity_job.rb, config/schedule.yml, spec/jobs/monitor_inbound_emails_activity_job_spec.rb
closes #2946 
Pour qu'on soit alerté si jamais les emails des usagers ne sont plus transférés (ce qui est arrivé récemment), je mets en place un CRON qui se lance chaque jour et vérifie que l'on a reçu un email d'usager il y a moins de cette jour.
Pour se faire, on va chercher dans redis le timestamp du dernier inbound email reçu. Je fais donc en sorte qu'on mette à ce jour ce timestamp à chaque fois qu'on reçoit un inbound email.
=> feat(app): Monitor inbound emails activity

app/jobs/monitor_inbound_emails_activity_job.rb, spec/jobs/monitor_inbound_emails_activity_job_spec.rb
Je me suis rendu compte en mergeant #3000 que 7 jours était peut-être trop long avant de lever une alerte, je l'ai réduit à 4 jours.
=> feat(cron): Reduce monitor inbound email threshold

app/controllers/concerns/users/filterable.rb, app/javascript/controllers/flatpickr_controller.js, app/views/dates_filterings/convocation_dates_filterings/new.html.erb, app/views/dates_filterings/creation_dates_filterings/new.html.erb, app/views/dates_filterings/invitation_dates_filterings/new.html.erb, app/views/orientations/_orientation_form.html.erb, spec/features/agent_can_filter_user_by_convocation_or_invitation_spec.rb
Le filtre sur les dates de convocations sur la page index était en fait un filtre sur toutes les notifications envoyées, que ce soit des notifications de création, de modification, d'annulation ou de rappel de rdv.
Or le filtre est censé être sur les convocations et être en accord avec la date affichée dans la liste, à savoir **la date de l'envoi de la notification de rdv créé** (= convocation).
Je corrige cette erreur ici.
J'en profite pour faire une amélioration simple au niveau de l'UX: je me suis rendu compte qu'à chaque fois qu'on propose deux sélections de dates pour un intervalle, il n'y a rien qui empêche au niveau du front de sélectionner une date "après" qui soit antérieure à la date "avant" et vice versa. 
Je mets en place un mécanisme simple pour que cela ne soit plus possible …
=> fix(filters): Fix convocations filters and improve date filterings UX

app/clients/mattermost_client.rb, app/jobs/rgpd_cleanup_organisation_job.rb, app/models/organisation/users_retriever.rb, app/services/organisations/rgpd_cleanup.rb, config/schedule.yml, spec/jobs/rgpd_cleanup_organisation_job_spec.rb, spec/models/organisation/users_retriever_spec.rb, spec/services/organisations/rgpd_cleanup_spec.rb
Suite à [la discussion](https://mattermost.incubateur.net/betagouv/pl/frotff9bx7dxidinkw1iymtmhh) qu'on a eu après le lancement du premier job de cleanup avec les nouvelles règles RGPD, je fais quelques ajustements sur nos règles:
* Je prends en compte la date d'ajout à l'organisation (et non plus la date de création de l'usager) comme critère pour enlever l'usager de l'orga
* J'essaie de prendre en compte les mises à jour de l'usager comme "activité" sur l'usager. Pour cela on ne peut pas se fier au champ `updated_at` parce qu'il est changé alors que l'usager n'a pas été vraiment mis à jour. Du coup je prends en compte les changements dans la table `versions`: au moins on est sûr qu'il s'agit d'une mise à jour "significative" sur l'usager. Le problème est que cette table a été créé il y …
=> fix(rgpd): Add rules to rgpd cleanup

app/jobs/outgoing_webhooks/france_travail/base_job.rb, app/jobs/outgoing_webhooks/france_travail/upsert_participation_job.rb, app/services/france_travail_api/retrieve_user_token.rb, spec/jobs/outgoing_webhooks/france_travail/upsert_participation_job_spec.rb, spec/models/participation_spec.rb, spec/services/france_travail_api/retrieve_user_token_spec.rb
closes #2963 
On fait en sorte ici d'ignorer l'erreur "accès non autorisé" lors de l'appel à l'API FT. Comme expliqué dans l'issue cette erreur arrive de rare fois quand l'usager n'est pas dans notre scope d'usagers FT, auquel cas il ne sert à rien de retenter l'appel.
* Je fais également en sorte de ne pas appeler l'API si la participation n'est plus éligible à être envoyée chez FT entre le moment où on a enqueue le job et le moment où on lance le job. On a notamment un cas d'erreur où on essaie de retenter un appel pour un usager supprimé
* J'ai un peu reformatté l'écriture du test du job parce qu'il comprenait de la logique de callback plutôt liée au model `Participation`.
Il y a encore l'erreur "ID_NON_RECONNU" au moment d'un update d'une participation qui n'est pas pris en compte. On …
=> fix(ft): France Travail webhooks fix

app/services/invite_user.rb, spec/services/invite_user_spec.rb
Il peut arriver, lorsqu'on fait un upload au niveau du territoire, que l'usager soit placé dans une organisation qui ne gère pas la catégorie dans laquelle on fait l'upload.
Si tel est le cas, aucune `category_configuration` n'est trouvé dans le service `InviteUser` et on se retrouve avec ce type d'erreur: https://sentry.incubateur.net/organizations/betagouv/issues/189455/events/206a4e83e8e9456ea02febbb9698fa1d/
En attendant de voir si on ne prévient pas en amont que l'usager est placé dans ce type de catégorie, je mets un message d'erreur plus explicite au niveau du service.
=> fix(invitations): Set explicit error when no category configuration

app/models/concerns/webhook_deliverable.rb, spec/models/concerns/webhook_deliverable_spec.rb
Je me suis rendu compte que l'on avait un problème dans le callback `around_destroy` sur le concern `WebhookDeliverable`: si on appelle la méthode `destroy` sur un record et que cette méthode renvoie `false` (la transaction échoue), on envoie quand même le webhook de destruction. 
Je pense que c'est jamais arrivé parce qu'on supprime jamais la donnée silencieusement (= sans utiliser `destroy!`), mais il est important de rectifier ce comportement.
P.S: sur rdv-sp on a pas ce "bug" parce qu'on enqueue les jobs en créant des entrées dans la table d'exécutions de `good_job`, et du coup cet insert est rollback en même temps que le rollback du record en question. Vu qu'on utilise redis pour pusher nos jobs on n'a pas le même comportement.
=> fix(webhooks): do not send webhook when destruction fails

app/controllers/category_configurations_controller.rb, app/controllers/concerns/cookies_consent_concern.rb
Cette PR apporte deux mini fixs:
* Je trie les `file_configurations` par rapport à leur date de création suite à #3014 pour une meilleure UX
* Je cache la bannière des cookies lorsqu'on se "log en tant que"
=> fix(file_configurations): Order file configurations

Gemfile.lock, config/initializers/with_advisory_lock_patch.rb, spec/initializers/with_advisory_lock_patch_spec.rb, spec/jobs/concerns/locked_jobs_spec.rb
Suite à une longue discussion avec le support de Skylight (voir conversation [ici](https://www.notion.so/gip-inclusion/Dev-2475f321b6048054a61fdac00e9e45d1?source=copy_link#2475f321b60480f58bb1d70c87121e56)), il est apparu que Skylight n'arrivait pas bien à aggréger les requêtes sur notre app et que donc les évènements qui sont présentés par l'appli sont incohérents.
Cela vient du fait que la gem `with_advisory_lock` utilise un alias random `AS ...` pour chaque requête de lock appelé via la méthode `ActiveRecord::Base#with_advisory_lock`. 
Cet alias sert probablement à s'assurer que les requêtes de lock ne sont pas cachées par Rails, même si cette façon de faire est désuette depuis que `ActiveRecord::Base.uncached` existe.
Il semblerait que ce comportement ne soit pas amené à changer pour …
=> fix(deps): Patch `with_advisory_lock` gem methods to use Skylight correctly

app/javascript/stylesheets/reset_dsfr_overrides.scss, app/views/common/_flash_content.html.erb, app/views/common/_header_help_menu.html.erb, app/views/common/_header_website.html.erb, app/views/layouts/_application_base.html.erb
Je me suis rendu compte qu'il y avait plusieurs petits effets de bord avec l'introduction du DSFR qui étaient passés inaperçus et que je tente de corriger ici.
Lorsqu'on clique sur un lien, il y a un changement de la couleur du background de tout l'élément `a` , ce qui peut faire des effets très moches lorsque l'élément cliquable est plus petit que le lien par exemple lorsqu'un bouton est wrapped dans un lien:
C'est fix en ajoutant cet override à la classe `.reset-dsfr-overrides`: https://github.com/gip-inclusion/rdv-insertion/commit/9427fb1ffcca17af318df0f3c8d5c917ded95e78
Lorsqu'on sélectionne un input, l'input sélectionné a une bordure par défaut qui donne un effet désagréable, par exemple ici: 
Je corrige ça en enlevant les propriétés focus sur les input dans la classe d'override: …
=> fix(dsfr): Remove DSFR undesired animations

app/javascript/stylesheets/components/_stat.scss
Cette PR corrige un problème de marge causé par l'ajout du DSFR sur le template du website
=> fix(stats): incorrect margins

app/javascript/stylesheets/application.scss, app/javascript/stylesheets/override_dsfr_defaults.scss, app/views/common/_header.html.erb, app/views/layouts/_application_base.html.erb, app/views/layouts/application.html.erb, app/views/layouts/user_list_upload.html.erb, app/views/layouts/website.html.erb
Il y avait un bug qui faisait apparaitre deux fois l'icône sur les liens  extérieurs: 
Ça vient du fait que le dsfr le rajoute automatiquement sur les liens avec la propriété `target:"_blank"`. 
Je fais en sorte d'overrider cette règle du dsfr.
J'en profite pour renommer la classe css  `reset-dsfr-overrides`, qui était sémantiquement correcte mais un peu confusante IMO.
=> fix(view): Remove icon duplicates on external links

app/models/archive.rb, config/locales/models/archive.fr.yml, spec/factories/archive.rb, spec/jobs/remove_users_from_orgs_with_old_archives_job_spec.rb, spec/models/archive_spec.rb, spec/services/user_list_upload/save_user_spec.rb
En travaillant sur #3083 je me suis rendu compte qu'il était possible d'archiver un usager qui n'appartenait plus à une orga si on ne rafraichissait pas la page de l'usager.
J'ajoute donc une validation au niveau du model `Archive` pour rendre impossible un archivage si l'usager n'appartient pas à l'organisation en question.
=> fix(archive): Add validation on user belonging to org

app/javascript/stylesheets/components/_dropdown.scss, app/views/common/_header_organisation_navigation_button.html.erb
close https://github.com/gip-inclusion/rdv-insertion/issues/3033
Avant | Après
:- | -:
=> fix(ui): keep chevron always visible in organisation select dropdown
