gip-inclusion/rdv-insertion

- db/seeds.rb
Cette PR ajoute les organisations aux seeds du projet, et corrige l'assignation des départements aux agents pour prendre en compte le code à date.
> Updating seeds

- app/controllers/invitations_controller.rb
- app/javascript/react/models/Applicant.js
- app/javascript/react/pages/Applicants.jsx
- app/jobs/notify_applicant_job.rb
- app/models/applicant.rb
- app/models/invitation.rb
- spec/factories/department.rb
- spec/jobs/process_rdv_solidarites_webhook_job_spec.rb
- spec/services/invitations/send_sms_spec.rb
Cette PR contient des petits fix sur l'affichage de l'adresse et de la date de naissance quand ceux-ci ne sont pas présents ainsi que quelques autres micro changements.
> fix(app): fix attributes display

- app/javascript/react/lib/formatPhoneNumber.js
- app/javascript/react/models/Applicant.js
Dans cette PR je formatte les champs rôle et numéro de téléphone du fichier pour prendre en compte les formats d'entrée de la Drôme.
> fix(drome): Format role and phone number

- app/javascript/stylesheets/components/_card.scss
- app/views/organisations/index.html.erb
J'ai fait quelques changements sur la page index des orgas en prévision de l'Aveyron qui aura 6 orgas dans RDVI.
> feat(view): change orga index view

- app/views/stats/index.html.erb
Cette PR corrige un comportement indésiré survenu après le déploiement de la PR #147
> fix(stats): allow display all stats when no department specified

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- config/database.yml
- package.json
Dans cette PR je setup un workflow github actions qui s'éxecutera à chaque push. Il vérifie `rubocop`, `eslint` ainsi que les tests unitaires.
> feat(ops): Setup gh actions

- README.md
- deploy.sh
J'ajoute un script shell qui à l'exécution (`./deploy.sh`), merge automatiquement les changements de `staging` vers `main` et push sur `main` pour déployer les changements en production.
> feat(ops): Add deploy script

- app/clients/rdv_solidarites_client.rb
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/models/rdv_solidarites_session.rb
- app/services/rdv_solidarites_api/base.rb
- spec/controllers/applicants_controller_spec.rb
- spec/controllers/invitations_controller_spec.rb
- spec/controllers/organisations_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/models/rdv_solidarites_session_spec.rb
- spec/services/rdv_solidarites_api/create_user_spec.rb
- spec/services/rdv_solidarites_api/retrieve_invitation_token_spec.rb
- spec/services/rdv_solidarites_api/retrieve_motifs_spec.rb
- spec/services/rdv_solidarites_api/retrieve_organisation_resources_spec.rb
- spec/services/rdv_solidarites_api/retrieve_organisations_spec.rb
- spec/services/rdv_solidarites_api/retrieve_user_spec.rb
- spec/services/rdv_solidarites_api/update_user_spec.rb
- spec/support/authentication_spec_helper.rb
Dans cette PR j'ajoute un mécanisme de vérification de validité de session que j'invoque au moment de la création de la session RDV-Solidarités.
Je modélise la session maintenant dans un objet `RdvSolidaritesSession`.
> refactor(session): validate session on login

- .rubocop.yml
- app/controllers/applicants_controller.rb
- app/javascript/react/components/Applicant.jsx
- app/javascript/react/models/Applicant.js
- app/javascript/react/pages/ApplicantsUpload.jsx
- app/models/applicant.rb
- app/models/department.rb
- db/migrate/20220111152434_add_department_to_applicants.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/applicants_controller_spec.rb
- spec/factories/applicant.rb
- spec/models/applicant_spec.rb
Séparation de la PR #178 en 2 parties [1/2]
> refactor(applicant): Add department to applicant

- app/jobs/soft_delete_applicant_job.rb
- app/models/applicant.rb
- db/migrate/20220111162622_rename_custom_id_to_department_internal_id.rb
- db/schema.rb
- spec/jobs/soft_delete_applicant_job_spec.rb
- spec/models/applicant_spec.rb
Séparation de la PR #178 en 2 parties [2/2]
> refactor(applicant): Rename custom id to department internal id

- app/javascript/react/models/Applicant.js
- app/views/organisations/index.html.erb
Quelques petits changements pour pouvoir lire le fichier d'entrée du 64 où les rôles sont `ALLOCATAIRE` et `CONJOINT(E)`
> fix(upload): adapt upload to 64 entry file

- app/controllers/stats_controller.rb
- app/javascript/react/models/Applicant.js
- app/models/stat.rb
- app/policies/department_policy.rb
- app/views/organisations/index.html.erb
- spec/policies/department_policy_spec.rb
Dans cette PR je fais plusieurs petits fixs sur l'app: 
* J'essaie de régler les N+1 queries que l'on a sur la page d'accueil lorsque l'on calcule les stats
* Je change la policy du département pour que l'agent puisse ajouter sur le territoire même s'il n'appartient pas à toutes les orgas
* Je filtre l'envoi des rôles et des civilités lorsque celles-ci ne correspondent pas aux valeurs attendues
* Je remets le raccourci pour ajouter les allocataires depuis la page index des orgas:
> fix(app): small improvements

- .rubocop.yml
- app/controllers/api/v1/applicants_controller.rb
- app/controllers/api/v1/application_controller.rb
- app/controllers/concerns/api/v1/params_validation_concern.rb
- app/jobs/create_and_invite_applicant_job.rb
- app/jobs/invite_applicant_job.rb
- app/mailers/department_mailer.rb
- app/models/rdv_solidarites_session.rb
- config/routes.rb
- db/migrate/20220126170508_add_email_and_phone_number_to_departments.rb
- db/schema.rb
- spec/mailers/previews/department_preview.rb
Dans cette PR j'ajoute l'endpoint pour créer et inviter des allocataires par batch par l'API. 
Toutes les spécifications de cet endpoint sont décrits ici: https://pad.incubateur.net/s/3lA9V4g5Q
Je merge cette PR pour la démo avec le 13 demain, j'implémenterai les tests de l'endpoint et des nouveaux jobs créés par la suite.
> feat(api): Add create and invite many endpoint

- app/controllers/api/v1/applicants_controller.rb
- app/controllers/api/v1/application_controller.rb
- app/controllers/applicants_controller.rb
- app/controllers/concerns/api/v1/params_validation_concern.rb
- app/jobs/create_and_invite_applicant_job.rb
- app/jobs/invite_applicant_job.rb
- app/policies/organisation_policy.rb
- config/routes.rb
- spec/jobs/create_and_invite_applicant_job_spec.rb
- spec/jobs/invite_applicant_job_spec.rb
- spec/requests/api/v1/applicants_request_spec.rb
- spec/support/authentication_spec_helper.rb
Dans cette PR je fais quelques ajustement par rapport à l'endpoint mis en place pour les BDR: 
* On utilise l'ID de l'orga RDV-S plutôt que l'ID RDV-I (à leur demande par homogénéité par rapport aux autres paramètres)
* J'ajoute les tests
> fix(api): Finish create and invitation many endpoint

- app/javascript/lib/retrieveContactPhoneNumber.js
- app/javascript/lib/retrievePhoneNumber.js
- app/javascript/react/components/EnrichWithContactFile.jsx
- app/javascript/react/components/FileHandler.jsx
- app/javascript/react/pages/ApplicantsUpload.jsx
J'ajoute la précision du .csv dans le bloc données de contacts. 
J'ajoute également une erreur lorsque le fichier n'est pas au format csv pour que l'erreur soit visible (le code qui suit ne peut pas s'exécuter sinon).
J'en profite pour simplifier la lecture de la condition pour récupérer le numéro de téléphone.
> fix(jsapp): Precise .csv for contacts file

- app/views/layouts/mailer.html.erb
Je suis pas sûr que ma tentative de résoudre #96 ait marché, dans le doute je remets le logo RDV-I.
> fix(mailer): reinsert rdvi logo in mails

- app/javascript/react/components/Applicant.jsx
- app/javascript/react/models/Applicant.js
- app/javascript/react/pages/ApplicantsUpload.jsx
- app/views/invitations/invitation_letter.html.erb
J'ajoute la prise en compte d'une colonne "numéro de rue" lorsque celle-ci est présente, c'est notamment le cas de l'Aude.
J'en profite pour enlever une méthode qu'on utilisait plus dans `Applicant.js` et mettre conditionnellement la signature du responsable dans l'export pdf.
> refactor(jsapp): take street number into account

- app/models/responsible.rb
- app/views/invitations/invitation_letter.html.erb
- db/migrate/20220310085941_add_role_to_responsibles.rb
- db/schema.rb
- spec/factories/responsible.rb
J'ajoute le rôle au responsable que l'on ajoute au courrier
> feat(pdf): add role to responsible

- app/services/invitations/send_sms.rb
- app/views/mailers/invitation_mailer/first_invitation.html.erb
- spec/services/invitations/send_sms_spec.rb
Dans cette PR, je change le message des sms et mails d'invitation afin de parler de "rendez-vous d'orientation" plutôt que de "rendez-vous d'accompagnement".
> fix(invitations): change invitation message

- app/mailers/csv_export_mailer.rb
- app/mailers/extraction_mailer.rb
- config/locales/fr.yml
- scripts/extract_applicants_to_csv.rb
Dans cette PR, j'ajoute un script qui permet d'extraire les données des bRSA sous forme de csv, envoyé sur un mail.
> feat(script): add script to extract applicants to csv

- app/helpers/applicants_helper.rb
- app/javascript/react/components/InvitationBlock.jsx
- app/javascript/stylesheets/pages/_applicants.scss
- app/views/applicants/_rdv_context.html.erb
- spec/controllers/applicants_controller_spec.rb
Je fais quelques petits changements au niveau de l'UI suite aux retours fait dans la démo en séparant le bloc "Statut global" du bloc des invitations.
> Feat/small UI changes to contexts

- app/javascript/react/models/Applicant.js
- app/javascript/react/pages/ApplicantsUpload.jsx
Dans cette PR, j'ajoute un champ supplémentaire possible pour le parsing des adresses depuis les fichiers excel, intitulé `street_type`.
> feat(uploads): add streetType fields

- app/javascript/components/tooltip.js
- app/views/applicants/index.html.erb
Lié à #331 . On affiche le bon nombre de jours avant intervention nécessaire dans la tooltip
> fix(applicants): Show right number of days in tooltip

- app/services/create_applicants_csv_export.rb
- spec/services/create_applicants_csv_export_spec.rb
Dans cette PR, je corrige l'encodage des exports csv pour un affichage correct sur Excel.
> fix(export): fix encoding of csv exports

- app/javascript/stylesheets/pdf.scss
- app/views/letters/_footer.html.erb
- app/views/letters/_header.html.erb
Dans cette PR, je modifie la position des logos afin que celui du département reste fixé en haut dans l'en-tête, et que les deux du bas soient mieux collés en bas.
> fix(letters): fix logos positions in invitations letter

- app/javascript/stylesheets/components/_image.scss
- app/views/teleprocedure_landings/_74.html.erb
Dans cette PR, je rajoute une page de fin de téléprocédure pour le 74 (Issue #449)
> feat(teleprocedure): add teleprocedure landing page for 74

- app/controllers/applicants_controller.rb
- app/services/create_applicants_csv_export.rb
- config/locales/models/applicant.fr.yml
- spec/services/create_applicants_csv_export_spec.rb
Dans cette PR, j'ajoute deux colonnes à l'export csv (Issue #441) : 
- date première invitation
- statut "invitation en attente (délai dépassé)"
> feat(csv): add columns to csv export

- app/jobs/send_invitation_reminders_job.rb
Je mets un filtre pour ne pas envoyer les relances en staging
> feat(cron): Do not send reminders in staging env

- .rubocop.yml
- app/controllers/concerns/filterable_applicants_concern.rb
- app/jobs/send_invitation_reminder_job.rb
- app/jobs/send_invitation_reminders_job.rb
- app/services/stats/compute_stats.rb
- app/views/applicants/index.html.erb
- db/migrate/20210927152632_create_rdvs.rb
- db/migrate/20211102171611_change_organisations.rb
- spec/controllers/applicants_controller_spec.rb
Dans cette PR, je corrige le filtre par dates afin que les dates cherchées soit incluses dans le filtrage.
J'ai également modifié l'`AbcSize` de Rubocop afin de le rendre légèrement plus permissif, car on commençait à avoir pas mal de disable dessus.
> fix(app): filter dates by including searched dates

- CONTRIBUTE.md
- INSTALL.md
- README.md
Dans cette PR je mets à jour le `README` pour y ajouter les instructions qui apparaissaient auparavant dans le fichier seeds, notamment en ce qui concerne la synchronisation à RDV-Solidarités.
J'ajoute également une partie `Contribuer` qui énumère les règles de code utilisés au sein de l'application.
> feat(docs): Update readme

- app/services/concerns/invitations/sms_content.rb
- app/views/letters/invitation_for_rsa_accompagnement.html.erb
- app/views/mailers/invitation_mailer/invitation_for_rsa_accompagnement.html.erb
- app/views/mailers/invitation_mailer/invitation_for_rsa_accompagnement_reminder.html.erb
- spec/services/invitations/send_sms_spec.rb
Dans cette PR, je modifie légèrement les messages d'invitation à un rdv d'accompagnement. "suspension" est remplacé par "suspension ou réduction".
> fix(invitation) : change accompagnement invitation message

- app/views/static_pages/privacy_policy.html.erb
Dans cette PR, je met à jour la politique de confidentialité.
NB : pour être conforme à ce que l'on écrit ici, il faudrait peut-être que l'on mette en place le nettoyage des données au bout de 2 ans.
> fix(privacy policy): update privacy policy

- app/views/applicants/show.html.erb
Cette PR répond à la demande exprimée dans l'issue #547
> fix(show): display organisations list at organisation level

- spec/services/stats/compute_stats_spec.rb
Est-ce que comme ça ça te convient ?
> fix(tests): clearer tests for compute stats

- app/controllers/concerns/filter_rdv_solidarites_webhooks_concern.rb
- app/controllers/rdv_solidarites_webhooks_controller.rb
- app/jobs/rdv_solidarites_webhooks/process_lieu_job.rb
- app/models/lieu.rb
- app/models/organisation.rb
- app/models/rdv_solidarites/lieu.rb
- config/initializers/inflections.rb
- db/migrate/20221003170642_create_lieux.rb
- db/schema.rb
- spec/jobs/rdv_solidarites_webhooks/process_lieu_job_spec.rb
Après les motifs c'est maintenant les lieux que je rapatrie sur RDV-I. 
Il est notamment nécessaire d'avoir ces derniers en base au moment d'envoyer les convocations pour avoir des informations tels que le nom et le numéro de téléphone du lieu en question.
Cette PR est lié à cette PR sur RDV-Solidarités: https://github.com/betagouv/rdv-solidarites.fr/pull/2879
> feat(app): Create Lieux table

- app/javascript/components/tooltip.js
Dans cette PR, je retire la mention aux non-invités dans le tooltip de l'index des bénéficiaires (issue #582)
> fix(front): remove non invites from action required

- app/javascript/react/lib/updateApplicantContactsData.js
issue #592 
Dans cette PR, je permets l'update des contacts des bRSA avant même la création du compte.
> update applicants contacts before account creation

- app/controllers/agents_applicants_controller.rb
- app/models/agent.rb
- app/models/applicant.rb
- app/views/agents_applicants/create.turbo_stream.erb
- app/views/agents_applicants/new.html.erb
- app/views/applicants/_add_to_org_button.html.erb
- app/views/applicants/_agents_list.html.erb
- app/views/applicants/show.html.erb
- config/locales/models/applicant.fr.yml
- config/routes.rb
- db/migrate/20221116163348_create_applicants_agents_table.rb
- db/schema.rb
- spec/controllers/agents_applicants_controller_spec.rb
Dans cette PR je rajoute le lien entre les agents et les applicants et je rajoute un bouton sur la page show pour faire ce lien
> feat(app): Add applicants <-> agent assignation

- app/models/participation.rb
- db/migrate/20221209103823_rename_applicants_rdvs_to_participations.rb
- db/schema.rb
Rien d'extraordinaire. J'anticipe pour https://github.com/betagouv/rdv-insertion/issues/663
> refactor(applicants_rdvs) Renommage table de jointure applicants_rdvs en participations

- app/controllers/applicants_controller.rb
- app/models/motif.rb
Lié à #634 
Dans cette PR j'affiche les catégories de motifs dans la page index et la page show dans l'ordre chronologique du parcours du bénéficiaire.
> feat(view): Order motif categories chronologically

- app/controllers/uploads_controller.rb
Suite de #696 , je trie aussi les catégories lors du choix du contexte sur la page upload
> feat(view): Order categories chronologicallyy on upload page

- app/javascript/react/models/Applicant.js
- app/javascript/react/pages/ApplicantsUpload.jsx
Close #716 
Suite à la PR #712 le fichier de contact ne se charge plus correctement.
Ce petit fix règle le problème qui est lié au changement dans la structure de l'array applicants dans fichier ApplicantList.jsx qui est passé de : 
```return applicants.map(({ applicant }) => (```
à :
```return applicants.map(( applicant ) => (```
> [BUG] Import fichier de contacts (Suite à la PR #712)

- app/javascript/react/pages/ApplicantsUpload.jsx
> Ajout du mot CNAF dans le bouton d'import de contact

- app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb
Dans cette PR j'évite le fait  que 2 webhooks du même RDV soient processés en même temps.
L'idée c'est d'essayer d'éviter de créer une participation qui existe déjà (voir cette erreur sentry: https://sentry.incubateur.net/organizations/betagouv/issues/7862/?project=16&query=is%3Aunresolved).
Cependant le fait de les traiter en série ne nous garantit que quand le 2eme job va être traité la participation sera déjà inséré en base au moment de fabriquer les `participation_attributions`, puisque l'upsert ne se fait pas directement dans ce job qui traite le webhook de rdv mais en  asynchrone dans le `UpsertRecordJob`.
Peut-être que ça peut déjà en diminuer les occurences.
Une solution pérenne à ce problème s'il persiste serait que les participations soit traitées via des webhooks de …
> fix(webhooks): Try avoiding race conditions when processing rdv job

- app/mailers/invitation_mailer.rb
- app/mailers/notification_mailer.rb
- app/models/concerns/templatable.rb
- app/models/motif.rb
- app/services/concerns/invitations/sms_content.rb
- app/services/invitations/generate_letter.rb
- app/views/letters/regular_invitation.html.erb
- app/views/mailers/invitation_mailer/regular_invitation.html.erb
- app/views/mailers/invitation_mailer/regular_invitation_reminder.html.erb
- app/views/mailers/notification_mailer/by_phone_rdv_created.html.erb
- app/views/mailers/notification_mailer/presential_rdv_created.html.erb
- config/locales/models/motif.fr.yml
- config/templates/applicant_messages.yml
- spec/mailers/invitation_mailer_spec.rb
- spec/services/invitations/generate_letter_spec.rb
- spec/services/invitations/send_sms_spec.rb
close issue #732 #749 
- Ajout du nouveau contexte SPIE.
- Parametrisation du applicant_designation (globalement : "bénéficiaire du RSA" mais dans le contexte spie c'est "demandeur d'emploi")
> Feat(app) Add rsa spie context and parameterize applicant_designation

- Gemfile.lock
- db/seeds.rb
Dans cette PR, je modifie la durée des number_of_days_before_action_required dans les seeds pour permettre les invitations courrier lors d'une install standard + je fix quelques commentaires.
> fix(seeds): micro fix for seeds

- app/models/organisation.rb
- app/views/applicants/_applicants_list_header.html.erb
close #801 
Rien d'extraordinaire mais un bouton pratique vers les orgas rdv-s directement dans rdv-i.
Voila ce que ca donne. Je peux changer le design si besoin :)
> feat(organisation link) Link to RDV-S organisation path

- app/controllers/applicants_controller.rb
- app/views/applicants/_applicants_list_header.html.erb
- app/views/organisations/index.html.erb
close #805 #767 
Pas vraiment complexe mais ca va être pratique aussi.
A voir dans le cas ou il y a vraiment bcp d'orgas la tête de la dropdown.
> feat(organisations) Pouvoir changer d'organisation depuis l'index.

- .github/workflows/ci.yml
- app/controllers/applicants_controller.rb
- app/controllers/concerns/applicants/convocable.rb
- app/controllers/concerns/applicants/filterable.rb
- app/controllers/concerns/before_action_override.rb
- app/helpers/applicants_helper.rb
- app/javascript/components/tooltip.js
- app/models/motif.rb
- app/models/rdv_context.rb
- app/views/applicants/_applicants_table_for_motif_category.html.erb
- app/views/applicants/_convocation_button.html.erb
- app/views/applicants/_rdv_context.html.erb
- spec/features/agent_can_convene_applicant_spec.rb
Dans PR j'ajoute  un bouton pour pouvoir convoquer un allocataire lorsque le délai pour accepter l'invitation est dépassé.
Ce bouton redirige vers la prise de rdv sur RDV-S pour le bénéficiaire sur un motif qui comporte la mention "convocation" dans son nom. Si aucun motif de ce type n'est présent sur RDV-S, le boutton est désactivé et nous affichons un message pour nous contacter.
* applicants#index: 
* applicants#show:
> feat(convocation): Add convocation button

- app/mailers/invitation_mailer.rb
- app/services/concerns/invitations/sms_content.rb
- app/views/letters/atelier_invitation.html.erb
- app/views/mailers/invitation_mailer/atelier_invitation.html.erb
- spec/mailers/invitation_mailer_spec.rb
- spec/services/invitations/generate_letter_spec.rb
- spec/services/invitations/send_sms_spec.rb
closes #834 
Dans cette PR, je fais les modifications demandées pour les messages d'invitation liés aux ateliers
> feat(invitations): change ateliers messages

- app/controllers/static_pages_controller.rb
- app/views/common/_footer.html.erb
- app/views/static_pages/cgu.html.erb
- app/views/static_pages/legal_notice.html.erb
- app/views/static_pages/privacy_policy.html.erb
- config/routes.rb
- spec/controllers/static_pages_controller_spec.rb
closes #821 
ajout des CGU et modification de la politique de confidentialité et des mentions légales
> feat(app): add cgu and change other legal stuff

- app/helpers/applicants_helper.rb
> fix(app): fix new applicant link at organisation level

- app/views/organisations/edit.html.erb
Voir https://mattermost.incubateur.net/betagouv/pl/4rgwhqza83ygmce1hen8y4uqbo
> fix(view): Fix cancel link in organisation details

- app/models/concerns/motif_category/sortable.rb
- db/migrate/20230328124553_add_orientations_motif_categories.rb
- db/schema.rb
- spec/support/motif_categories_helper.rb
closes #927 #928 
Dans cette PR, j'ajoute les deux nouveaux contextes d'orientation demandés par le Var
> feat(category): add orientations motif_categories

- app/jobs/rdv_solidarites_webhooks/process_referent_assignation_job.rb
- app/jobs/rdv_solidarites_webhooks/process_user_profile_job.rb
J'essaie ici de fix les erreurs suivantes qui créent du bruit dans sentry: 
* https://sentry.incubateur.net/organizations/betagouv/issues/24303/?project=16&query=is%3Aunresolved
* https://sentry.incubateur.net/organizations/betagouv/issues/25642/?project=16&query=is%3Aunresolved
> fix(jobs): Avoid race conditions on webhook jobs

- config/initializers/cors.rb
Test Cors pour inclusion connect
> Cors for callback

- config/initializers/cors.rb
Encore un test de conf cors pour le staging
> Test cors avec /auth

- app/javascript/react/models/Applicant.js
Corrige un bug au chargement d'une liste de bénéficiaire sur la page upload.
> fix(upload): fix shouldDisplay method in Applicant.js

- config/initializers/cors.rb
Je rollback les changements que l'on a testé ce matin avec Quentin en attendant de trouver une solution viable
> Rollback cors changes

- app/views/organisations/_organisation_form.html.erb
Micro changement pour ordonner alphabétiquement la liste des départements de la modal `new`pour les `organisations`.
> feat(configurations): order department list for new organisations

- spec/jobs/rdv_solidarites_webhooks/process_rdv_job_spec.rb
En local, cela faisait plusieurs semaines que j'avais un bug récurrent sur le test du `process_rdv_job`, test qui passait généralement sur la CI (mais pas toujours ; il nécessitait parfois d'être relancé). Sur ma dernière PR, il ne passe définitivement plus : je fais donc ici un petit fix pour que cela ne se produise plus.
> fix(tests): fix broken test for process rdv job

- db/migrate/20230427122751_change_default_values_for_configurations.rb
- db/schema.rb
- spec/controllers/invitations_controller_spec.rb
closes #955 
Dans cette PR, je change la valeur par défaut des colonnes `convene_applicant` et `invite_to_applicant_organisations_only` de la table `configurations`
> feat(configurations): change columns default values

- app/jobs/designate_on_watch_developer_job.rb
Ce n'est qu'un au revoir 😢 🙋‍♂️
> chore(app): Remove Romain from on watch developers

- spec/factories/rdv_context.rb
- spec/features/agent_can_close_or_reopen_rdv_context_spec.rb
> feat(rdv_contexts): add feature test for closings of rdv_contexts

- app/javascript/lib/datesHelper.js
- app/javascript/react/pages/ApplicantsUpload.jsx
Cette PR répond au problème de date soulevé par Salma dans le 44.
Je fais une petite modification pour permettre plus de flexibilité sur les formats de date pris en charge.
> feat(upload): allow more dates formats on upload

- app/models/applicant.rb
- app/services/applicants/find_or_initialize.rb
Cette logique est présente dans #1026 mais j'en extrais un fix ici car elle cause des soucis sur certains départements (voir https://mattermost.incubateur.net/betagouv/pl/pastrzayqifkdnoid9pjzhbjgo)
> fix(app): Retrieve only active applicants

- app/views/applicants_organisations/_applicants_organisation.html.erb
Cette PR permet d'aligner les formulaires dans la modale d'assignation d'une organisation.
> fix(view): Align forms in organisation assignation modal

- app/views/applicants_organisations/_applicants_organisation.html.erb
Il y avait encore un problème de largeur de l'input quand on avait des catégories avec des noms longs, ça devrait être bon maintenant :)
> fix(view): input size in assign organisation form

- app/views/common/_inclusion_connect_button.html.erb
> fix(inclusion_connect): add turbo false for IC link

- app/javascript/react/components/applicant/CarnetCreationCell.jsx
- app/models/applicant.rb
- spec/features/agent_can_create_carnet_spec.rb
Il semblerait que ce soit plutôt les managers qui seront amenés à créer des carnets, je change l'url du carnet en conséquence
> fix(cdb): Change carnet url

- app/javascript/react/components/applicant/CarnetCreationCell.jsx
- app/models/applicant.rb
- spec/features/agent_can_create_carnet_spec.rb
Les url sur la doc n'étaient pas les bons, je les change même si pour l'instant on peut pas accéder au lien directement depuis rdvi
> fix(cdb): Change url again

- app/controllers/convocations_controller.rb
- spec/features/agent_can_convene_applicant_spec.rb
On voudrait prendre le premier rdv disponible lorsqu'on convoque sur un rdv collectif.
> fix(app): Convene on first available collectif rdv

- app/controllers/invitations_controller.rb
- spec/controllers/invitations_controller_spec.rb
Issue: https://github.com/betagouv/rdv-insertion/issues/1053
> fix(invitation): add a clear error message

- app/jobs/designate_on_watch_developer_job.rb
J'ajoute @Michaelvilleneuve à la liste des développeurs de vigie, de sorte à ce qu'il commence à prendre le rôle dans deux semaines.
> feat(org): Add Michael to on watch list

- app/javascript/react/components/ApplicantList.jsx
- app/javascript/react/models/Applicants.js
- app/javascript/react/pages/ApplicantsUpload.jsx
Cette PR permet d'afficher les lignes en erreurs en premier lors d'une action par batch. 
Résoud #1240
> feat(upload): display invalid applicants firsts

- app/javascript/react/pages/ApplicantsUpload.jsx
Afin de pouvoir afficher la liste correctement je l'ai sortie du conteneur parent, de cette façon elle n'est plus limité en largeur. J'ai ensuite rajouté un padding pour éviter qu'elle se colle au bord, et j'ai mis la div parent de la table en overflow-scroll. 
De cette façon sur des écrans plus petits la table devient scrollable.
https://github.com/betagouv/rdv-insertion/assets/4990201/59323688-b895-4647-9371-79369a33d7f5
Corrige #1016
> fix(css): better responsiveness of applicant list

- app/javascript/react/components/Applicant.jsx
- app/javascript/react/components/ApplicantList.jsx
- app/javascript/react/components/applicant/EditableCell.jsx
- app/javascript/react/models/Applicant.js
- spec/features/agent_can_edit_uploaded_applicant_list_spec.rb
Cette PR permet de corriger un problème de duplication évoqué par Salma [ici](https://mattermost.incubateur.net/betagouv/pl/kwu8r8jy4ibm7x415f9z7n6acw)
J'ai également ajouté quelques correctifs UX pour les champs: 
- select au lieu de input pour la civilité
- input style bootstrap plutôt qu'un input brut
> fix(upload): Deduplication of rows and UX fixes

- app/javascript/react/components/applicant/CreationCell.jsx
- app/javascript/react/models/Applicant.js
En déplaçant le CTA plus haut dans la pile de conditions cette PR fait en sorte d'éviter que l'on puisse avoir une ligne en erreur sans CTA adapté (rouge)
> fix(upload): always display error CTA when invalid

- app/javascript/react/models/Applicant.js
Cette PR permet d'éviter de reset les erreurs d'une ligne en erreur lors d'un click sur "Résoudre les erreurs" si jamais la ligne présente toujours des erreurs.
> fix: prevent flushing errors when invalid

- db/schema.rb
Juste pour enlever la colonne custom_image commit par erreur
> fix: remove useless column

- app/jobs/transfer_email_reply_job.rb
- spec/jobs/transfer_email_reply_job_spec.rb
Pour résoudre [cette erreur](https://sentry.incubateur.net/organizations/betagouv/issues/60989/?alert_rule_id=9&alert_timestamp=1693406488542&alert_type=email&environment=production&project=16&referrer=alert_email), survenue après le déploiement de [cette PR](https://github.com/betagouv/rdv-insertion/pull/1151)
> fix(mailers): fix bugs for ReplyTransferMailer

- db/seeds.rb
- spec/support/motif_categories_helper.rb
En rechargeant mes bases de donnée et les seed en local j'ai eu une petite erreur suite à [cette pr](https://github.com/betagouv/rdv-insertion/pull/1249)
Il y avait également un oubli dans le `MotifCategoriesHelper`
> fix(seed): add mandatory attributes for template model in seed

- app/views/mailers/notification_mailer/presential_participation_reminder.html.erb
Petite typo repérée dans un message, petit fix pour la corriger.
> fix(convocations): fix typo

- .github/ISSUE_TEMPLATE/new_motif_category.md
- app/services/concerns/invitations/sms_content.rb
- app/views/mailers/invitation_mailer/atelier_enfants_ados_invitation.html.erb
- app/views/mailers/invitation_mailer/atelier_enfants_ados_invitation_reminder.html.erb
- app/views/mailers/invitation_mailer/atelier_invitation.html.erb
- app/views/mailers/invitation_mailer/short_invitation.html.erb
- app/views/mailers/invitation_mailer/short_invitation_reminder.html.erb
- app/views/mailers/invitation_mailer/standard_invitation.html.erb
- app/views/mailers/invitation_mailer/standard_invitation_reminder.html.erb
- spec/services/invitations/send_sms_spec.rb
closes #1182 
Dans les différents messages, la mention "En cas de problème technique, contactez le" est remplacée par "En cas de problème, contactez le"
> feat(messages): change "problème technique" by "problème"

- app/models/concerns/motif_category/sortable.rb
J'ajoute la catégorie `rsa_suivi_plie` dans le tableau qui trie les catégories de motifs en attendant de développer #1387
> feat(category): Order rsa_suivi_plie category

- app/views/mailers/invitation_mailer/atelier_enfants_ados_invitation.html.erb
- app/views/mailers/invitation_mailer/atelier_enfants_ados_invitation_reminder.html.erb
- spec/mailers/invitation_mailer_spec.rb
Cette PR modifie le texte des mails du contexte ASE
Corrige https://github.com/betagouv/rdv-insertion/issues/984
> fix(wording): small change in ASE mails

- app/controllers/configurations_controller.rb
- spec/controllers/configurations_controller_spec.rb
Juste un oubli de re-nommage du param convene_user dans le controller
> fix(configurations): convene_user was broken

- app/clients/inclusion_connect_client.rb
- spec/clients/inclusion_connect_client_spec.rb
- spec/controllers/inclusion_connect_controller_spec.rb
Suite à un changement au niveau de inclusion connect il faut adapter les endpoints.
https://mattermost.incubateur.net/betagouv/pl/wnpbu9ax6brmz8x8rtmdyrimdc
> fix(inclusion_connect): change auth path

- app/javascript/react/models/Users.jsx
- app/javascript/react/pages/UsersUpload.jsx
Juste histoire de centrer toute la logique des colonnes et rows au même endroit
> fix(batch): move behavior where it belongs

- db/migrate/20231013132233_add_position_to_configuration.rb
- db/schema.rb
Cette PR permet de s'assurer que tous les éléments de cette table aient un sorting par défaut
> fix(db): add default values to position and department_position

- app/controllers/concerns/users/sortable.rb
Je remets ici la simplification de la requête faite dans #1490 et enlevé lors pour le hotfix de #1503
> refactor(ordering): Simplify order request

- app/jobs/rdv_solidarites_webhooks/process_agent_job.rb
- app/jobs/rdv_solidarites_webhooks/process_agent_role_job.rb
- spec/jobs/rdv_solidarites_webhooks/process_agent_job_spec.rb
- spec/jobs/rdv_solidarites_webhooks/process_agent_role_job_spec.rb
Stop trying to upsert intervenants roles jobs for agent and agent_roles
> bug(jobs): does not process intervenants agent and agent_role jobs

- app/blueprints/agent_blueprint.rb
- app/blueprints/lieu_blueprint.rb
- app/blueprints/motif_blueprint.rb
- app/blueprints/organisation_blueprint.rb
- app/blueprints/rdv_blueprint.rb
- app/blueprints/user_blueprint.rb
- app/models/concerns/webhook_deliverable.rb
Je fais un fix temporaire ici pour les BDR où je rétablis les ids rdv-solidarités en tant que "id" le temps qu'ils fassent le changement de leur côté.
> fix(webhooks): Revert changes temporarly for BDR

- app/views/static_pages/privacy_policy.html.erb
closes #1602 
Mise à jour de la politique de confidentialité, conformément au ticket référencé ci-dessus.
> feat(static): update privacy policy

- app/controllers/referent_assignations_controller.rb
- config/routes.rb
Bon cette fois le bug est résolu, ça marche sur la partie React mais également sur le reste, il faudra faire un fix pour arranger le routing pour la partie React.
> fix(referent): broken show assignation

- app/controllers/referent_assignations_controller.rb
- app/javascript/react/actions/assignReferent.js
- app/javascript/react/components/user/ReferentAssignationCell.jsx
- config/routes.rb
Fix de la partie React pour utiliser les nouvelles routes et re-basculer sur la structure Current
> fix: using new routing for referent assignation

- app/jobs/inbound_webhooks/rdv_solidarites/process_agent_job.rb
- app/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job.rb
- spec/jobs/inbound_webhooks/rdv_solidarites/process_agent_role_job_spec.rb
Lié à #1579 .
Je fixe ici les erreurs dans le `ProcessAgentJob` obtenues lorsqu'on essaie de supprimer un agent qui a déjà été supprimé (ça arrive notamment lorsqu'un agent appartient à plusieurs organisations). 
J'en profite aussi pour changer le `ProcessAgentRoleJob`:
* On upsert l'agent de manière **synchrone** s'il n'existe pas
* J'enlève la logique censée être temporaire de mettre à jour le `rdv_solidarites_agent_role_id`
> fix(jobs): Do not process already deleted agent webhooks

- app/views/static_pages/welcome.html.erb
> fix(landing): Change SIAE onboarding link

- deploy.sh
Cette PR ajoute un check permettant d'éviter de déployer en production des changements non souhaités.
> feat(deploy): ask before deploy to avoid any unwanted deploy

- app/models/concerns/webhook_deliverable.rb
Je remets la nouvelle sérialisation en staging pour les BDR pour qu'ils puissent tester
> feat(webhooks): set new serialization for webhooks in staging

- .env.example
- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/storage.yml
- db/migrate/20240116093639_create_active_storage_tables.active_storage.rb
- db/schema.rb
Cette PR permet l'ajout de la configuration permettant l'upload de fichier via ActiveStorage et un provider S3 compatible.
Fix https://github.com/betagouv/rdv-insertion/issues/1656
> feat: add file storage configuration

- app/blueprints/agent_blueprint.rb
- app/blueprints/lieu_blueprint.rb
- app/blueprints/motif_blueprint.rb
- app/blueprints/organisation_blueprint.rb
- app/blueprints/rdv_blueprint.rb
- app/blueprints/user_blueprint.rb
- app/models/concerns/webhook_deliverable.rb
J'enlève la logique temporaire qu'on avait mise en place pour les BDR
> feat(webhooks): Remove temporary webhook configuration for bdr

- app/controllers/users/parcours_controller.rb
- app/controllers/users/rdv_contexts_controller.rb
closes #1629 
Le bouton retour vers la page show ne renvoyait plus vers la liste avec les params
> fix(front): users show return button

- app/mailers/csv_export_mailer.rb
- app/views/users/_users_list_header.html.erb
- spec/features/agent_can_download_csv_from_index_page_spec.rb
Juste un changement de wording ainsi qu'une correction de marge :
> fix: minor fixes csv export

- config/schedule.yml
Dans cette PR, nous activons le cron job permettant la destruction périodique des ressources inactives pour raison RGPD
> feat(rgpd): activate cron job

- app/jobs/stats/monthly_stats/upsert_stats_job.rb
J'enlève ce commentaire qui n'est plus d'actualité
> fix(stats): remove useless comment

- app/lib/asset_helper.rb
Je fix ici l'erreur qu'il y avait au niveau de la condition de cette méthode, et je la rends plus compréhensible en faisant paraitre les différences entre environnements
> fix(assets): fix condition in new asset helper

- Gemfile
- Gemfile.lock
- config/skylight.yml
Lié à #1432 . J'ai créé un compte skylight et je mets en place la gem ici pour récupérer les infos dans le dashboard de l'appli.
> feat(ops): Install skylight

- app/views/users/_users_list_header.html.erb
Suite à [cette conversation](https://mattermost.incubateur.net/betagouv/pl/r9dqdnesctge9b375msg3u5n4c) je remets la mention "filtrer par :" au dessus des filtres de tag et intervention nécessaire.
> fix(view): Put back filter message

- app/views/users/_all_users_table.html.erb
- app/views/users/_users_table_for_motif_category.html.erb
Lié à #1732 . Je fais en sorte que l'on redirige vers les infos de l'usager plutôt que les infos de rdvs sur la page show.
> refactor(navigation): Redirect to user info page

- app/policies/rdv_policy.rb
La requête raise une erreur avec la nouvelle version de rails
> fix(csv): Fix failing query due to new defaults

- app/jobs/stats/global_stats/upsert_stat_job.rb
- app/jobs/stats/monthly_stats/upsert_stat_job.rb
Je passe les timeouts à 1 heure. Je mets volontairement pas plus pour qu'on soit notifié dès lors qu'on dépassera, ainsi on saura où on en est là dessus..
> fix(stats): moving to 1 hour timeouts

- app/javascript/stylesheets/_variables.scss
- app/javascript/stylesheets/components/_color.scss
- app/models/parcours_document.rb
- app/views/parcours_documents/_document_form.html.erb
- app/views/parcours_documents/_documents_list.html.erb
> feat(upload): minor visual improvements

- app/javascript/stylesheets/_variables.scss
Juste un petit changement de variable couleur demandé par Samantha
> fix(css): slightly grayer grey

- app/views/letters/_header.html.erb
closes #1797 
dans cette PR, je fais en sorte que l'objet de la lettre descende plus bas afin qu'il n'apparaisse pas dans les fenêtres des enveloppes
> feat(letters): move down object lines in letters

- app/javascript/react/models/Users.jsx
Fix de la typo de sur la page upload décrite dans https://github.com/betagouv/rdv-insertion/issues/1787
> fix(upload): Fix upload typo

- app/services/stats/compute_rate_of_rdv_seen_in_less_than_n_days.rb
Nous avons eu plusieurs record de stat qui n'ont pas été mis à jour ce week-end suite au changement de cacul de la stat `Rdv pris en - de X jours` : #1840 
En analysant les requêtes je me suis rendu compte que comme on utilise `find_in_batches` des nouvelles requêtes étaient effectués tous les 100 records (taille du batch) : 
* Une requête récupérant les `rdv_contexts` se basant sur la requête utilisée dans `stat.users_first_orientation_context` qui est complexe (faisant elle même appel à la requête pour récuper les `users`), donc elle prend à chaque fois + de 500ms 
* Des requêtes pour récupérer les participations et rdvs associés. Le temps de complétion de celles-ci est < 10ms parce qu'on filtre directement sur des ids indexés
Pour améliorer la performance de ce service, j'ai donc: 
* …
> fix(stat): Optimize rate of rdv seen in X days calculation

- app/javascript/react/components/user/EditableCell.jsx
- app/javascript/react/components/user/EditableTags.jsx
- app/javascript/react/models/User.js
Cette PR permet de prendre en compte les mises à jour de tags depuis l'upload indépendamment de leur casse. 
Fix https://github.com/betagouv/rdv-insertion/issues/1862
> fix(tags): made tags case insensitive

- app/views/users/show.html.erb
close https://github.com/betagouv/rdv-insertion/issues/1857
> ux(wording): add Modifier to edit button in user show

- app/views/users/_user_page_header.html.erb
close https://github.com/betagouv/rdv-insertion/issues/1833
> ux(wording): upcase user last_name in show

- app/views/users/_user_tabs.html.erb
- spec/features/agent_can_create_user_through_form_spec.rb
close https://github.com/betagouv/rdv-insertion/issues/1834
Avant
Après
> ux(wording): rename Infos to Informations in user show

- app/javascript/controllers/help_menu_controller.js
- app/javascript/stylesheets/components/_dropdown.scss
- app/views/common/_header.html.erb
- app/views/common/_header_help_menu.html.erb
Cette PR ajoute un menu d'aide avec des liens amenant vers notre gitbook
fix https://github.com/betagouv/rdv-insertion/issues/1858
> feat(header): add help menu

- config/initializers/sidekiq.rb
- config/schedule.yml
Cette PR vient fixer l'autoload des crons jobs qui ne fonctionnait pas car Sidekiq::Cron load par défaut le fichier schedule.yml
Vu que le fichier supporte le ERB j'ai fait les conditions sur l'env directement dans le yml ça sera plus clair comme ça
> fix(cron): sidekiq schedule filter

- app/views/common/_header_help_menu.html.erb
Juste pour enlever un espace que Samantha a vu pendant la rétro
> fix(help_menu): remove space

- app/javascript/controllers/index_table_sorting_controller.js
- app/views/users/_all_users_table.html.erb
- app/views/users/_archived_users_table.html.erb
- app/views/users/_users_table_for_motif_category.html.erb
closes #1920 
Les flèches du sorting ne s'affichaient pas bien + on m'a demandé de mettre des flèches "témoin" lorsqu'il n'y a pas de tri. Cette PR résout ce problème.
> fix(index): arrows for sorting

- app/models/agent_role.rb
- app/models/concerns/rdv_context_status.rb
- app/models/concerns/rdv_participation_status.rb
- app/models/csv_export.rb
- app/models/invitation.rb
- app/models/motif.rb
- app/models/notification.rb
- app/models/orientation.rb
- app/models/rdv.rb
- app/models/template.rb
- app/models/user.rb
- app/models/webhook_endpoint.rb
- db/migrate/20240403125856_change_enum_to_strings.rb
- db/schema.rb
- spec/factories/user.rb
- spec/features/agent_can_edit_organisation_tags_spec.rb
* fix: add migration file
* fix: improved migration
* feat: update all enum to use strings
* fix: default value
* fix: linter
* fix: user factory
* fix: spec
> refactor(enums): unify enums with a string declaration (#1914)

- config/initializers/content_security_policy.rb
Il y avait certaines pages qui posaient problème avec la policy actuelle, notamment la page stat. Je fix ça ici
> fix(config): Change content security rules

- app/controllers/concerns/current_structure.rb
- app/javascript/stylesheets/_fonts.scss
- app/javascript/stylesheets/_variables.scss
- app/javascript/stylesheets/components/_color.scss
- app/views/organisations/index.html.erb
- app/views/users/_user_page_header.html.erb
- app/views/users/_users_list_header.html.erb
close https://github.com/betagouv/rdv-insertion/issues/1962
J'ajoute le nom de la structure sous le nom de l'usager.
Je me suis basé sur le figma de Samantha et j'ai créé des variables et des classes pour pouvoir réutiliser la nouvelle couleur et la taille de la police.
> ux(user_show): add current structure name below user name

- app/dashboards/organisation_dashboard.rb
- app/helpers/users_helper.rb
- app/models/organisation.rb
- app/policies/department_policy.rb
- app/policies/organisation_policy.rb
- app/views/users/_user_tabs.html.erb
- config/locales/models/organisation.fr.yml
- db/migrate/20240430143646_add_organisation_type_to_organisation.rb
- db/schema.rb
- spec/factories/organisation.rb
- spec/features/administrate/super_admin_can_manage_organisations_spec.rb
- spec/features/agent_can_upload_documents_for_users_spec.rb
J'ai traité à la fois le ticket sur l'ajout dans le super admin de l'option mais également la restriction des pages parcours aux organisations non SIAE et l'accès direct uniquement aux agents faisant parti d'une organisation non SIAE.
Voici le script qu'il faudra faire tourner en production une fois déployé (je ne voulais pas mettre ça dans les migrations, c'est un peu lourd). 
```ruby
[
{ id: 279, type: "siae" },
{ id: 298, type: "siae" },
{ id: 304, type: "siae" },
{ id: 309, type: "siae" },
{ id: 297, type: "siae" },
{ id: 310, type: "siae" },
{ id: 144, type: "siae" },
{ id: 230, type: "delegataire_rsa" },
{ id: 227, type: "siae" },
{ id: 234, type: "siae" },
{ id: 233, type: "siae" },
{ id: 286, type: "siae" },
{ id: 141, type: "conseil_departemental" },
{ id: 36, type: …
```
> feat(super_admin): add ability to specify organisation_type

- app/views/letters/invitations/short.html.erb
- app/views/letters/invitations/standard.html.erb
- app/views/letters/notifications/by_phone_participation_created.html.erb
- app/views/letters/notifications/participation_cancelled.html.erb
- app/views/letters/notifications/presential_participation_created.html.erb
closes #2016 
dans cette PR j'ajoute dans les courriers la mention à la MSA à côté du numéro CAF
> add msa mention in letters

- app/controllers/concerns/current_structure.rb
- app/javascript/stylesheets/_text.scss
- app/javascript/stylesheets/_variables.scss
- app/javascript/stylesheets/components/_color.scss
- app/views/users/_user_page_header.html.erb
- app/views/users/_users_list_header.html.erb
Close : https://github.com/betagouv/rdv-insertion/issues/2018
Revert de cette PR : https://github.com/betagouv/rdv-insertion/pull/1975
> ux(user_show): Revert - add current structure name below user name

- app/javascript/stylesheets/_text.scss
- app/javascript/stylesheets/application.scss
- app/views/common/_footer.html.erb
- app/views/common/_header.html.erb
- app/views/static_pages/welcome.html.erb
- app/views/stats/_stats.html.erb
- app/views/stats/deployment_map.html.erb
- app/views/teleprocedure_landings/show.html.erb
- app/views/users/_archive_banner.html.erb
closes #1919 
Dans cette PR, je fais de la police d'écriture Marianne la police par défaut pour toute l'app. J'ai l'impression que c'est un peu moins lisible mais je suis peut-être juste pas encore habitué 🤷‍♂️
> feat(front): use Marianne font across the app

- app/javascript/react/components/user/EditableTags.jsx
- spec/features/agent_can_edit_uploaded_user_list_spec.rb
Cette PR implémente la nouvelle[ UI ](https://www.figma.com/design/I6oGJ4ZliyAhCIZ3Dkahym/Upload-de-fichiers-usagers?node-id=5-12&t=fMAxLlqPyWXBHKfP-0) de modification des tags depuis la page upload
Fix https://github.com/betagouv/rdv-insertion/issues/2015
> feat(tags): implement new tags UI

- app/services/exporters/generate_users_csv.rb
- app/services/exporters/generate_users_participations_csv.rb
- spec/services/exporters/generate_users_csv_spec.rb
- spec/services/exporters/generate_users_participations_csv_spec.rb
Lié à #2023 .
J'affiche la date de création du rdv dans les exports csv.
> feat(exports): Add rdv creation date to csv exports

- .slugignore
Pour réparer les migration en prod.
> fix(migration): migrations are not comiting anymore

- app/javascript/components/login-form.js
- app/javascript/stylesheets/components/_form.scss
- app/javascript/stylesheets/components/_title.scss
- app/views/common/_inclusion_connect_button.html.erb
- app/views/sessions/_login_form.html.erb
- spec/controllers/sessions_controller_spec.rb
closes #2069 
Dans cette PR, je change le design du login-form, en ajoutant notamment un lien "Mot de passe oublié"
> new login form design

- app/models/agent.rb
> fix(super_admins): blank agent name in super_admin

- app/controllers/concerns/users/filterable.rb
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/javascript/application.js
- app/javascript/components/orientation-selector.js
- app/views/users/_filter_by_orientation_type_button.html.erb
- app/views/users/_users_list_header.html.erb
- spec/factories/orientation.rb
- spec/features/agent_can_filter_users_by_orientation_type_spec.rb
Cette PR ajoute un filtre par type d'orientation
Fix https://github.com/betagouv/rdv-insertion/issues/2073
> feat(index): add orientation_type filter

- app/javascript/react/actions/assignReferent.js
- app/javascript/react/lib/handleReferentAssignation.js
- app/javascript/react/models/User.js
À la suite de #2066 et #2085, l'assignation de référents sur la page upload était cassé. Cette PR corrige ce souci.
> fix(upload): fix referent assignation on upload

- app/views/static_pages/welcome.html.erb
> fix(landing): Update calendly link

- app/helpers/application_helper.rb
Fixes #2137 . 
Je pense qu'il faut s'attaquer à #2113 assez rapidement parce que c'est vraiment pas terrible ce qu'on fait ici. C'est compliqué à suivre et ça entremêle plusieurs logiques différentes, c'est donc source d'erreur et compliqué à débugger.
> fix(stats): Display stats correctly when logged in

- app/javascript/stylesheets/components/_qr_code_scanner.scss
Juste un petit fix css sur le QR code scanner sur mobile
> fix(ui): minor css fix

- app/views/super_admins/application/_navigation.html.erb
- app/views/super_admins/organisations/show.html.erb
- app/views/super_admins/users/show.html.erb
Juste un lien vers le super admin RdvSP 
En attendant je réfléchis à la possibilité d'avoir un mode prolongé "En tant que" rdvi<>rdvsp
Fix https://github.com/betagouv/rdv-insertion/issues/2130
> feat(superamdin): add rdvsp super admin link in super admin

- spec/services/invitations/compute_link_spec.rb
- spec/services/invitations/send_sms_spec.rb
> fix(test): use RDV_SOLIDARITES_URL test env variable

- app/jobs/designate_on_watch_developer_job.rb
Je change la liste de vigie, @qblanc sera là la semaine prochaine mais pas toute la semaine et je pense qu'il aura pas le temps d'être de vigie :).
> feat(org): Update vigie list

- docs/api/description.md
Dans #2194 j'avais oublié de rajouter les participations dans le payload montré en exemple dans la description, je répare ça ici.
> feat(doc): Add participations to payload description

- app/javascript/stylesheets/components/_card.scss
- app/views/agent_roles/csv_export_authorizations/_form.html.erb
- app/views/previews/invitations/index.html.erb
- app/views/previews/notifications/index.html.erb
- app/views/referent_assignations/_form.html.erb
- app/views/tag_assignations/_form.html.erb
- app/views/users/_find_rdv_button.html.erb
- app/views/users_organisations/index.html.erb
- app/views/users_organisations/new.html.erb
closes #2199 
Un certain nombre de modals pouvaient dépasser en hauteur la taille de l'écran. Cette PR vise à résoudre ce problème.
> fix(modals): limit modal height and make them scrollable

- app/jobs/organisations/destroy_job.rb
Cette PR supprime de la donnée qui pouvait empecher la suppression d'orga.
> fix(script): delete more things that need to be deleted

- app/javascript/controllers/new_department_archive_form_controller.js
- app/javascript/stylesheets/components/_form.scss
- app/views/archives/_new_batch_form.html.erb
- spec/features/agent_can_archive_and_unarchive_user_spec.rb
Dans cette PR je fix une erreur 500 à la création d'archives au niveau du département sans aucune organisation sélectionnée.
Je rajoute aussi un test pour vérifier ce cas,
Je fix donc https://github.com/gip-inclusion/rdv-insertion/issues/2321 et https://github.com/gip-inclusion/rdv-insertion/issues/2277
> fix(archives): issue when creating archive on department

- app/javascript/react/lib/trackUserListComposition.js
- app/javascript/react/models/Users.jsx
- app/javascript/react/pages/users/Uploads.jsx
Cette PR ajoute un tracking custom de la composition de la liste après un ajout de fichier
fix https://github.com/gip-inclusion/rdv-insertion/issues/2264
> feat(matomo): track user list composition

- app/jobs/designate_on_watch_developer_job.rb
J'ajoute Romain à la liste de vigie suite à son rapatriement  full time sur rdv-i 🔥 🎉
> feat(org): Add Romain to vigie list

- db/seeds.rb
Nouveau param devenu obligatoire qui manquait dans les seeds
> fix(seeds): missing mandatory param

- .slugignore
- db/seeds.rb
Juste quelques fix pour faire marcher les seeds dans un env neutre
Je rajoute la création d'usagers pour permettre la réçeption d'usagers depuis les seeds de rdvsp
Cette PR est liée à celle-ci côté rdvsp https://github.com/betagouv/rdv-service-public/pull/4661
> fix(seeds): broken rdvi links

- db/seeds.rb
Il manquait encore quelques données nécessaire à l'environnement de staging, cf https://github.com/gip-inclusion/rdv-insertion/issues/2266
> fix(seeds): improve staging seeds

- app/controllers/application_controller.rb
- app/javascript/react/components/users/EnrichWithContactFile.jsx
- app/javascript/react/lib/createInvitationLetter.js
- app/javascript/react/lib/handleUserCreation.js
- app/javascript/react/lib/handleUserInvitation.js
- app/javascript/react/lib/retrieveUpToDateUsers.js
- app/javascript/react/lib/trackUserListComposition.js
- app/services/invitations/save_and_send.rb
- app/views/users/_user_remove_from_last_organisation_confirm.html.erb
- spec/features/agent_can_invite_users_from_index_page_spec.rb
- spec/services/invitations/save_and_send_spec.rb
closes #2324 
Je remplace les dernières mentions d' "utilisateurs" par "usagers".
> fix(wording): Replace 'utilisateur' by 'usager'

- .env.example
- app/clients/mattermost_client.rb
- app/helpers/environments_helper.rb
- app/helpers/rdv_insertion_instance_name_helper.rb
- app/javascript/stylesheets/components/_rdv_insertion_instance_name.scss
- app/jobs/refresh_out_of_date_follow_up_statuses_job.rb
- app/views/layouts/_rdv_insertion_instance_name.html.erb
- config/initializers/sentry.rb
- config/schedule.yml
- config/storage.yml
- spec/jobs/refresh_out_of_date_follow_up_statuses_job_spec.rb
Cette PR permet d'ajouter un lien lors du clic sur la bannière et corrige le nom pour l'env de staging.
L'idée est d'y lier cette page notion https://www.notion.so/gip-inclusion/Infos-staging-10d5f321b6048071b1e6d58ae401a802 qui apporte des infos utiles sur l'utilisation de l'environnement
> feat(banner): allow custom banner link

- app/views/website/static_pages/welcome.html.erb
> ui(landing): remove upcased Rdv-insertion

- app/controllers/concerns/turbo_stream_concern.rb
- app/controllers/invitations_controller.rb
- spec/features/agent_can_invite_user_from_user_follow_up_page_spec.rb
Oubli de ma part suite à https://github.com/gip-inclusion/rdv-insertion/pull/2361
J'ai ajouté un test pour éviter que ca ne se reproduise.
> bug(invitation): add missing format response for turbo stream invitation

- app/jobs/destroy_old_ressources_job.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2400
> feat(rgpd): do not send webhooks to bdr for rdv destroyed

- app/views/website/stats/_stats.html.erb
closes #2385 
J'ajoute un séparateur pour les milliers sur les stats. 
Avant:
Après:
> feat(stats): Add delimiter in stat numbers

- app/services/users/remove_from_organisation.rb
- spec/jobs/remove_organisation_user_for_expired_archive_job_spec.rb
- spec/services/users/remove_from_organisation_spec.rb
Fix https://sentry.incubateur.net/organizations/betagouv/issues/129257/events/949605ca3da4441fadc43451621c4f8a/?project=16&referrer=next-event
> fix(job): fix remove user profile for expired archive job for user without rdv_solidarites_user_id

- app/views/super_admins/webhook_endpoints/_collection_item_actions.html.erb
Cette PR évite de déclencher le form lors d'un clic sur le bouton "Annuler"
> fix(superadmin): move listener to button to avoid auto disable

- app/controllers/category_configurations_controller.rb
- app/controllers/file_configurations_controller.rb
- app/controllers/organisations/user_added_notifications_controller.rb
- app/controllers/users_organisations_controller.rb
Cette PR rend simplement l'utilisation de turbo_stream plus explicite dans les méthodes de controller qui semblaient ne rien render
fix https://github.com/gip-inclusion/rdv-insertion/issues/875
> feat(turbo): make turbo_stream response more explicit

- app/views/website/stats/_stats.html.erb
Petite coquille dans la résolution d'un conflit de fichier.
> bug(stats): fix a wording class mistake in stats

- docs/api/description.md
Je mets à jour l'url de demo dans la documentation de l'API suite au changement de nom de domaine.
J'en profite pour la rendre un peu moins verbeuse.
> feat(docs): Improve api docs description

- app/helpers/archives_helper.rb
- app/models/user.rb
- app/models/user_archived_status.rb
- app/views/users/_all_users_table.html.erb
- app/views/users/_archived_banner.html.erb
- spec/features/agent_can_archive_and_unarchive_user_spec.rb
Cette PR ajout le motif d'archive sur la bannière de la page usager show ainsi que sur l'index des usagers. 
fix https://github.com/gip-inclusion/rdv-insertion/issues/2519
> feat(archive): add archive reasons

- app/views/website/teleprocedure_landings/_13.html.erb
Cette PR change le texte de la landing téléprocedure du 13
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2529
> fix(wording): change 13 téléprocédure text

- app/models/agent.rb
- spec/models/stat_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/2581
> ui(referents): hide agents with @inclusion.gouv.fr emails from referent assignation and stats

- app/helpers/users_helper.rb
- app/models/department.rb
- app/views/users/_users_list_header.html.erb
Lié à #2547 .
J'ajoute un lien vers l'index des organisations rdv-sp lorsqu'on est sur la page index des usagers au niveau de toutes les organisations.
> feat(navigation): Add link to rdv-sp organisations index

- app/views/website/static_pages/privacy_policy.html.erb
Cette PR met à jour la politique de confidentialité. 
À noter : dans le fichier donné dans le ticket il y a une erreur sur la description du provider Scaleway. 
J'ai corrigé mais j'attends validation avant de merge
fix https://github.com/gip-inclusion/rdv-insertion/issues/2572
> feat(privacy_policy): update

- app/models/user_list_upload/invitation_attempt.rb
- app/models/user_list_upload/user_save_attempt.rb
Je fais en sorte que les messages d'erreurs soient un peu plus clair quand on a une erreur interne
> fix(upload): Clearer internal error message

- app/views/user_list_uploads/invitation_attempts/_user_rows_after_invitation.html.erb
- app/views/user_list_uploads/invitation_attempts/_user_rows_before_invitation.html.erb
Lié à #2676 .
Je change le nom de la colonne du statut sur les étapes d'invitations dans le nouvel upload.
> feat(upload): Change invitation status column name

- app/jobs/creneaux/store_all_number_of_creneaux_available_job.rb
Cette PR fix l'appel au job dans la boucle, je viens de faire de bout en bout c'est ok 👍
> fix(creneaux): broken creneau job call

- app/controllers/super_admins/blocked_users_controller.rb
- app/models/blocked_user.rb
- app/views/super_admins/blocked_users/_chart.html.erb
- app/views/super_admins/blocked_users/index.html.erb
Closes #2706 .
Je change le graphique des usagers bloqués pour le montrer par jour et non pas par mois.
> feat(super_admins): Show blocked_users by day and not by month

- app/helpers/users_helper.rb
- app/views/users/_users_list_header.html.erb
closes #2705 
J'enlève l'ancien bouton "Réinitialiser les filtres" qui fait doublon.
> fix(view): Delete filter reinitialize button

- app/models/organisation.rb
- app/views/category_configurations/index.html.erb
Closes #2722 
Je change le lien vers RDV-Solidarités de la page `category_configurations#index` pour pointer vers la nouvelle pas de configuration de RDV-S.
> fix(view): Modify config url

- app/helpers/stats_helper.rb
- app/views/category_configurations/index.html.erb
- app/views/website/stats/_stats.html.erb
closes #2549 .
J'ajoute une infobulle avec la description de chaque stat comme mentionné dans l'issue.
Exemple:
> feat(stats): Add stats explanations

- app/views/website/static_pages/accessibility.html.erb
Cette PR met à jour la déclaration d'accessibilité.
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2766
> feat(ally): update accessibility page

- app/javascript/stylesheets/dsfr_overrides.scss
- app/views/layouts/user_list_upload.html.erb
- app/views/users/_csv_export_button.html.erb
- app/views/users/_users_list_header.html.erb
Cette PR corrige des problèmes de CSS sur les boutons en ajoutant le reset sur l'upload ainsi qu'en corrigeant un problème d'after sur les bouton de dropdown
> fix(css): broken css after dsfr update

- app/controllers/concerns/notification_center_concern.rb
- app/controllers/notification_center_controller.rb
- app/models/creneau_availability.rb
- spec/features/agent_can_read_notifications_spec.rb
- spec/models/creneau_availability_spec.rb
Cette PR fait en sorte d'afficher les notifications pour toutes les catégories pour lesquelles le centre de notifications devrait être affiché
> fix(notification_center): make sure all relevant motifs are taken into account

- app/javascript/react/models/User.js
- docs/api/description.md
- swagger/v1/api.json
J'ai oublié d'enlever quelques références à cdb dans #2833 , je le fais ici.
> fix(cdb): remove cdb last occurences

- app/jobs/delete_archive_job.rb
- app/models/user.rb
- app/models/users_organisation.rb
- spec/models/users_organisation_spec.rb
closes #2784 
Je fais en sorte ici de supprimer l'archivage d'un usager d'une orga lorsque l'usager est enlevé de cette orga.
Pour se faire j'ajoute un AR callback au niveau du model `UsersOrganisation` qui enqueue un job de destruction de l'archive après sa destruction.
> feat(archive): Delete archives when removing user from org

- app/views/invitations/invalid.html.erb
suite à https://github.com/gip-inclusion/rdv-insertion/pull/2800
> fix(bug): missing asset extension in invalid_invitations

- app/javascript/stylesheets/components/_button.scss
- app/views/common/_footer.html.erb
- app/views/common/_footer_website.html.erb
- app/views/common/_header.html.erb
- app/views/common/_header_help_menu.html.erb
- app/views/common/_header_organisation_navigation_button.html.erb
- app/views/common/_header_website.html.erb
- app/views/users/_filter_by_creation_dates_button.html.erb
- app/views/users/_filter_by_invitation_or_convocation_dates_button.html.erb
- app/views/users/_filter_by_orientation_type_button.html.erb
- app/views/users/_search_form.html.erb
- app/views/users/_users_list_header.html.erb
- spec/features/agent_can_change_navigation_level_spec.rb
- spec/features/agent_can_invite_users_by_batch_from_index_spec.rb
Cette PR ajoute les IDs nécessaires au tracking de matomo.
Fix https://github.com/gip-inclusion/rdv-insertion/issues/2737
> feat(matomo): add click ids

- app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb
- spec/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job_spec.rb
Cette PR corrige le problème des webhook reçus de la part de rdvs, j'ajoute désormais le department à la création du user
> fix(webhook): add department to user creation

- app/javascript/stylesheets/pages/_upload.scss
close https://github.com/gip-inclusion/rdv-insertion/issues/2928
> NewUpload(ui): Fix user list table height scrolling

- spec/swagger_helper.rb
- swagger/v1/api.json
L'url de l'environnement de démo sur la doc de l'API n'avait pas été mise à jour, je le fais ici.
> fix(api): Fix demo url in docs

- app/views/agent_roles/csv_export_authorizations/_form.html.erb
- app/views/organisations/index.html.erb
- app/views/users/referent_assignations/_form.html.erb
- app/views/users/tag_assignations/_form.html.erb
- app/views/users_organisations/index.html.erb
- spec/features/agent_can_assign_referents_spec.rb
- spec/features/agent_can_edit_user_tags_spec.rb
Je fais deux mini changements sur l'UI dans cette PR:
* Le lien vers l'upload dans l'index des organisations (quand on clique sur "Ajouter des usagers") pointait encore vers l'ancien upload. Je rectifie ça ici
* Je change le wording des boutons où il y avait écrit "Ok" en "OK" (plus correct et plus joli au niveau du wording)
> fix(view): Small UI changes

- app/views/common/_success_modal.html.erb
- app/views/configurations/show.html.erb
Je change le style de sélection de la période de rétention pour avoir un select, qui est plus approprié niveau UX.
> fix(view): Change data retention selection UI

- app/helpers/follow_ups_helper.rb
- app/helpers/participations_helper.rb
- app/javascript/stylesheets/components/_border.scss
- app/javascript/stylesheets/components/_button.scss
- app/javascript/stylesheets/components/_table.scss
- app/models/follow_up.rb
- app/views/common/_sign_out_button.html.erb
- app/views/follow_ups/_follow_up_status_badge.html.erb
- app/views/follow_ups/_follow_up_status_cell.html.erb
- config/locales/models/follow_up.fr.yml
- spec/features/agent_can_close_or_reopen_follow_up_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/3040
J'ai suivi le figma. Les changements en plus ont été validés par Samantha.
https://github.com/user-attachments/assets/793e8efb-648d-4184-86dc-a65f45e98cad
> ux(colors): change status, follow up table and badges colors

- .well-known/security.txt
- app/mailers/organisation_mailer.rb
- app/views/common/_header_website.html.erb
- app/views/convocations/new.html.erb
- app/views/organisations/index.html.erb
- docs/CONTRIBUTE.md
- docs/api/description.md
- swagger/v1/api.json
close https://github.com/gip-inclusion/rdv-insertion/issues/3045
Tant que j'y étais j'ai fait le changement dans toute l'app (pour les reply-to, dans la doc...)
> fix(ux): replace rdv-insertion@beta.gouv.fr with rdv-insertion@inclusion.gouv.fr

- app/javascript/controllers/users_list_filter_controller.js
- spec/features/agent_can_filter_users_with_multiselect_spec.rb
close https://github.com/gip-inclusion/rdv-insertion/issues/3077
J'en ai profité pour ajouter un feature test de non regression.
> fix(filter): multiselect filters broken (uncheck not possible and dup) in user index
